-- ============================================================================
-- portal-schema.sql — 포털 DB 복제본 스키마 단일 생성본 (db/portal/V1~Vn 통합 스냅샷)
--
-- ★ 생성물(수기 편집 금지). gen-schema-sql.sh 가 db/portal 의 DDL 을 적용한 결과를 덤프한다.
--
-- 용도: control 과 물리 분리된 포털 DB(PORTAL_DB_*)에 1회 로드. 저작도구 Flyway 는 control
--   (@Primary) 데이터소스에만 붙으므로 포털 스키마는 설치 단계가 책임진다
--   (17-load-portal-schema.sh). 로드하지 않으면 메타 복제가 조용히 0건으로 유지된다.
--
-- flyway_schema_history 제외. 재생성: deploy/onprem/scripts/gen-schema-sql.sh
-- ============================================================================

--
-- PostgreSQL database dump
--

\restrict XlnFMGZMgSNyrDtJdS6I40y4jxtNa0EjvXLmUjg3L331mbmSEvfLHMzSRJNECoC

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ls_dataset_video_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ls_dataset_video_meta (
    meta_snpsht_sn bigint NOT NULL,
    raw_sn bigint NOT NULL,
    snpsht_hash character varying(64) NOT NULL,
    active_yn character(1) DEFAULT 'Y'::bpchar NOT NULL,
    orgnl_raw_sn bigint,
    vms_clip_id character varying(128),
    vms_cctv_id character varying(64),
    raw_file_path_nm character varying(500),
    sht_dt timestamp without time zone,
    vdo_len_sec integer,
    lclgv_cd character varying(20),
    prvc_yn character(1),
    prvc_type_cd character varying(16),
    de_ident_yn character(1),
    ai_crt_yn character(1),
    evnt_type_cd character varying(20),
    cctv_nm character varying(255),
    wgs84_lat numeric(10,7),
    wgs84_lot numeric(10,7),
    sido_nm character varying(100),
    sgg_nm character varying(100),
    file_fmt character varying(32),
    evnt_nm character varying(255),
    vdo_cdc character varying(20),
    fps numeric,
    bit_rt bigint,
    asprt_rt numeric,
    resl character varying(32),
    vdo_wdth integer,
    vdo_hgt integer,
    file_sz bigint,
    day_ngt_cd character varying(8),
    sesn_cd character varying(20),
    wthr_nm character varying(32),
    rvw_cmpl_dt timestamp without time zone,
    reg_dt timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reg_id character varying(30),
    evnt_anno_cn jsonb
);


--
-- Name: ls_dataset_video_meta_meta_snpsht_sn_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ls_dataset_video_meta ALTER COLUMN meta_snpsht_sn ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ls_dataset_video_meta_meta_snpsht_sn_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ls_dataset_video_meta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ls_dataset_video_meta (meta_snpsht_sn, raw_sn, snpsht_hash, active_yn, orgnl_raw_sn, vms_clip_id, vms_cctv_id, raw_file_path_nm, sht_dt, vdo_len_sec, lclgv_cd, prvc_yn, prvc_type_cd, de_ident_yn, ai_crt_yn, evnt_type_cd, cctv_nm, wgs84_lat, wgs84_lot, sido_nm, sgg_nm, file_fmt, evnt_nm, vdo_cdc, fps, bit_rt, asprt_rt, resl, vdo_wdth, vdo_hgt, file_sz, day_ngt_cd, sesn_cd, wthr_nm, rvw_cmpl_dt, reg_dt, reg_id, evnt_anno_cn) FROM stdin;
\.


--
-- Name: ls_dataset_video_meta_meta_snpsht_sn_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ls_dataset_video_meta_meta_snpsht_sn_seq', 1, false);


--
-- Name: ls_dataset_video_meta ls_dataset_video_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ls_dataset_video_meta
    ADD CONSTRAINT ls_dataset_video_meta_pkey PRIMARY KEY (meta_snpsht_sn);


--
-- Name: ls_dataset_video_meta uk_ls_dataset_video_meta; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ls_dataset_video_meta
    ADD CONSTRAINT uk_ls_dataset_video_meta UNIQUE (raw_sn, snpsht_hash);


--
-- Name: idx_ls_dataset_video_meta_raw_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ls_dataset_video_meta_raw_active ON public.ls_dataset_video_meta USING btree (raw_sn, active_yn);


--
-- Name: idx_ls_dataset_video_meta_rvw_cmpl; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ls_dataset_video_meta_rvw_cmpl ON public.ls_dataset_video_meta USING btree (rvw_cmpl_dt);


--
-- Name: uk_ls_dataset_video_meta_raw_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_ls_dataset_video_meta_raw_active ON public.ls_dataset_video_meta USING btree (raw_sn) WHERE (active_yn = 'Y'::bpchar);


--
-- PostgreSQL database dump complete
--

\unrestrict XlnFMGZMgSNyrDtJdS6I40y4jxtNa0EjvXLmUjg3L331mbmSEvfLHMzSRJNECoC

