package kr.co.cudo.authoring.support;

import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * 전체 테스트가 공유하는 싱글톤 PostgreSQL Testcontainer.
 *
 * <p>MariaDB → PostgreSQL 전환(Phase 3)에 따라 기존 H2 in-memory 테스트 인프라를 대체한다.
 * H2 는 PostgreSQL 의 {@code ON CONFLICT}, {@code GENERATED BY DEFAULT AS IDENTITY} 등
 * 문법을 완전히 지원하지 못해 실제 PG dialect 검증이 불가능했다. 본 컨테이너 위에서
 * Flyway clean migrate + {@code ddl-auto=validate} 부팅 + 전체 테스트를 수행한다.
 *
 * <p>컨테이너는 JVM 당 1개만 기동(싱글톤)하고, JUnit 종료 시 Ryuk(Testcontainers reaper)가
 * 자동 정리하므로 {@code @Container} 라이프사이클이나 명시적 stop() 을 두지 않는다.
 *
 */
public final class PostgresTestContainer {

    private static final DockerImageName IMAGE = DockerImageName.parse("postgres:16-alpine");

    @SuppressWarnings("resource") // 싱글톤 — Ryuk reaper 가 JVM 종료 시 정리한다.
    public static final PostgreSQLContainer<?> INSTANCE = new PostgreSQLContainer<>(IMAGE)
            .withDatabaseName("klid_system")
            .withUsername("klid_test")
            .withPassword("klid_test")
            // 다수의 @SpringBootTest 컨텍스트가 캐시되며 각각 HikariCP 풀을 유지하므로
            // 기본 max_connections=100 이 고갈("too many clients")된다. 충분히 높여 안전 마진 확보.
            .withCommand("postgres", "-c", "max_connections=300")
            .withReuse(true);

    static {
        INSTANCE.start();
    }

    private PostgresTestContainer() {
    }
}
