package kr.co.cudo.authoring.support;

import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.transaction.TestTransaction;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * {@code LS_DATA_RAW}(부모 영상) 시드 공용 픽스처.
 *
 * <p><b>왜 필요한가 (DB-ISSUE-01 / V146)</b>: {@code V146__add_ls_data_raw_child_fk.sql} 이
 * {@code LS_DATA_RAW.RAW_SN} 을 참조하는 자식 테이블 27개에 FK(+{@code ON DELETE CASCADE})를 세웠다.
 * 그 전까지 다수의 테스트가 <b>부모 영상 행을 만들지 않고</b> 자식(프레임·작업상태·배정·비식별로그·
 * 배치큐·export 이력 등)부터 INSERT 해 왔고, 그 데이터는 실제로는 <b>고아</b>였다. FK 신설 후 이런
 * 픽스처는 정당하게 거부되므로, 자식 INSERT 전에 부모를 먼저 시드해야 한다.
 *
 * <p>FK 를 우회(테스트 프로파일에서 제약 해제 / {@code SET CONSTRAINTS DEFERRED} / 제약 drop)하는 것은
 * 금지다 — 그러면 "고아가 구조적으로 불가능" 이라는 V146 의 목적이 사라진다. 본 픽스처는 <b>준비
 * 데이터를 추가</b>하기만 하고, 어떤 단언도 약화시키지 않는다.
 *
 * <h2>사용법</h2>
 * <ul>
 *   <li>{@link #seedRaw(JdbcTemplate, long)} — 테스트가 <b>하드코딩한 rawSn</b>(예: {@code 995_001L})을
 *       그대로 쓰고 싶을 때. 이미 있으면 no-op(멱등).</li>
 *   <li>{@link #newRaw(JdbcTemplate)} — rawSn 값 자체는 의미 없고 "실재하는 영상 1건" 만 필요할 때.
 *       IDENTITY 로 발급받는다({@code System.nanoTime()} 같은 임의값 대체).</li>
 *   <li>{@link #deleteRaws(JdbcTemplate, long...)} — 커밋 시드를 쓰는(비트랜잭션) 테스트의 정리.
 *       CASCADE 로 자식까지 함께 사라진다.</li>
 *   <li>{@link #endAmbientTransaction()} — 클래스 레벨 {@code @Transactional} 테스트가 <b>커밋 시드</b>를
 *       별도 트랜잭션으로 정리할 때, 정리 전에 롤백 트랜잭션을 먼저 끝내야 한다(아래 설명).</li>
 * </ul>
 *
 * <p><b>rawSn 을 명시 지정할 때 IDENTITY 시퀀스를 함께 전진</b>시킨다. {@code RAW_SN} 은
 * {@code GENERATED BY DEFAULT AS IDENTITY} 라 명시 삽입이 허용되지만 시퀀스는 움직이지 않는다.
 * Testcontainers 컨테이너가 {@code withReuse(true)} 로 재사용되며 시퀀스는 실행마다 누적되므로,
 * 전진시키지 않으면 여러 번 실행한 뒤 자동 발급값이 하드코딩 시드값(예: 5001)에 도달해
 * PK 충돌로 간헐 실패한다. 전진은 <b>절대 후퇴시키지 않는다</b>({@code GREATEST(?, nextval)}).
 */
public final class RawVideoFixture {

    /** 시드 영상의 클립 ID 접두 — {@code UK_LS_DATA_RAW_VMS_CLIP} 충돌을 피하기 위한 격리 네임스페이스. */
    public static final String CLIP_ID_PREFIX = "FIXTURE-RAW-";

    /** 시드 부모 삭제가 FK 키공유 잠금에 걸릴 때의 1회 대기(ms) — 짧게 끊고 재시도한다. */
    private static final int DELETE_LOCK_TIMEOUT_MS = 1_000;
    /** 삭제 재시도 총 상한(회) — 비동기 후속 작업(@Async 비식별 등)의 커밋을 기다린다. */
    private static final int DELETE_MAX_ATTEMPTS = 15;
    /** PostgreSQL {@code lock_timeout} 초과 SQLSTATE. */
    private static final String SQLSTATE_LOCK_NOT_AVAILABLE = "55P03";

    private RawVideoFixture() {
    }

    // ------------------------------------------------------------------ seed

    /**
     * 지정한 {@code rawSn} 으로 부모 영상 1행을 <b>멱등</b> 시드한다(이미 있으면 그대로 둔다).
     *
     * @return 입력한 {@code rawSn} (체이닝 편의)
     */
    public static long seedRaw(JdbcTemplate jdbc, long rawSn) {
        jdbc.update("""
                INSERT INTO LS_DATA_RAW
                    (RAW_SN, VMS_CLIP_ID, VMS_CCTV_ID, PRVC_TYPE_CD, PRVC_YN, DE_IDENT_YN,
                     RAW_FILE_PATH_NM, DATA_STTS_CD, REG_DT)
                VALUES (?, ?, 'CCTV-001', 'ANONY', 'N', 'N', ?, 'PENDING', CURRENT_TIMESTAMP)
                ON CONFLICT DO NOTHING
                """, rawSn, CLIP_ID_PREFIX + rawSn, "/nas-storage/raw/fixture-" + rawSn + ".mp4");
        advanceIdentityBeyond(jdbc, rawSn);
        return rawSn;
    }

    /** 여러 부모 영상을 한 번에 멱등 시드한다. */
    public static void seedRaws(JdbcTemplate jdbc, long... rawSns) {
        for (long rawSn : rawSns) {
            seedRaw(jdbc, rawSn);
        }
    }

    /** {@link #seedRaw(JdbcTemplate, long)} 의 DataSource 편의 오버로드. */
    public static long seedRaw(DataSource dataSource, long rawSn) {
        return seedRaw(new JdbcTemplate(dataSource), rawSn);
    }

    /** {@link #seedRaws(JdbcTemplate, long...)} 의 DataSource 편의 오버로드. */
    public static void seedRaws(DataSource dataSource, long... rawSns) {
        seedRaws(new JdbcTemplate(dataSource), rawSns);
    }

    /**
     * IDENTITY 로 새 {@code RAW_SN} 을 발급받아 부모 영상 1행을 시드한다.
     * rawSn 값 자체에 의미가 없는 테스트({@code System.nanoTime()} 등 임의값 사용)에 쓴다.
     */
    public static long newRaw(JdbcTemplate jdbc) {
        Long rawSn = jdbc.queryForObject("""
                INSERT INTO LS_DATA_RAW
                    (VMS_CLIP_ID, VMS_CCTV_ID, PRVC_TYPE_CD, PRVC_YN, DE_IDENT_YN,
                     RAW_FILE_PATH_NM, DATA_STTS_CD, REG_DT)
                VALUES (?, 'CCTV-001', 'ANONY', 'N', 'N', ?, 'PENDING', CURRENT_TIMESTAMP)
                RETURNING RAW_SN
                """, Long.class,
                CLIP_ID_PREFIX + "GEN-" + System.nanoTime(),
                "/nas-storage/raw/fixture-gen.mp4");
        if (rawSn == null) {
            throw new IllegalStateException("LS_DATA_RAW 시드에 실패했습니다.");
        }
        return rawSn;
    }

    /** {@link #newRaw(JdbcTemplate)} 의 DataSource 편의 오버로드. */
    public static long newRaw(DataSource dataSource) {
        return newRaw(new JdbcTemplate(dataSource));
    }

    /**
     * ambient(롤백) 트랜잭션과 <b>독립적으로 커밋</b>되는 부모 영상 1건을 만든다.
     *
     * <p><b>언제 필요한가</b>: 프로덕션 코드가 {@code REQUIRES_NEW} 로 자식 행을 쓰는 경로
     * (예: {@code WorkLockService#lockRawExclusiveInNewTx} → {@code LS_AUTH_WORK_LOCK})는 <b>별도
     * 트랜잭션</b>이라 테스트의 미커밋 시드를 볼 수 없다. 부모가 미커밋이면 FK 검증이 실패한다.
     * 따라서 이런 테스트는 부모 영상만 실제 커밋해 두고, 자식(프레임·라벨·배정)은 ambient 롤백
     * 트랜잭션에 남겨 기존 격리를 유지한다.
     *
     * <p>정리는 {@code @AfterEach} 에서 {@link #endAmbientTransaction()} → {@link #deleteRaws} 순으로
     * 한다(ambient 가 살아 있으면 그 미커밋 자식이 부모 행에 키공유 잠금을 걸어 삭제가 대기한다).
     */
    public static long newRawCommitted(PlatformTransactionManager txManager, JdbcTemplate jdbc) {
        TransactionTemplate committed = new TransactionTemplate(txManager);
        committed.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
        Long rawSn = committed.execute(status -> newRaw(jdbc));
        if (rawSn == null) {
            throw new IllegalStateException("LS_DATA_RAW 커밋 시드에 실패했습니다.");
        }
        return rawSn;
    }

    // ---------------------------------------------------------------- delete

    /**
     * 시드한 부모 영상을 삭제한다 — FK {@code ON DELETE CASCADE} 로 자식 행도 함께 사라진다.
     *
     * <p>비동기 후속 작업(@Async 비식별 등)이 자식 행을 INSERT 한 채 아직 커밋하지 않았으면 그 트랜잭션이
     * 부모 행에 {@code FOR KEY SHARE} 를 들고 있어 삭제가 대기한다. 커넥션 기본 {@code lock_timeout}
     * (30s)으로 한 번에 기다리면 테스트가 통째로 멈추므로, 짧게 끊고 재시도해 최대
     * {@value #DELETE_MAX_ATTEMPTS}회 동안 커밋을 기다린다.
     */
    public static void deleteRaws(JdbcTemplate jdbc, long... rawSns) {
        if (rawSns.length == 0) {
            return;
        }
        StringBuilder in = new StringBuilder();
        Object[] args = new Object[rawSns.length];
        for (int i = 0; i < rawSns.length; i++) {
            in.append(i == 0 ? "?" : ",?");
            args[i] = rawSns[i];
        }
        deleteRawsWhere(jdbc, "RAW_SN IN (" + in + ")", args);
    }

    /** {@link #deleteRaws(JdbcTemplate, long...)} 의 DataSource 편의 오버로드. */
    public static void deleteRaws(DataSource dataSource, long... rawSns) {
        deleteRaws(new JdbcTemplate(dataSource), rawSns);
    }

    /**
     * 조건식으로 부모 영상을 삭제한다(예: {@code "VMS_CLIP_ID LIKE ?"}).
     * 잠금 대기 처리는 {@link #deleteRaws(JdbcTemplate, long...)} 와 동일하다.
     *
     * <p><b>이슈 댓글을 먼저 지운다 (V10)</b>: {@code LS_ISSUE_COMMENT} 의 FK 는 설계(ERD-023)대로
     * {@code ON DELETE RESTRICT} 라 <b>CASCADE 를 타고 내려오지 않는다</b>. 부모 이슈
     * ({@code LS_DATA_ISSUE})는 RAW CASCADE 로 사라지려 하는데 그 이슈에 댓글이 남아 있으면
     * <b>RAW 삭제 자체가 FK 위반으로 거부</b>된다. 운영 코드도 같은 이유로 선삭제 단계를 갖는다
     * ({@code AugmentDiscardPurgeTxService.DELETE_ORDER} ⑧).
     *
     * <p>⚠ FK 를 우회(제약 해제·DEFERRED)하지 않는다 — 클래스 javadoc 의 V146 원칙과 같다.
     * 삭제 <b>순서</b>를 지키는 것으로 해결한다.
     */
    public static void deleteRawsWhere(JdbcTemplate jdbc, String whereClause, Object... args) {
        String commentSql = """
                DELETE FROM LS_ISSUE_COMMENT
                 WHERE DATA_ISSUE_SN IN (
                        SELECT i.DATA_ISSUE_SN FROM LS_DATA_ISSUE i
                         WHERE i.DATA_RAW_SN IN (SELECT RAW_SN FROM LS_DATA_RAW WHERE %s))
                """.formatted(whereClause);
        String sql = "DELETE FROM LS_DATA_RAW WHERE " + whereClause;
        jdbc.execute((ConnectionCallback<Void>) con -> {
            try (Statement session = con.createStatement()) {
                // 커넥션 풀 init-sql(SET lock_timeout='30000')을 훼손하지 않도록 원래 값을 보관·복원한다.
                String previous = "30000";
                try (var rs = session.executeQuery("SHOW lock_timeout")) {
                    if (rs.next()) {
                        previous = rs.getString(1);
                    }
                }
                session.execute("SET lock_timeout = '" + DELETE_LOCK_TIMEOUT_MS + "'");
                try {
                    runWithRetry(con, commentSql, args); // RESTRICT FK — 반드시 RAW 보다 먼저(V10)
                    runWithRetry(con, sql, args);
                } finally {
                    session.execute("SET lock_timeout = '" + previous + "'");
                }
            }
            return null;
        });
    }

    private static void runWithRetry(java.sql.Connection con, String sql, Object[] args) throws SQLException {
        SQLException last = null;
        for (int attempt = 1; attempt <= DELETE_MAX_ATTEMPTS; attempt++) {
            try (PreparedStatement ps = con.prepareStatement(sql)) {
                for (int i = 0; i < args.length; i++) {
                    ps.setObject(i + 1, args[i]);
                }
                ps.executeUpdate();
                return;
            } catch (SQLException e) {
                if (!SQLSTATE_LOCK_NOT_AVAILABLE.equals(e.getSQLState())) {
                    throw e;
                }
                last = e; // 자식을 쥔 비동기 트랜잭션의 커밋을 기다린다.
            }
        }
        throw last;
    }

    // ------------------------------------------------------- ambient tx 종료

    /**
     * 클래스 레벨 {@code @Transactional} 테스트의 ambient(롤백) 트랜잭션을 즉시 롤백해 끝낸다.
     *
     * <p><b>왜 필요한가</b>: 커밋 시드(REQUIRES_NEW)로 부모 영상을 만들고 자식(프레임·마킹 등)은
     * ambient 롤백 트랜잭션에 넣는 테스트는, FK 신설 후 그 자식 INSERT 가 부모 행에
     * {@code FOR KEY SHARE} 를 걸어 <b>다른 트랜잭션의 부모 삭제를 막는다</b>. ambient 트랜잭션은
     * {@code @AfterEach} 가 끝난 뒤에야 롤백되므로, 정리 코드가 먼저 ambient 를 닫아야 한다.
     *
     * <p>Spring 의 {@code TransactionalTestExecutionListener} 는 종료 시
     * {@code transactionStatus == null || isCompleted()} 를 확인하고 건너뛰므로 이중 종료 문제는 없다.
     */
    public static void endAmbientTransaction() {
        if (TestTransaction.isActive()) {
            TestTransaction.flagForRollback();
            TestTransaction.end();
        }
    }

    // ----------------------------------------------------------------- 내부

    /**
     * IDENTITY 시퀀스를 {@code rawSn} 이후로 전진시킨다(후퇴 없음). 명시 rawSn 삽입 시에만 호출한다.
     * 시퀀스 조작은 트랜잭션 롤백 대상이 아니므로 롤백 테스트에서도 효과가 남는다(의도된 동작).
     */
    private static void advanceIdentityBeyond(JdbcTemplate jdbc, long rawSn) {
        jdbc.queryForObject("""
                SELECT setval(t.seq, GREATEST(?, nextval(t.seq)))
                  FROM (SELECT pg_get_serial_sequence('ls_data_raw', 'raw_sn') AS seq) t
                """, Long.class, rawSn);
    }
}
