package kr.co.cudo.authoring.version.service;

import kr.co.cudo.authoring.assignment.entity.LsTaskAssignment;
import kr.co.cudo.authoring.assignment.repository.LsTaskAssignmentRepository;
import kr.co.cudo.authoring.auth.service.WorkLockService;
import kr.co.cudo.authoring.batch.entity.LsDataLbl;
import kr.co.cudo.authoring.batch.entity.LsDataSrc;
import kr.co.cudo.authoring.batch.repository.LsDataLblRepository;
import kr.co.cudo.authoring.batch.repository.LsDataSrcRepository;
import kr.co.cudo.authoring.common.security.Channel;
import kr.co.cudo.authoring.common.security.Role;
import kr.co.cudo.authoring.common.security.TokenClaims;
import kr.co.cudo.authoring.label.entity.LsDataLblAttrVal;
import kr.co.cudo.authoring.label.entity.LsLabel;
import kr.co.cudo.authoring.label.entity.LsLabelAttr;
import kr.co.cudo.authoring.label.repository.LsDataLblAttrValRepository;
import kr.co.cudo.authoring.label.repository.LsLabelAttrRepository;
import kr.co.cudo.authoring.label.repository.LsLabelRepository;
import kr.co.cudo.authoring.support.PostgresTestContainer;
import kr.co.cudo.authoring.version.dto.DiffResponseDto;
import kr.co.cudo.authoring.version.dto.VersionItem;
import kr.co.cudo.authoring.version.entity.LsLabelVersion;
import kr.co.cudo.authoring.version.repository.LsLabelVersionRepository;
import kr.co.cudo.authoring.video.entity.LsDataRaw;
import kr.co.cudo.authoring.video.repository.VideoRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * 롤백 라벨 복원 통합 테스트 (Testcontainers PostgreSQL) — D-ISSUE-22 / D-ISSUE-23.
 *
 * <p>명시 PK 삽입({@code GENERATED BY DEFAULT AS IDENTITY})·IDENTITY 시퀀스 동기화·실 FK
 * ({@code LS_DATA_LBL_ATTR_VAL})·1차 캐시 정합은 <b>실 DB 동작</b>이라 mock 단위테스트로 갈음할 수 없다.
 * 따라서 본 클래스는 실제 컨테이너 DB 위에서 검증한다.
 */
@SpringBootTest
@ActiveProfiles("local")
@Sql(scripts = {"/db/test-data.sql", "/db/test-data-video.sql"},
        executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class VersionRollbackRestoreIT {

    @Autowired private VersionService versionService;
    @Autowired private LsLabelVersionRepository labelVersionRepository;
    @Autowired private VideoRepository rawRepository;
    @Autowired private LsDataSrcRepository srcRepository;
    @Autowired private LsDataLblRepository labelRepository;
    @Autowired private LsDataLblAttrValRepository attrValRepository;
    @Autowired private LsLabelRepository lsLabelRepository;
    @Autowired private LsLabelAttrRepository lsLabelAttrRepository;
    @Autowired private LsTaskAssignmentRepository assignmentRepository;
    @Autowired private WorkLockService workLockService;
    @Autowired private JdbcTemplate jdbcTemplate;

    /** 동시성 시나리오에서 <b>커밋 시점을 통제</b>하기 위한 외부 트랜잭션 템플릿(control 데이터소스). */
    private final TransactionTemplate txTemplate;

    VersionRollbackRestoreIT(
            @Qualifier("controlTransactionManager") PlatformTransactionManager controlTxManager) {
        this.txTemplate = new TransactionTemplate(controlTxManager);
    }

    /** 동시성 시나리오의 래치/Future 대기 상한(초). */
    private static final int AWAIT_SEC = 30;

    /**
     * 이 테스트가 만든 경합만 세는 잠금 대기 관측 쿼리 — 상세 근거는 {@link #awaitLockWait()} 주석 참조.
     *
     * <p>대기자 판정: ① 대기 락 자체가 대상 테이블 위에 있거나(relation/tuple 대기)
     * ② {@code transactionid} 대기이면서 대상 테이블의 {@code tuple} 락을 보유 중인 세션.
     * 파라미터 바인딩 없는 상수 SQL(사용자 입력 미개입).
     */
    private static final String SCOPED_LOCK_WAIT_SQL = """
            SELECT COUNT(*)
              FROM pg_locks w
              LEFT JOIN pg_class wc ON wc.oid = w.relation
             WHERE NOT w.granted
               AND w.pid <> pg_backend_pid()
               AND (lower(wc.relname) IN ('ls_label_version', 'ls_data_src')
                    OR EXISTS (SELECT 1
                                 FROM pg_locks t
                                 JOIN pg_class c ON c.oid = t.relation
                                WHERE t.pid = w.pid
                                  AND t.locktype = 'tuple'
                                  AND lower(c.relname) IN ('ls_label_version', 'ls_data_src')))
            """;

    private Long rawSn;
    private Long srcSn;
    private TokenClaims reviewer;
    /** 속성값 FK 테스트가 만든 라벨 마스터/속성 정의 — 다른 테스트 오염 방지를 위해 반드시 정리한다. */
    private Long createdAttrId;
    private Long createdLabelId;

    @BeforeEach
    void setUp() {
        LsDataRaw raw = rawRepository.save(LsDataRaw.createFromIngest(
                "CLIP-RBK-001", "CCTV-001", "EVT-A", "11680",
                LsDataRaw.PRVC_TYPE_ANONY, "/var/raw/clip.mp4", LocalDateTime.now(), 30));
        rawSn = raw.getRawSn();
        srcSn = srcRepository.save(LsDataSrc.create(rawSn, 0, "/raw/0.jpg", LocalDateTime.now()))
                .getSrcSn();
        assignmentRepository.save(LsTaskAssignment.createLabeler(rawSn, 100L, 1L));
        workLockService.releaseRaw(rawSn, "test", "TEST_SETUP");
        reviewer = new TokenClaims("1", Role.REVIEWER, Channel.INTERNAL, Instant.now().plusSeconds(60));
    }

    @AfterEach
    void tearDown() {
        // LS_LABEL_ATTR 이 남으면 LS_LABEL 을 전량 삭제하는 다른 테스트가 FK 위반으로 깨진다(테스트 오염).
        if (createdAttrId != null) {
            lsLabelAttrRepository.deleteById(createdAttrId);
            createdAttrId = null;
        }
        if (createdLabelId != null) {
            lsLabelRepository.deleteById(createdLabelId);
            createdLabelId = null;
        }
    }

    // ---------- 픽스처 ----------

    private LsDataLbl seedLabel(Long frameSn, String label, String pointsJson) {
        return labelRepository.save(
                LsDataLbl.createManual(frameSn, LsDataLbl.TYPE_BBOX, null, label, pointsJson, "100"));
    }

    /** 지정 payload 를 그대로 담은 active 버전 행을 적재하고 해시를 반환(롤백 입력용). */
    private String seedVersion(String hash, String payload) {
        labelVersionRepository.save(LsLabelVersion.create(
                rawSn, srcSn, hash, payload, 1, LsLabelVersion.SAVE_REASON_APPROVED, "1"));
        return hash;
    }

    /** commitApproved 가 만든 현재 active 스냅샷 해시. */
    private String activeSnapshotHash() {
        return labelVersionRepository.findByDataSrcSnOrderByRegDtDesc(srcSn).stream()
                .filter(v -> LsLabelVersion.ACTIVE_YES.equals(v.getActiveYn()))
                .findFirst().orElseThrow().getVersionHash();
    }

    /** 스냅샷 item 1건 JSON — 옛 LBL_SN(id) 및 AI 메타/트랙 포함(필드는 null 허용). */
    private static String item(Long id, String label, String points, String autoLblYn,
                               String confScore, String trackId, String lblSrcCd) {
        return "{\"id\":" + id + ",\"lblTypeCd\":\"BBOX\",\"label\":\"" + label
                + "\",\"labelId\":null,\"points\":" + points
                + ",\"autoLblYn\":" + (autoLblYn == null ? "null" : "\"" + autoLblYn + "\"")
                + ",\"confScore\":" + (confScore == null ? "null" : confScore)
                + ",\"trackId\":" + (trackId == null ? "null" : "\"" + trackId + "\"")
                + ",\"lblSrcCd\":" + (lblSrcCd == null ? "null" : "\"" + lblSrcCd + "\"") + "}";
    }

    private String payload(String... items) {
        return "{\"srcSn\":" + srcSn + ",\"frameNo\":0,\"items\":[" + String.join(",", items) + "]}";
    }

    // ---------- D-22: LBL_SN 보존 ----------

    @Test
    @DisplayName("롤백_복원시_스냅샷의_LBL_SN_이_그대로_유지된다")
    void rollbackPreservesSnapshotLblSn() {
        // given — 라벨 2건으로 승인 스냅샷 v1 생성 후, 라벨을 전혀 다른 세트로 교체.
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long id2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        labelRepository.deleteAllByIdInBatch(List.of(id1, id2));
        seedLabel(srcSn, "bike", "[[7.0,7.0],[8.0,8.0]]");

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 옛 LBL_SN 이 그대로 복원(재발급 금지).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn)
                .containsExactlyInAnyOrder(id1, id2);
        assertThat(after).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("person", "car");
    }

    @Test
    @DisplayName("좌표가_동일한_롤백_후_diff_가_변경없음으로_판정")
    void diffAfterRoundTripReportsNoChange() {
        // given — v1(person) → 수정(car) → v2 → v1 로 롤백 → 재승인.
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        labelRepository.deleteAllByIdInBatch(List.of(id1));
        seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        versionService.commitApproved(rawSn, reviewer);

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);
        versionService.commitApproved(rawSn, reviewer);

        // then — 롤백 후 상태는 v1 과 라벨 식별자·좌표가 동일하므로 diff 는 변경 0건.
        DiffResponseDto diff = versionService.diff(v1Hash, activeSnapshotHash(), reviewer);
        assertThat(diff.labels()).isEmpty();
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(id1);
    }

    // ---------- S1: PK 충돌 폴백 ----------

    @Test
    @DisplayName("복원하려는_LBL_SN_이_이미_존재하면_신규발급으로_폴백하고_전체가_실패하지_않는다")
    void conflictingLblSnFallsBackToNewId() {
        // given — 다른 프레임(other)이 LBL_SN 을 점유한 상태의 스냅샷.
        Long otherSrcSn = srcRepository.save(LsDataSrc.create(rawSn, 1, "/raw/1.jpg", LocalDateTime.now()))
                .getSrcSn();
        Long occupiedId = seedLabel(otherSrcSn, "occupied", "[[0.0,0.0],[1.0,1.0]]").getLblSn();
        String hash = seedVersion("aa11bb22cc33dd44ee55ff66aa77bb88cc99dd00",
                payload(item(occupiedId, "person", "[[10.0,10.0],[50.0,50.0]]", null, null, null, null)));

        // when — 점유된 PK 로 복원 시도.
        assertThatCode(() -> versionService.rollback(hash, srcSn, reviewer)).doesNotThrowAnyException();

        // then — 대상 프레임은 새 PK 로 복원되고, 점유 라벨(타 프레임)은 그대로 남는다.
        List<LsDataLbl> restored = labelRepository.findBySrcSn(srcSn);
        assertThat(restored).hasSize(1);
        assertThat(restored.get(0).getLblSn()).isNotEqualTo(occupiedId);
        assertThat(restored.get(0).getLabelNm()).isEqualTo("person");
        assertThat(labelRepository.findById(occupiedId)).isPresent()
                .get().extracting(LsDataLbl::getSrcSn).isEqualTo(otherSrcSn);
    }

    // ---------- S2: IDENTITY 시퀀스 동기화 ----------

    @Test
    @DisplayName("명시_PK_복원_후에도_다음_라벨_저장이_PK_충돌없이_성공한다")
    void identitySequenceStaysAheadAfterExplicitIdRestore() {
        // given — 시퀀스가 다음에 발급할 값(maxId + 1)을 스냅샷 LBL_SN 으로 사용한다.
        //   시퀀스를 동기화하지 않으면 이후 첫 라벨 저장이 이 PK 를 재발급해 23505(중복키)로 전면 실패한다.
        Long maxId = seedLabel(srcSn, "seed", "[[0.0,0.0],[1.0,1.0]]").getLblSn();
        Long nextIdentity = maxId + 1;
        String hash = seedVersion("bb11cc22dd33ee44ff55aa66bb77cc88dd99ee00",
                payload(item(nextIdentity, "person", "[[10.0,10.0],[50.0,50.0]]", null, null, null, null)));

        versionService.rollback(hash, srcSn, reviewer);
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(nextIdentity);

        // when / then — 복원 이후 신규 라벨 저장이 PK 충돌 없이 성공해야 한다.
        assertThatCode(() -> {
            LsDataLbl saved = seedLabel(srcSn, "after", "[[2.0,2.0],[3.0,3.0]]");
            assertThat(saved.getLblSn()).isGreaterThan(nextIdentity);
        }).doesNotThrowAnyException();
    }

    // ---------- S5: 같은 트랜잭션 재조회 정합 ----------

    @Test
    @DisplayName("복원_직후_같은_트랜잭션에서_재조회하면_새_라벨이_보인다")
    @Transactional(transactionManager = "controlTransactionManager")
    void restoredLabelsVisibleInSameTransaction() {
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long id2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();
        labelRepository.deleteAllByIdInBatch(List.of(id1, id2));
        assertThat(labelRepository.findBySrcSn(srcSn)).isEmpty();

        versionService.rollback(v1Hash, srcSn, reviewer);

        // 네이티브 삽입은 영속성 컨텍스트를 우회하므로 같은 트랜잭션 재조회가 0건이 되면 안 된다.
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn).containsExactlyInAnyOrder(id1, id2);
    }

    /**
     * DEV_FIX-B(M4) — bulk delete(JPQL) 는 1차 캐시를 evict 하지 않는다. 복원 대상 {@code LBL_SN} 이
     * managed 로 남아 있으면 후속 조회가 <b>복원 전 내용</b>을 돌려준다(행 수만 맞음).
     *
     * <p>구 테스트({@link #restoredLabelsVisibleInSameTransaction})는 {@code LBL_SN} 만 단언하고
     * 픽스처가 "복원 전 == 복원 후" 라 stale 을 원리적으로 검출할 수 없었다. 여기서는 <b>복원 전 작업본을
     * 드리프트</b>시켜(라벨명·좌표 상이) 내용까지 단언한다.
     */
    @Test
    @DisplayName("복원_후_재조회가_복원_전_내용을_돌려주지_않는다")
    @Transactional(transactionManager = "controlTransactionManager")
    void reReadAfterRestoreDoesNotReturnStalePersistenceContextState() {
        // given — v1 스냅샷(person/car) 생성 후, 같은 LBL_SN 을 유지한 채 내용만 드리프트시킨다.
        LsDataLbl l1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]");
        LsDataLbl l2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        Long id1 = l1.getLblSn();
        Long id2 = l2.getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        l1.updateUserContent(LsDataLbl.TYPE_BBOX, null, "drifted-person", "[[99.0,99.0],[100.0,100.0]]");
        l2.updateUserContent(LsDataLbl.TYPE_BBOX, null, "drifted-car", "[[98.0,98.0],[100.0,100.0]]");
        labelRepository.flush();
        // 드리프트된 인스턴스가 1차 캐시에 managed 로 남아 있는 상태(= stale 재현 조건).
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("drifted-person", "drifted-car");

        // when — v1 로 롤백(같은 LBL_SN 으로 원래 내용 복원).
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 같은 트랜잭션 재조회가 복원 <b>후</b> 내용을 돌려줘야 한다(행 수·식별자만이 아니라 내용까지).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn).containsExactlyInAnyOrder(id1, id2);
        assertThat(after).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("person", "car");
        assertThat(after).extracting(LsDataLbl::getPointCn)
                .containsExactlyInAnyOrder("[[10.0,10.0],[50.0,50.0]]", "[[1.0,1.0],[2.0,2.0]]");
    }

    /**
     * DEV_FIX-B(M2) — SKELETON 왕복 롤백이 {@code POINT_CN} 의 가시성 v 표현을 변질시키지 않는지
     * <b>실 DB 값</b>으로 확인한다(스냅샷은 v 를 {@code 2.0} 으로, DB 는 {@code 2} 로 쓴다).
     */
    @Test
    @DisplayName("SKELETON_왕복_롤백_후_POINT_CN_의_v_가_변질되지_않는다")
    void skeletonRoundTripKeepsPointCnRepresentation() {
        // given — 17-keypoint SKELETON 라벨 1건으로 v1 스냅샷 생성.
        String keypoints = skeletonPoints();
        Long id = labelRepository.save(LsDataLbl.createManual(
                srcSn, LsDataLbl.TYPE_SKELETON, null, "person", keypoints, "100")).getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        // 작업본을 드리프트시켜 실제 교체 경로를 타게 한다.
        seedLabel(srcSn, "drift", "[[9.0,9.0],[9.5,9.5]]");

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 복원된 좌표는 DB 정규형 그대로(v 가 2.0 으로 변질되지 않음).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLblSn()).isEqualTo(id);
        assertThat(after.get(0).getPointCn()).isEqualTo(keypoints);
        assertThat(after.get(0).getPointCn()).doesNotContain("2.0]");
    }

    /** COCO-17 키포인트 좌표(DB 정규형 — x/y 는 double, v 는 정수). */
    private static String skeletonPoints() {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < 17; i++) {
            if (i > 0) {
                sb.append(',');
            }
            sb.append('[').append(10.0 + i).append(',').append(20.0 + i).append(",2]");
        }
        return sb.append(']').toString();
    }

    // ---------- D-23: 속성값 FK / AI 메타 / TRCK_ID ----------

    @Test
    @DisplayName("속성값을_보유한_프레임_롤백시_FK_위반_500_이_발생하지_않는다")
    void rollbackWithAttributeValuesDoesNotViolateFk() {
        // given — 라벨 1건 + 그 라벨의 속성값(LS_DATA_LBL_ATTR_VAL — LS_DATA_LBL 에 실 FK).
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        createdLabelId = lsLabelRepository.save(
                LsLabel.create("롤백복원IT라벨", "#FF0000", LsDataLbl.TYPE_BBOX, 1, "1")).getLabelId();
        createdAttrId = lsLabelAttrRepository.save(LsLabelAttr.create(
                createdLabelId, "색상", LsLabelAttr.INPUT_TEXT, null, null, "Y", 1, "1")).getAttrId();
        attrValRepository.save(LsDataLblAttrVal.create(id1, createdAttrId, "red"));

        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();
        // D-ISSUE-24 — 작업본이 스냅샷과 완전히 동일하면 롤백은 진짜 no-op(라벨 미교체)이 되어 FK 경로를
        //   타지 않는다. 실제 교체 경로를 검증하려면 작업본을 드리프트시켜 둔다.
        seedLabel(srcSn, "drift", "[[9.0,9.0],[9.5,9.5]]");

        // when / then — 속성값 선정리 없이 부모를 지우면 FK 위반(500)이 된다.
        assertThatCode(() -> versionService.rollback(v1Hash, srcSn, reviewer))
                .doesNotThrowAnyException();
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(id1);
        // ★ 알려진 한계(적대 #7 — 스코프 밖, 별건): 스냅샷 payload 에 라벨 <b>속성값</b> 필드가 없어
        //   어떤 버전으로 롤백해도 LS_DATA_LBL_ATTR_VAL 은 복원할 수 없다(FK 위반 방지를 위해 삭제만 한다).
        //   따라서 아래 isEmpty() 는 "정상 동작"이 아니라 <b>복원 불가라는 현 한계를 고정</b>한 단언이다.
        //   복원까지 하려면 스냅샷 스키마 확장(속성값 포함)이 선행돼야 하며 본 수정 범위가 아니다.
        assertThat(attrValRepository.findByLblSnIn(List.of(id1))).isEmpty();
    }

    @Test
    @DisplayName("롤백_후_AI메타와_TRCK_ID_가_고아가_되지_않고_복원된다")
    void rollbackRestoresAiMetaAndTrackIdWithoutOrphans() {
        // given — 라벨 A(스냅샷 대상) / 라벨 B(스냅샷 미포함) 각각 AI 메타 보유.
        Long idA = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long idB = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        applyAiMeta(idA, LsDataLbl.SRC_YOLO, new BigDecimal("0.50000"));
        applyAiMeta(idB, LsDataLbl.SRC_SAM2, new BigDecimal("0.60000"));
        String hash = seedVersion("cc11dd22ee33ff44aa55bb66cc77dd88ee99ff00",
                payload(item(idA, "person", "[[10.0,10.0],[50.0,50.0]]",
                        LsDataLbl.AUTO_YES, "0.90000", "T-1", LsDataLbl.SRC_YOLO)));

        // when
        versionService.rollback(hash, srcSn, reviewer);

        // then — TRCK_ID 복원(구 구현은 createManual 이라 항상 NULL).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLblSn()).isEqualTo(idA);
        assertThat(after.get(0).getTrackId()).isEqualTo("T-1");

        // AI 메타는 스냅샷 값으로 복원 — V6 이후 라벨 행의 컬럼이다.
        assertThat(after.get(0).getLblSrcCd()).isEqualTo(LsDataLbl.SRC_YOLO);
        assertThat(after.get(0).getAutoLblYn()).isEqualTo(LsDataLbl.AUTO_YES);
        assertThat(after.get(0).getConfScore()).isEqualByComparingTo("0.90000");

        // 스냅샷에 없어 삭제된 라벨 B 는 행째 사라진다(생산이력만 고아로 남던 구조가 없어졌다).
        assertThat(labelRepository.findById(idB)).isEmpty();
    }

    // ---------- D-ISSUE-21(3차): ACTIVE 단일 불변식 — 동시 롤백/승인 write skew ----------

    /**
     * 3차 전수검증 D-ISSUE-21 회귀 가드 — <b>동시 롤백 2건이 ACTIVE 버전을 2건 남기던 write skew</b>.
     *
     * <h3>실패 모드</h3>
     * 구 구현은 "이 프레임의 현재 ACTIVE 버전 목록"을 <b>프레임 행 락(직렬화 앵커)을 잡기 전에</b>
     * 한 번만 조회했다. PostgreSQL READ COMMITTED 에서 {@code SELECT ... WHERE ACTIVE_YN='Y' FOR UPDATE}
     * 는 잠금을 기다린 뒤 <b>갱신된 행이 술어를 만족하지 않으면 결과에서 탈락</b>시킬 뿐, 그 사이 다른
     * 트랜잭션이 <b>새로 ACTIVE 로 만든 행</b>은 최초 스냅샷에 없어 보이지 않는다. 결과:
     * <pre>
     *   T1: active=[v3] 잠금 → v3 비활성 + v1 활성 → commit
     *   T2: active=[v3] 로 대기 → 해제 후 결과 []  (v1 이 ACTIVE 가 된 사실을 못 봄)
     *       → v2 활성, 비활성화할 대상 없음  ⇒ ACTIVE = {v1, v2} 2건
     * </pre>
     *
     * <h3>재현 결정성</h3>
     * 타이밍에 맡기지 않는다. T1 을 외부 트랜잭션으로 감싸 <b>롤백 본문 종료 후 커밋 직전</b>에 붙잡아 두고,
     * T2 가 실제로 <b>행 잠금 대기</b>(pg_locks NOT granted)에 들어간 것을 관측한 뒤에야 T1 을 커밋시킨다.
     */
    @Test
    @DisplayName("동시_두_롤백_요청_후_ACTIVE_버전이_정확히_1건만_남는다")
    void concurrentRollbacksLeaveExactlyOneActiveVersion() throws Exception {
        // given — 승인 스냅샷 3벌(v1 person → v2 car → v3 bike). 현재 active 는 v3.
        String v1 = approveWith("person", "[[10.0,10.0],[50.0,50.0]]");
        String v2 = approveWith("car", "[[1.0,1.0],[2.0,2.0]]");
        approveWith("bike", "[[7.0,7.0],[8.0,8.0]]");
        assertThat(activeVersionCount()).isEqualTo(1);

        // when — 서로 다른 유효 스냅샷으로 동시 롤백
        runWithFirstHeldUntilSecondBlocks(
                () -> versionService.rollback(v1, srcSn, reviewer),
                () -> versionService.rollback(v2, srcSn, reviewer));

        // then — ACTIVE 는 정확히 1건 (구 구현: 2건)
        assertThat(activeVersionCount())
                .as("동시 롤백 후에도 프레임당 ACTIVE 버전은 1건이어야 한다")
                .isEqualTo(1);

        // and — 이력은 <b>정확히 2건</b>: 두 롤백이 앵커로 직렬화돼 각자 실질 교체 경로를 1회씩 수행한다
        //   (T1: bike→person / T2: person→car). 중복 기록(같은 롤백이 2행)·누락(패자가 조용히 no-op)
        //   회귀를 이 단언이 잡는다 — ACTIVE 건수만 보면 둘 다 통과해버린다.
        assertThat(labelHistoryCount())
                .as("직렬화된 두 롤백은 각각 1건씩, 총 2건의 롤백 이력을 남겨야 한다")
                .isEqualTo(2);
    }

    @Test
    @DisplayName("롤백_후_GET_버전목록_조회시_isCurrent가_정확히_1건만_true다")
    void versionListExposesExactlyOneCurrentAfterConcurrentRollbacks() throws Exception {
        // given
        String v1 = approveWith("person", "[[10.0,10.0],[50.0,50.0]]");
        String v2 = approveWith("car", "[[1.0,1.0],[2.0,2.0]]");
        approveWith("bike", "[[7.0,7.0],[8.0,8.0]]");

        // when
        runWithFirstHeldUntilSecondBlocks(
                () -> versionService.rollback(v1, srcSn, reviewer),
                () -> versionService.rollback(v2, srcSn, reviewer));

        // then — API 응답(GET /v1/frames/{srcSn}/versions) 축에서도 현재 버전은 1건뿐이어야 한다.
        List<VersionItem> versions = versionService.listVersions(srcSn, reviewer);
        assertThat(versions).filteredOn(VersionItem::isCurrent)
                .as("버전 목록의 isCurrent 는 정확히 1건이어야 한다")
                .hasSize(1);
        assertThat(labelHistoryCount())
                .as("직렬화된 두 롤백은 각각 1건씩, 총 2건의 롤백 이력을 남겨야 한다")
                .isEqualTo(2);
    }

    @Test
    @DisplayName("동시_검수승인과_롤백_요청_후에도_ACTIVE_버전이_1건만_남는다")
    void concurrentApproveAndRollbackLeaveExactlyOneActiveVersion() throws Exception {
        // given — v1(person) → v2(car, 현재 active) → 작업본만 bike 로 드리프트(미승인).
        String v1 = approveWith("person", "[[10.0,10.0],[50.0,50.0]]");
        approveWith("car", "[[1.0,1.0],[2.0,2.0]]");
        replaceLabels("bike", "[[7.0,7.0],[8.0,8.0]]");

        // when — 롤백(v1 재활성)과 검수 승인 스냅샷(bike 신규 버전)이 겹친다.
        runWithFirstHeldUntilSecondBlocks(
                () -> versionService.rollback(v1, srcSn, reviewer),
                () -> versionService.commitApproved(rawSn, reviewer));

        // then — 승인 경로도 같은 앵커로 직렬화되어 ACTIVE 는 1건 (구 구현: v1 + 신규 = 2건)
        assertThat(activeVersionCount())
                .as("동시 검수승인·롤백 후에도 프레임당 ACTIVE 버전은 1건이어야 한다")
                .isEqualTo(1);

        // and — 롤백 1건만 이력을 남긴다(승인 스냅샷은 라벨을 바꾸지 않아 이력 축이 없다).
        assertThat(labelHistoryCount())
                .as("경합해도 롤백 이력은 실제 수행된 1건만 남아야 한다")
                .isEqualTo(1);
    }

    /**
     * 항목 4 보강(2026-08-04) — 위 시나리오의 <b>역순</b>. 검수 승인이 먼저 프레임 행 앵커를 선점하고
     * 롤백이 대기하는 방향도 대칭적으로 안전한지 고정한다.
     *
     * <p>두 방향을 모두 고정해야 하는 이유: 앵커 이후 재조회는 <b>양쪽 경로에 각각</b> 배선돼 있어
     * (rollback / snapshotFrameOnApprove) 한쪽만 회귀해도 다른 방향 테스트는 계속 통과한다.
     * 실제로 구 구현에서는 <b>승인 쪽 재조회가 없어</b> 승인이 롤백의 재활성 행을 못 보고 ACTIVE 를
     * 2건 남겼는데, 이 방향에서는 승인이 <b>먼저</b> 커밋하므로 롤백 쪽 재조회 누락을 잡는다.
     */
    @Test
    @DisplayName("동시_검수승인_선점_후_롤백_요청_후에도_ACTIVE_버전이_1건만_남는다")
    void approveFirstThenBlockedRollbackLeavesExactlyOneActiveVersion() throws Exception {
        // given — v1(person) → v2(car, 현재 active) → 작업본만 bike 로 드리프트(미승인).
        String v1 = approveWith("person", "[[10.0,10.0],[50.0,50.0]]");
        approveWith("car", "[[1.0,1.0],[2.0,2.0]]");
        replaceLabels("bike", "[[7.0,7.0],[8.0,8.0]]");

        // when — 승인 스냅샷(bike 신규 버전)이 앵커를 선점하고, 롤백(v1)이 그 뒤에서 대기한다.
        runWithFirstHeldUntilSecondBlocks(
                () -> versionService.commitApproved(rawSn, reviewer),
                () -> versionService.rollback(v1, srcSn, reviewer));

        // then — 나중에 커밋한 롤백이 승인 스냅샷을 보고 비활성화하므로 ACTIVE 는 1건이고,
        //        최종 정본은 롤백 대상(v1)이어야 한다(승인 신규 버전이 살아남으면 롤백이 무효화된 것).
        assertThat(activeVersionCount())
                .as("승인 선점 → 롤백 대기 방향에서도 ACTIVE 버전은 1건이어야 한다")
                .isEqualTo(1);
        assertThat(activeSnapshotHash())
                .as("나중에 직렬화된 롤백 대상(v1)이 최종 정본이어야 한다")
                .isEqualTo(v1);
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLabelNm)
                .as("라벨 본문도 롤백 대상 스냅샷으로 복원돼야 한다")
                .containsExactly("person");
        assertThat(labelHistoryCount())
                .as("경합해도 롤백 이력은 실제 수행된 1건만 남아야 한다")
                .isEqualTo(1);
    }

    @Test
    @DisplayName("단일_롤백_요청은_기존과_동일하게_정상_동작한다")
    void singleRollbackRestoresLabelsAndKeepsSingleActive() {
        // given — v1(person) → v2(car, 현재 active)
        String v1 = approveWith("person", "[[10.0,10.0],[50.0,50.0]]");
        approveWith("car", "[[1.0,1.0],[2.0,2.0]]");

        // when
        versionService.rollback(v1, srcSn, reviewer);

        // then — 대상 스냅샷이 재활성(적층 없음) + 라벨 본문 복원
        assertThat(activeVersionCount()).isEqualTo(1);
        assertThat(activeSnapshotHash()).isEqualTo(v1);
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLabelNm)
                .containsExactly("person");
        Long restoredId = labelRepository.findBySrcSn(srcSn).get(0).getLblSn();

        // and — 멱등 롤백(이미 active + 라벨 동일)은 no-op: 라벨 재작성(LBL_SN 변경) 없음
        versionService.rollback(v1, srcSn, reviewer);
        assertThat(activeVersionCount()).isEqualTo(1);
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(restoredId);
    }

    // ---------- 동시성 픽스처 ----------

    /** 프레임 작업본을 라벨 1건으로 교체한다(기존 라벨 전량 삭제 후 신규 1건). */
    private void replaceLabels(String label, String pointsJson) {
        List<Long> existing = labelRepository.findBySrcSn(srcSn).stream()
                .map(LsDataLbl::getLblSn).toList();
        if (!existing.isEmpty()) {
            labelRepository.deleteAllByIdInBatch(existing);
        }
        seedLabel(srcSn, label, pointsJson);
    }

    /** 작업본을 지정 라벨로 교체하고 검수 승인 스냅샷을 만든 뒤 그 해시를 돌려준다. */
    private String approveWith(String label, String pointsJson) {
        replaceLabels(label, pointsJson);
        versionService.commitApproved(rawSn, reviewer);
        return activeSnapshotHash();
    }

    /** 이 프레임의 ACTIVE 버전 행 수 — DB 직접 확인(영속성 컨텍스트 경유 금지). */
    private int activeVersionCount() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM LS_LABEL_VERSION WHERE DATA_SRC_SN = ? AND ACTVTN_YN = 'Y'",
                Integer.class, srcSn);
        return count == null ? 0 : count;
    }

    /**
     * 이 프레임의 라벨 이력({@code LS_DATA_LBL_HSTRY}) 행 수 — DB 직접 확인.
     *
     * <p>롤백은 실질 교체 경로에서만 이력 1행을 남긴다({@code recordRollbackEvent}). 멱등 no-op 은
     * 이력을 남기지 않고, 승인 스냅샷({@code commitApproved})은 라벨을 바꾸지 않으므로 이 축에 기록이 없다.
     */
    private int labelHistoryCount() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM LS_DATA_LBL_HSTRY WHERE SRC_SN = ?", Integer.class, srcSn);
        return count == null ? 0 : count;
    }

    /**
     * {@code first} 를 외부 트랜잭션 안에서 실행해 <b>커밋 직전에 붙잡아 두고</b>, 그 사이 {@code second} 를
     * 다른 스레드에서 시작시켜 <b>행 잠금 대기가 실제로 관측될 때까지</b> 기다린 뒤 {@code first} 를 커밋한다.
     *
     * <p>슬립 기반이 아니라 {@code pg_locks} 관측으로 동기화하므로 재현이 결정적이다. 잠금 대기가 관측되지
     * 않으면 경합이 성립하지 않은 것이므로 <b>테스트를 실패</b>시킨다(조용한 위양성 통과 금지).
     *
     * <p><b>2-way 만 다루는 이유(3-way 미검증 근거, 2026-08-04):</b> 애플리케이션 커넥션 풀이
     * {@code maximum-pool-size: 2}(의도적 — 커넥션 기아 결함을 드러내려는 설정이라 늘리지 않는다)라
     * 세 번째 동시 요청은 <b>행 잠금이 아니라 커넥션 획득</b>에서 막힌다. 그 상태의 테스트는 "3-way 경합에서도
     * ACTIVE 가 1건" 을 검증하는 것처럼 보이지만 실제로는 순차 실행을 확인할 뿐이라 <b>거짓 안전감</b>만 준다.
     * 직렬화 앵커가 프레임 <b>단일 행</b>이라 N 개 경합도 그 행에서 한 줄로 세워지므로(2-way 와 동일 메커니즘)
     * 별도 케이스의 회귀 검출력도 없다.
     */
    private void runWithFirstHeldUntilSecondBlocks(Runnable first, Runnable second) throws Exception {
        CountDownLatch firstBodyDone = new CountDownLatch(1);
        CountDownLatch releaseFirst = new CountDownLatch(1);
        ExecutorService pool = Executors.newFixedThreadPool(2);
        try {
            Future<?> t1 = pool.submit(() -> txTemplate.execute(status -> {
                first.run();
                firstBodyDone.countDown();
                awaitOrThrow(releaseFirst);
                return null; // 반환 후 커밋 — 그때까지 모든 행 잠금을 보유한다
            }));
            assertThat(firstBodyDone.await(AWAIT_SEC, TimeUnit.SECONDS))
                    .as("첫 요청의 롤백 본문이 완료돼야 한다").isTrue();

            Future<?> t2 = pool.submit(second);
            assertThat(awaitLockWait())
                    .as("두 번째 요청이 행 잠금 대기에 들어가야 경합이 성립한다").isTrue();

            releaseFirst.countDown();
            t1.get(AWAIT_SEC, TimeUnit.SECONDS);
            t2.get(AWAIT_SEC, TimeUnit.SECONDS);
        } finally {
            releaseFirst.countDown();
            pool.shutdownNow();
        }
    }

    /**
     * <b>이 테스트가 만든 경합</b>으로 다른 세션이 행 잠금을 기다리는 상태가 될 때까지 폴링한다(관측되면 true).
     *
     * <p>애플리케이션 커넥션 풀({@code maximum-pool-size: 2} — 커넥션 기아 결함을 드러내려는 <b>의도적</b>
     * 설정이라 늘리지 않는다)은 이 시점에 T1·T2 가 모두 점유하고 있어 {@code jdbcTemplate} 로는 관측
     * 자체가 불가능하다. 관측 전용 커넥션을 컨테이너에 직접 연다(풀 비의존).
     *
     * <h3>관측 스코프 (2026-08-04 보강 — flaky 차단)</h3>
     * 구 구현은 {@code SELECT COUNT(*) FROM pg_locks WHERE NOT granted} 로 <b>DB 전역</b>의 대기 락을
     * 셌다. 컨테이너는 모든 {@code @SpringBootTest} 컨텍스트가 공유하므로(싱글톤 + {@code withReuse}),
     * 무관한 세션(다른 컨텍스트의 배치/Quartz 등)의 잠금 대기가 하나라도 섞이면 <b>경합이 성립하기 전에</b>
     * T1 을 커밋시켜 "결정적 동기화" 설계가 조용히 무력화된다(그 경우 write skew 회귀를 놓친다).
     *
     * <p>따라서 <b>이 경로가 잠그는 두 테이블</b>({@code LS_LABEL_VERSION} 선취/재조회 · {@code LS_DATA_SRC}
     * 앵커)로 좁힌다. PostgreSQL 에서 행 잠금 대기는 {@code pg_locks} 에 <b>{@code locktype='transactionid'}
     * (relation NULL)</b> 로 나타나므로 relation 컬럼만으로는 좁힐 수 없다 — 대기자는 그와 동시에 대상
     * 행에 대한 {@code locktype='tuple'} 락을 <b>보유</b>하므로(heap_lock_tuple 의 tuple lock → xact wait
     * 순서), 그 tuple 락의 relation 으로 대기자를 식별한다. 자기 자신(관측 커넥션)은 제외한다.
     *
     * <p>행 단위(srcSn)까지 좁히는 것은 {@code page/tuple} ↔ {@code ctid} 대응이 필요한데 {@code ctid} 는
     * UPDATE 마다 바뀌어(롤백 경로는 {@code LBL_VER} bump 로 실제 갱신된다) 오히려 불안정하므로,
     * relation 단위까지만 좁힌다.
     */
    private boolean awaitLockWait() throws Exception {
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(AWAIT_SEC);
        try (Connection observer = DriverManager.getConnection(
                PostgresTestContainer.INSTANCE.getJdbcUrl(),
                PostgresTestContainer.INSTANCE.getUsername(),
                PostgresTestContainer.INSTANCE.getPassword());
             PreparedStatement ps = observer.prepareStatement(SCOPED_LOCK_WAIT_SQL)) {
            while (System.nanoTime() < deadline) {
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        return true;
                    }
                }
                Thread.sleep(20);
            }
        }
        return false;
    }

    private static void awaitOrThrow(CountDownLatch latch) {
        try {
            if (!latch.await(AWAIT_SEC, TimeUnit.SECONDS)) {
                throw new IllegalStateException("래치 대기 시간 초과");
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(e);
        }
    }

    @Test
    @DisplayName("AI메타_키가_없는_옛_스냅샷도_롤백이_성공한다")
    void legacySnapshotWithoutAiMetaKeysStillRolledBack() {
        // given — id/autoLblYn/confScore/trackId/lblSrcCd 키가 전혀 없는 옛 스냅샷 형식.
        seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        String legacyPayload = "{\"srcSn\":" + srcSn + ",\"frameNo\":0,\"items\":["
                + "{\"lblTypeCd\":\"BBOX\",\"label\":\"person\",\"points\":[[10.0,10.0],[50.0,50.0]]}]}";
        String hash = seedVersion("dd11ee22ff33aa44bb55cc66dd77ee88ff99aa00", legacyPayload);

        // when / then — 신규 PK 발급으로 복원되고 예외가 없어야 한다.
        assertThatCode(() -> versionService.rollback(hash, srcSn, reviewer))
                .doesNotThrowAnyException();
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLabelNm()).isEqualTo("person");
        assertThat(after.get(0).getTrackId()).isNull();
        // 스냅샷에 출처가 없고 승계할 옛 값도 없으면 생산이력은 null 이다(날조하지 않는다).
        assertThat(after.get(0).getLblSrcCd()).isNull();
    }

    /** V6 — 생산이력을 라벨 행에 직접 부여한다(구 LS_DATA_LBL_AI_INFO 시드 대체). */
    private void applyAiMeta(Long lblSn, String lblSrcCd, java.math.BigDecimal score) {
        LsDataLbl lbl = labelRepository.findById(lblSn).orElseThrow();
        lbl.applyAiSource(lblSrcCd, score);
        labelRepository.saveAndFlush(lbl);
    }
}
