package kr.co.cudo.authoring.version.service;

import kr.co.cudo.authoring.assignment.entity.LsTaskAssignment;
import kr.co.cudo.authoring.assignment.repository.LsTaskAssignmentRepository;
import kr.co.cudo.authoring.auth.service.WorkLockService;
import kr.co.cudo.authoring.batch.entity.LsDataLbl;
import kr.co.cudo.authoring.batch.entity.LsDataLblAiInfo;
import kr.co.cudo.authoring.batch.entity.LsDataSrc;
import kr.co.cudo.authoring.batch.repository.LsDataLblAiInfoRepository;
import kr.co.cudo.authoring.batch.repository.LsDataLblRepository;
import kr.co.cudo.authoring.batch.repository.LsDataSrcRepository;
import kr.co.cudo.authoring.common.security.Channel;
import kr.co.cudo.authoring.common.security.Role;
import kr.co.cudo.authoring.common.security.TokenClaims;
import kr.co.cudo.authoring.label.entity.LsDataLblAttrVal;
import kr.co.cudo.authoring.label.entity.LsLabel;
import kr.co.cudo.authoring.label.entity.LsLabelAttr;
import kr.co.cudo.authoring.label.repository.LsDataLblAttrValRepository;
import kr.co.cudo.authoring.label.repository.LsLabelAttrRepository;
import kr.co.cudo.authoring.label.repository.LsLabelRepository;
import kr.co.cudo.authoring.version.dto.DiffResponseDto;
import kr.co.cudo.authoring.version.entity.LsLabelVersion;
import kr.co.cudo.authoring.version.repository.LsLabelVersionRepository;
import kr.co.cudo.authoring.video.entity.LsDataRaw;
import kr.co.cudo.authoring.video.repository.VideoRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * 롤백 라벨 복원 통합 테스트 (Testcontainers PostgreSQL) — D-ISSUE-22 / D-ISSUE-23.
 *
 * <p>명시 PK 삽입({@code GENERATED BY DEFAULT AS IDENTITY})·IDENTITY 시퀀스 동기화·실 FK
 * ({@code LS_DATA_LBL_ATTR_VAL})·1차 캐시 정합은 <b>실 DB 동작</b>이라 mock 단위테스트로 갈음할 수 없다.
 * 따라서 본 클래스는 실제 컨테이너 DB 위에서 검증한다.
 */
@SpringBootTest
@ActiveProfiles("local")
@Sql(scripts = {"/db/test-data.sql", "/db/test-data-video.sql"},
        executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class VersionRollbackRestoreIT {

    @Autowired private VersionService versionService;
    @Autowired private LsLabelVersionRepository labelVersionRepository;
    @Autowired private VideoRepository rawRepository;
    @Autowired private LsDataSrcRepository srcRepository;
    @Autowired private LsDataLblRepository labelRepository;
    @Autowired private LsDataLblAiInfoRepository aiInfoRepository;
    @Autowired private LsDataLblAttrValRepository attrValRepository;
    @Autowired private LsLabelRepository lsLabelRepository;
    @Autowired private LsLabelAttrRepository lsLabelAttrRepository;
    @Autowired private LsTaskAssignmentRepository assignmentRepository;
    @Autowired private WorkLockService workLockService;

    private Long rawSn;
    private Long srcSn;
    private TokenClaims reviewer;
    /** 속성값 FK 테스트가 만든 라벨 마스터/속성 정의 — 다른 테스트 오염 방지를 위해 반드시 정리한다. */
    private Long createdAttrId;
    private Long createdLabelId;

    @BeforeEach
    void setUp() {
        LsDataRaw raw = rawRepository.save(LsDataRaw.createFromIngest(
                "CLIP-RBK-001", "CCTV-001", "EVT-A", "11680",
                LsDataRaw.PRVC_TYPE_ANONY, "/var/raw/clip.mp4", LocalDateTime.now(), 30));
        rawSn = raw.getRawSn();
        srcSn = srcRepository.save(LsDataSrc.create(rawSn, 0, "/raw/0.jpg", LocalDateTime.now()))
                .getSrcSn();
        assignmentRepository.save(LsTaskAssignment.createLabeler(rawSn, 100L, 1L));
        workLockService.releaseRaw(rawSn, "test", "TEST_SETUP");
        reviewer = new TokenClaims("1", Role.REVIEWER, Channel.INTERNAL, Instant.now().plusSeconds(60));
    }

    @AfterEach
    void tearDown() {
        // LS_LABEL_ATTR 이 남으면 LS_LABEL 을 전량 삭제하는 다른 테스트가 FK 위반으로 깨진다(테스트 오염).
        if (createdAttrId != null) {
            lsLabelAttrRepository.deleteById(createdAttrId);
            createdAttrId = null;
        }
        if (createdLabelId != null) {
            lsLabelRepository.deleteById(createdLabelId);
            createdLabelId = null;
        }
    }

    // ---------- 픽스처 ----------

    private LsDataLbl seedLabel(Long frameSn, String label, String pointsJson) {
        return labelRepository.save(
                LsDataLbl.createManual(frameSn, LsDataLbl.TYPE_BBOX, null, label, pointsJson, 100L));
    }

    /** 지정 payload 를 그대로 담은 active 버전 행을 적재하고 해시를 반환(롤백 입력용). */
    private String seedVersion(String hash, String payload) {
        labelVersionRepository.save(LsLabelVersion.create(
                rawSn, srcSn, hash, payload, 1, LsLabelVersion.SAVE_REASON_APPROVED, "1"));
        return hash;
    }

    /** commitApproved 가 만든 현재 active 스냅샷 해시. */
    private String activeSnapshotHash() {
        return labelVersionRepository.findByDataSrcSnOrderByRegDtDesc(srcSn).stream()
                .filter(v -> LsLabelVersion.ACTIVE_YES.equals(v.getActiveYn()))
                .findFirst().orElseThrow().getVersionHash();
    }

    /** 스냅샷 item 1건 JSON — 옛 LBL_SN(id) 및 AI 메타/트랙 포함(필드는 null 허용). */
    private static String item(Long id, String label, String points, String autoLblYn,
                               String confScore, String trackId, String lblSrcCd) {
        return "{\"id\":" + id + ",\"lblTypeCd\":\"BBOX\",\"label\":\"" + label
                + "\",\"labelId\":null,\"points\":" + points
                + ",\"autoLblYn\":" + (autoLblYn == null ? "null" : "\"" + autoLblYn + "\"")
                + ",\"confScore\":" + (confScore == null ? "null" : confScore)
                + ",\"trackId\":" + (trackId == null ? "null" : "\"" + trackId + "\"")
                + ",\"lblSrcCd\":" + (lblSrcCd == null ? "null" : "\"" + lblSrcCd + "\"") + "}";
    }

    private String payload(String... items) {
        return "{\"srcSn\":" + srcSn + ",\"frameNo\":0,\"items\":[" + String.join(",", items) + "]}";
    }

    // ---------- D-22: LBL_SN 보존 ----------

    @Test
    @DisplayName("롤백_복원시_스냅샷의_LBL_SN_이_그대로_유지된다")
    void rollbackPreservesSnapshotLblSn() {
        // given — 라벨 2건으로 승인 스냅샷 v1 생성 후, 라벨을 전혀 다른 세트로 교체.
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long id2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        labelRepository.deleteAllByIdInBatch(List.of(id1, id2));
        seedLabel(srcSn, "bike", "[[7.0,7.0],[8.0,8.0]]");

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 옛 LBL_SN 이 그대로 복원(재발급 금지).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn)
                .containsExactlyInAnyOrder(id1, id2);
        assertThat(after).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("person", "car");
    }

    @Test
    @DisplayName("좌표가_동일한_롤백_후_diff_가_변경없음으로_판정")
    void diffAfterRoundTripReportsNoChange() {
        // given — v1(person) → 수정(car) → v2 → v1 로 롤백 → 재승인.
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        labelRepository.deleteAllByIdInBatch(List.of(id1));
        seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        versionService.commitApproved(rawSn, reviewer);

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);
        versionService.commitApproved(rawSn, reviewer);

        // then — 롤백 후 상태는 v1 과 라벨 식별자·좌표가 동일하므로 diff 는 변경 0건.
        DiffResponseDto diff = versionService.diff(v1Hash, activeSnapshotHash(), reviewer);
        assertThat(diff.labels()).isEmpty();
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(id1);
    }

    // ---------- S1: PK 충돌 폴백 ----------

    @Test
    @DisplayName("복원하려는_LBL_SN_이_이미_존재하면_신규발급으로_폴백하고_전체가_실패하지_않는다")
    void conflictingLblSnFallsBackToNewId() {
        // given — 다른 프레임(other)이 LBL_SN 을 점유한 상태의 스냅샷.
        Long otherSrcSn = srcRepository.save(LsDataSrc.create(rawSn, 1, "/raw/1.jpg", LocalDateTime.now()))
                .getSrcSn();
        Long occupiedId = seedLabel(otherSrcSn, "occupied", "[[0.0,0.0],[1.0,1.0]]").getLblSn();
        String hash = seedVersion("aa11bb22cc33dd44ee55ff66aa77bb88cc99dd00",
                payload(item(occupiedId, "person", "[[10.0,10.0],[50.0,50.0]]", null, null, null, null)));

        // when — 점유된 PK 로 복원 시도.
        assertThatCode(() -> versionService.rollback(hash, srcSn, reviewer)).doesNotThrowAnyException();

        // then — 대상 프레임은 새 PK 로 복원되고, 점유 라벨(타 프레임)은 그대로 남는다.
        List<LsDataLbl> restored = labelRepository.findBySrcSn(srcSn);
        assertThat(restored).hasSize(1);
        assertThat(restored.get(0).getLblSn()).isNotEqualTo(occupiedId);
        assertThat(restored.get(0).getLabelNm()).isEqualTo("person");
        assertThat(labelRepository.findById(occupiedId)).isPresent()
                .get().extracting(LsDataLbl::getSrcSn).isEqualTo(otherSrcSn);
    }

    // ---------- S2: IDENTITY 시퀀스 동기화 ----------

    @Test
    @DisplayName("명시_PK_복원_후에도_다음_라벨_저장이_PK_충돌없이_성공한다")
    void identitySequenceStaysAheadAfterExplicitIdRestore() {
        // given — 시퀀스가 다음에 발급할 값(maxId + 1)을 스냅샷 LBL_SN 으로 사용한다.
        //   시퀀스를 동기화하지 않으면 이후 첫 라벨 저장이 이 PK 를 재발급해 23505(중복키)로 전면 실패한다.
        Long maxId = seedLabel(srcSn, "seed", "[[0.0,0.0],[1.0,1.0]]").getLblSn();
        Long nextIdentity = maxId + 1;
        String hash = seedVersion("bb11cc22dd33ee44ff55aa66bb77cc88dd99ee00",
                payload(item(nextIdentity, "person", "[[10.0,10.0],[50.0,50.0]]", null, null, null, null)));

        versionService.rollback(hash, srcSn, reviewer);
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(nextIdentity);

        // when / then — 복원 이후 신규 라벨 저장이 PK 충돌 없이 성공해야 한다.
        assertThatCode(() -> {
            LsDataLbl saved = seedLabel(srcSn, "after", "[[2.0,2.0],[3.0,3.0]]");
            assertThat(saved.getLblSn()).isGreaterThan(nextIdentity);
        }).doesNotThrowAnyException();
    }

    // ---------- S5: 같은 트랜잭션 재조회 정합 ----------

    @Test
    @DisplayName("복원_직후_같은_트랜잭션에서_재조회하면_새_라벨이_보인다")
    @Transactional(transactionManager = "controlTransactionManager")
    void restoredLabelsVisibleInSameTransaction() {
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long id2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();
        labelRepository.deleteAllByIdInBatch(List.of(id1, id2));
        assertThat(labelRepository.findBySrcSn(srcSn)).isEmpty();

        versionService.rollback(v1Hash, srcSn, reviewer);

        // 네이티브 삽입은 영속성 컨텍스트를 우회하므로 같은 트랜잭션 재조회가 0건이 되면 안 된다.
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn).containsExactlyInAnyOrder(id1, id2);
    }

    /**
     * DEV_FIX-B(M4) — bulk delete(JPQL) 는 1차 캐시를 evict 하지 않는다. 복원 대상 {@code LBL_SN} 이
     * managed 로 남아 있으면 후속 조회가 <b>복원 전 내용</b>을 돌려준다(행 수만 맞음).
     *
     * <p>구 테스트({@link #restoredLabelsVisibleInSameTransaction})는 {@code LBL_SN} 만 단언하고
     * 픽스처가 "복원 전 == 복원 후" 라 stale 을 원리적으로 검출할 수 없었다. 여기서는 <b>복원 전 작업본을
     * 드리프트</b>시켜(라벨명·좌표 상이) 내용까지 단언한다.
     */
    @Test
    @DisplayName("복원_후_재조회가_복원_전_내용을_돌려주지_않는다")
    @Transactional(transactionManager = "controlTransactionManager")
    void reReadAfterRestoreDoesNotReturnStalePersistenceContextState() {
        // given — v1 스냅샷(person/car) 생성 후, 같은 LBL_SN 을 유지한 채 내용만 드리프트시킨다.
        LsDataLbl l1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]");
        LsDataLbl l2 = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        Long id1 = l1.getLblSn();
        Long id2 = l2.getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        l1.updateUserContent(LsDataLbl.TYPE_BBOX, null, "drifted-person", "[[99.0,99.0],[100.0,100.0]]");
        l2.updateUserContent(LsDataLbl.TYPE_BBOX, null, "drifted-car", "[[98.0,98.0],[100.0,100.0]]");
        labelRepository.flush();
        // 드리프트된 인스턴스가 1차 캐시에 managed 로 남아 있는 상태(= stale 재현 조건).
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("drifted-person", "drifted-car");

        // when — v1 로 롤백(같은 LBL_SN 으로 원래 내용 복원).
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 같은 트랜잭션 재조회가 복원 <b>후</b> 내용을 돌려줘야 한다(행 수·식별자만이 아니라 내용까지).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).extracting(LsDataLbl::getLblSn).containsExactlyInAnyOrder(id1, id2);
        assertThat(after).extracting(LsDataLbl::getLabelNm)
                .containsExactlyInAnyOrder("person", "car");
        assertThat(after).extracting(LsDataLbl::getPointCn)
                .containsExactlyInAnyOrder("[[10.0,10.0],[50.0,50.0]]", "[[1.0,1.0],[2.0,2.0]]");
    }

    /**
     * DEV_FIX-B(M2) — SKELETON 왕복 롤백이 {@code POINT_CN} 의 가시성 v 표현을 변질시키지 않는지
     * <b>실 DB 값</b>으로 확인한다(스냅샷은 v 를 {@code 2.0} 으로, DB 는 {@code 2} 로 쓴다).
     */
    @Test
    @DisplayName("SKELETON_왕복_롤백_후_POINT_CN_의_v_가_변질되지_않는다")
    void skeletonRoundTripKeepsPointCnRepresentation() {
        // given — 17-keypoint SKELETON 라벨 1건으로 v1 스냅샷 생성.
        String keypoints = skeletonPoints();
        Long id = labelRepository.save(LsDataLbl.createManual(
                srcSn, LsDataLbl.TYPE_SKELETON, null, "person", keypoints, 100L)).getLblSn();
        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();

        // 작업본을 드리프트시켜 실제 교체 경로를 타게 한다.
        seedLabel(srcSn, "drift", "[[9.0,9.0],[9.5,9.5]]");

        // when
        versionService.rollback(v1Hash, srcSn, reviewer);

        // then — 복원된 좌표는 DB 정규형 그대로(v 가 2.0 으로 변질되지 않음).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLblSn()).isEqualTo(id);
        assertThat(after.get(0).getPointCn()).isEqualTo(keypoints);
        assertThat(after.get(0).getPointCn()).doesNotContain("2.0]");
    }

    /** COCO-17 키포인트 좌표(DB 정규형 — x/y 는 double, v 는 정수). */
    private static String skeletonPoints() {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < 17; i++) {
            if (i > 0) {
                sb.append(',');
            }
            sb.append('[').append(10.0 + i).append(',').append(20.0 + i).append(",2]");
        }
        return sb.append(']').toString();
    }

    // ---------- D-23: 속성값 FK / AI 메타 / TRCK_ID ----------

    @Test
    @DisplayName("속성값을_보유한_프레임_롤백시_FK_위반_500_이_발생하지_않는다")
    void rollbackWithAttributeValuesDoesNotViolateFk() {
        // given — 라벨 1건 + 그 라벨의 속성값(LS_DATA_LBL_ATTR_VAL — LS_DATA_LBL 에 실 FK).
        Long id1 = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        createdLabelId = lsLabelRepository.save(
                LsLabel.create("롤백복원IT라벨", "#FF0000", LsDataLbl.TYPE_BBOX, 1, "1")).getLabelId();
        createdAttrId = lsLabelAttrRepository.save(LsLabelAttr.create(
                createdLabelId, "색상", LsLabelAttr.INPUT_TEXT, null, null, "Y", 1, "1")).getAttrId();
        attrValRepository.save(LsDataLblAttrVal.create(id1, createdAttrId, "red"));

        versionService.commitApproved(rawSn, reviewer);
        String v1Hash = activeSnapshotHash();
        // D-ISSUE-24 — 작업본이 스냅샷과 완전히 동일하면 롤백은 진짜 no-op(라벨 미교체)이 되어 FK 경로를
        //   타지 않는다. 실제 교체 경로를 검증하려면 작업본을 드리프트시켜 둔다.
        seedLabel(srcSn, "drift", "[[9.0,9.0],[9.5,9.5]]");

        // when / then — 속성값 선정리 없이 부모를 지우면 FK 위반(500)이 된다.
        assertThatCode(() -> versionService.rollback(v1Hash, srcSn, reviewer))
                .doesNotThrowAnyException();
        assertThat(labelRepository.findBySrcSn(srcSn)).extracting(LsDataLbl::getLblSn)
                .containsExactly(id1);
        // ★ 알려진 한계(적대 #7 — 스코프 밖, 별건): 스냅샷 payload 에 라벨 <b>속성값</b> 필드가 없어
        //   어떤 버전으로 롤백해도 LS_DATA_LBL_ATTR_VAL 은 복원할 수 없다(FK 위반 방지를 위해 삭제만 한다).
        //   따라서 아래 isEmpty() 는 "정상 동작"이 아니라 <b>복원 불가라는 현 한계를 고정</b>한 단언이다.
        //   복원까지 하려면 스냅샷 스키마 확장(속성값 포함)이 선행돼야 하며 본 수정 범위가 아니다.
        assertThat(attrValRepository.findByLblSnIn(List.of(id1))).isEmpty();
    }

    @Test
    @DisplayName("롤백_후_AI메타와_TRCK_ID_가_고아가_되지_않고_복원된다")
    void rollbackRestoresAiMetaAndTrackIdWithoutOrphans() {
        // given — 라벨 A(스냅샷 대상) / 라벨 B(스냅샷 미포함) 각각 AI 메타 보유.
        Long idA = seedLabel(srcSn, "person", "[[10.0,10.0],[50.0,50.0]]").getLblSn();
        Long idB = seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]").getLblSn();
        aiInfoRepository.save(LsDataLblAiInfo.create(idA, rawSn, srcSn,
                LsDataLblAiInfo.SRC_YOLO, new BigDecimal("0.50000"), "1"));
        aiInfoRepository.save(LsDataLblAiInfo.create(idB, rawSn, srcSn,
                LsDataLblAiInfo.SRC_SAM2, new BigDecimal("0.60000"), "1"));
        String hash = seedVersion("cc11dd22ee33ff44aa55bb66cc77dd88ee99ff00",
                payload(item(idA, "person", "[[10.0,10.0],[50.0,50.0]]",
                        LsDataLbl.AUTO_YES, "0.90000", "T-1", LsDataLblAiInfo.SRC_YOLO)));

        // when
        versionService.rollback(hash, srcSn, reviewer);

        // then — TRCK_ID 복원(구 구현은 createManual 이라 항상 NULL).
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLblSn()).isEqualTo(idA);
        assertThat(after.get(0).getTrackId()).isEqualTo("T-1");

        // AI 메타는 스냅샷 값으로 복원.
        List<LsDataLblAiInfo> aiA = aiInfoRepository.findByDataLblSnIn(List.of(idA));
        assertThat(aiA).hasSize(1);
        assertThat(aiA.get(0).getLblSrcCd()).isEqualTo(LsDataLblAiInfo.SRC_YOLO);
        assertThat(aiA.get(0).getAutoLblYn()).isEqualTo(LsDataLbl.AUTO_YES);
        assertThat(aiA.get(0).getConfScore()).isEqualByComparingTo("0.90000");

        // 스냅샷에 없어 삭제된 라벨 B 의 AI 메타는 고아로 남지 않는다.
        assertThat(aiInfoRepository.findByDataLblSnIn(List.of(idB))).isEmpty();
    }

    @Test
    @DisplayName("AI메타_키가_없는_옛_스냅샷도_롤백이_성공한다")
    void legacySnapshotWithoutAiMetaKeysStillRolledBack() {
        // given — id/autoLblYn/confScore/trackId/lblSrcCd 키가 전혀 없는 옛 스냅샷 형식.
        seedLabel(srcSn, "car", "[[1.0,1.0],[2.0,2.0]]");
        String legacyPayload = "{\"srcSn\":" + srcSn + ",\"frameNo\":0,\"items\":["
                + "{\"lblTypeCd\":\"BBOX\",\"label\":\"person\",\"points\":[[10.0,10.0],[50.0,50.0]]}]}";
        String hash = seedVersion("dd11ee22ff33aa44bb55cc66dd77ee88ff99aa00", legacyPayload);

        // when / then — 신규 PK 발급으로 복원되고 예외가 없어야 한다.
        assertThatCode(() -> versionService.rollback(hash, srcSn, reviewer))
                .doesNotThrowAnyException();
        List<LsDataLbl> after = labelRepository.findBySrcSn(srcSn);
        assertThat(after).hasSize(1);
        assertThat(after.get(0).getLabelNm()).isEqualTo("person");
        assertThat(after.get(0).getTrackId()).isNull();
        assertThat(aiInfoRepository.findByDataLblSnIn(List.of(after.get(0).getLblSn()))).isEmpty();
    }
}
