package kr.co.cudo.authoring.batch.repository;

import java.util.List;
import java.util.Set;

/**
 * {@link LsDataLblRepository} 커스텀 프래그먼트 — <b>LBL_SN 을 명시 지정</b>하는 라벨 복원 삽입.
 *
 * <p>버전 롤백(D-ISSUE-22)은 스냅샷의 {@code items[].id}(= 옛 {@code LBL_SN})를 그대로 되살려야 한다.
 * diff/이력의 라벨 식별 축이 {@code LBL_SN} 이므로, 재발급하면 좌표가 동일해도 "전량 삭제 + 전량 추가"
 * 로 오분류된다. JPA {@code GenerationType.IDENTITY} 전략은 엔티티에 수동으로 넣은 PK 를 무시하므로
 * (DB 컬럼은 {@code GENERATED BY DEFAULT AS IDENTITY} 라 명시 삽입 자체는 허용) 네이티브 경로가 필요하다.
 */
public interface LsDataLblRepositoryCustom {

    /**
     * 명시 PK 복원 대상 1건. 값은 모두 파라미터 바인딩되며 SQL 문자열에 결합되지 않는다(CWE-89).
     *
     * <h3>V6 — AI 메타 3필드가 여기로 들어왔다 (Critical)</h3>
     * 흡수 전에는 이 네이티브 삽입이 라벨 본문만 넣고, 생산이력(자동라벨 여부·신뢰도·출처)은 호출부가
     * {@code LS_DATA_LBL_AI_INFO} 에 <b>따로</b> 적재했다. 흡수 후 그 값들은 <b>같은 행의 컬럼</b>이라
     * 여기서 함께 넣지 않으면 복원된 라벨의 생산이력이 통째로 {@code null} 이 된다(자동 라벨이
     * 수동으로 둔갑하고 신뢰도·출처가 소실된다).
     *
     * @param lblSn     복원할 {@code LBL_SN}(필수)
     * @param lblTypeCd 라벨 타입(필수)
     * @param labelId   {@code LS_LABEL} FK (null 허용)
     * @param labelNm   라벨명(필수)
     * @param pointCn   좌표 JSON (null 허용)
     * @param trackId   트랙 ID (null 허용 — 수동 라벨/미부여)
     * @param autoLblYn 스냅샷의 자동라벨 여부 (null 허용 — AI 정보가 없던 라벨)
     * @param confScore 스냅샷의 신뢰도 (null 허용)
     * @param lblSrcCd  스냅샷의 라벨 출처 (null 허용 — 없으면 지어내지 않는다)
     */
    record RestoreRow(Long lblSn, String lblTypeCd, Long labelId, String labelNm,
                      String pointCn, String trackId,
                      String autoLblYn, java.math.BigDecimal confScore, String lblSrcCd) {
    }

    /**
     * 주어진 라벨들을 {@code LBL_SN} 명시 지정으로 프레임({@code srcSn}) 에 일괄 INSERT 한다.
     *
     * <p>동작/보증:
     * <ul>
     *   <li><b>단일 JDBC 배치</b>({@code Session#doWork}) — 호출자의 활성 트랜잭션·동일 커넥션에서 실행되어
     *       원자적으로 참여한다(별도 커넥션/트랜잭션 분리 없음 → 라벨 저장 경로와 ABBA 데드락 없음).</li>
     *   <li><b>PK 충돌 내성</b>: {@code ON CONFLICT (LBL_SN) DO NOTHING} — 이미 다른 라벨이 그 PK 를
     *       점유하고 있으면 해당 1건만 건너뛴다(전체 실패로 만들지 않는다). 반환 집합에서 빠지므로
     *       호출자가 신규 PK 발급으로 폴백할 수 있다.</li>
     *   <li><b>삽입 성공 판정</b>: 드라이버별 배치 update count 편차({@code reWriteBatchedInserts} 시
     *       {@code SUCCESS_NO_INFO})에 의존하지 않고, 삽입 후 "이 프레임이 소유한 LBL_SN" 재조회로 확정한다.
     *       <b>전제</b>는 호출 시점에 따라 둘 중 하나가 성립해야 한다 — 어느 쪽이든 재조회가 방금 삽입한
     *       행만 돌려주므로 {@code OWNED_SQL} 판정(이 프레임 소유 여부)이 그대로 유효하다:
     *       <ol>
     *         <li>호출 전 그 프레임의 기존 라벨이 <b>모두 삭제</b>되어 있다(롤백 복원 규약 — D-ISSUE-22.
     *             삭제 후 호출이라 그 프레임에 남은 라벨이 없어 재조회 결과가 곧 신규 삽입분이다).</li>
     *         <li>기존 라벨이 남아 있어도, 요청 {@code rows} 의 {@code lblSn} 전부가 그 프레임에
     *             <b>미실재</b>한다(확정 저장의 스냅샷 PK 복원 — {@code LabelService.restoreSnapshotPks}.
     *             호출부가 "그 프레임에 없는 PK 만" 골라 넘기므로 삭제 델타 이전에 호출해도 기존 라벨과
     *             교집합이 없어, 재조회가 여전히 방금 삽입한 행만 돌려준다).</li>
     *       </ol></li>
     *   <li><b>IDENTITY 시퀀스 동기화</b>: 1건 이상 삽입되면 마지막에 <b>1회</b> {@code setval} 로 시퀀스를
     *       {@code MAX(LBL_SN)} 이후로 끌어올린다. 하지 않으면 이후 모든 라벨 저장이 PK 충돌(23505)로
     *       전면 실패한다. 현재 시퀀스 값보다 낮추지 않도록 {@code GREATEST} 로 보호한다.</li>
     *   <li><b>1차 캐시 정합</b>: 배치 직전 {@code flush()} 로 선행 삭제/수정을 DB 에 반영한다(네이티브 SQL
     *       은 Hibernate auto-flush 대상이 아니다). 컨텍스트 {@code clear()} 는 하지 않는다 — 호출자가
     *       보유한 {@code FOR UPDATE} 잠금 엔티티가 detach 되어 이후 상태 전환이 유실되는 회귀를 막기 위함.</li>
     * </ul>
     *
     * @param srcSn 대상 프레임 SRC_SN
     * @param rows  복원 대상 (비었으면 no-op)
     * @return 실제로 삽입된 {@code LBL_SN} 집합 (충돌로 건너뛴 건은 미포함)
     */
    Set<Long> insertRestoredWithExplicitIds(Long srcSn, List<RestoreRow> rows);
}
