-- =============================================================================
-- V109: 포털 전용 이미지/영상 업로드 + 수동 라벨링 데이터 기반 (3테이블)
--
-- 목적: 포털 사용자(PORTAL_USER)가 직접 업로드한 이미지/영상과 그 위에 남긴 수동
--       라벨을 적재한다. 원본(LS_DATA_RAW)·데이터마트와 무관한 포털 전용 작업본이며,
--       LS_PORTAL_USER_LABEL(데이터마트 영상 위 라벨)과는 별개 경로다.
--
-- 표준용어(glossary 확정): 업로드=ULD, 프레임=FRME, 크기=SZ, 사유=RSN, 라벨=LBL,
--   포털=PORTAL, 원본=ORGNL. (기존 드리프트 FRM_NO 등은 신규 테이블에 답습하지 않음 → FRME_NO)
--
-- 소유자 스코프: 모든 조회는 PORTAL_USER_NO 로 스코프(IDOR 방지). 라벨/프레임은
--   업로드에 종속되어 ON DELETE CASCADE 로 연쇄 정리된다.
--
-- PostgreSQL 표준 문법. LS_* 접두사 저작도구 전용 테이블 — 관제서버팀 협의 면제.
-- =============================================================================

-- ============================================================
-- LS_PORTAL_ULD : 포털 업로드 원본(이미지 1장 또는 영상 1건)
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD (
    ULD_SN         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PORTAL_USER_NO VARCHAR(100) NOT NULL,
    ULD_TYPE_CD    VARCHAR(16)  NOT NULL,   -- IMAGE | VIDEO
    ORGNL_FILE_NM  VARCHAR(255),            -- 업로드 당시 원본 파일명
    FILE_PATH_NM   VARCHAR(500),            -- 저장 경로(이미지=원본, 영상=원본 영상)
    FILE_SZ        BIGINT,                  -- 바이트 크기
    MIME_TYPE_NM   VARCHAR(100),
    ULD_STTS_CD    VARCHAR(16)  NOT NULL,   -- UPLOADED | PROCESSING | READY | FAILED
    VDO_LEN_SEC    DOUBLE PRECISION,        -- 영상만: 길이(초)
    FPS            DOUBLE PRECISION,        -- 영상만: 초당 프레임
    FRME_CNT       INT,                     -- 영상만: 추출된 프레임 수
    FAIL_RSN_CN    TEXT,                    -- 실패 사유(내용)
    REG_DT         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_USER_REG
    ON LS_PORTAL_ULD (PORTAL_USER_NO, REG_DT);

COMMENT ON TABLE  LS_PORTAL_ULD                IS '포털 전용 업로드 원본(이미지/영상) — 데이터마트/원본과 무관한 포털 작업본.';
COMMENT ON COLUMN LS_PORTAL_ULD.ULD_TYPE_CD    IS '업로드 유형: IMAGE | VIDEO.';
COMMENT ON COLUMN LS_PORTAL_ULD.ULD_STTS_CD    IS '업로드 상태: UPLOADED | PROCESSING | READY | FAILED.';
COMMENT ON COLUMN LS_PORTAL_ULD.FRME_CNT       IS '영상 추출 프레임 수(이미지는 null).';
COMMENT ON COLUMN LS_PORTAL_ULD.FAIL_RSN_CN    IS '처리 실패 사유(내용). 상태 FAILED 시 기록.';

-- ============================================================
-- LS_PORTAL_ULD_FRME : 업로드 프레임(이미지=1행, 영상=추출 프레임 N행)
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD_FRME (
    ULD_FRME_SN  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ULD_SN       BIGINT       NOT NULL,
    FRME_NO      INT          NOT NULL,    -- 프레임 순번(이미지=0)
    FILE_PATH_NM VARCHAR(500) NOT NULL,    -- 프레임 이미지 저장 경로
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_FRME_SN),
    CONSTRAINT FK_LS_PORTAL_ULD_FRME_ULD
        FOREIGN KEY (ULD_SN) REFERENCES LS_PORTAL_ULD (ULD_SN) ON DELETE CASCADE,
    CONSTRAINT UK_LS_PORTAL_ULD_FRME UNIQUE (ULD_SN, FRME_NO)
);

COMMENT ON TABLE  LS_PORTAL_ULD_FRME         IS '포털 업로드 프레임(이미지=1행, 영상=추출 프레임 N행). 업로드 삭제 시 연쇄 삭제.';
COMMENT ON COLUMN LS_PORTAL_ULD_FRME.FRME_NO IS '프레임 순번(영상 추출 순서, 이미지는 0).';

-- ============================================================
-- LS_PORTAL_ULD_LBL : 업로드 프레임 위 수동 라벨(BBOX/POLYGON)
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD_LBL (
    ULD_LBL_SN     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PORTAL_USER_NO VARCHAR(100) NOT NULL,
    ULD_SN         BIGINT       NOT NULL,
    ULD_FRME_SN    BIGINT       NOT NULL,
    LBL_TYPE_CD    VARCHAR(16)  NOT NULL,   -- BBOX | POLYGON
    LBL_NM         VARCHAR(80),             -- 라벨(클래스)명
    POINT_CN       TEXT,                    -- 좌표 JSON(내용)
    REG_DT         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_LBL_SN),
    CONSTRAINT FK_LS_PORTAL_ULD_LBL_FRME
        FOREIGN KEY (ULD_FRME_SN) REFERENCES LS_PORTAL_ULD_FRME (ULD_FRME_SN) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_LBL_USER_ULD
    ON LS_PORTAL_ULD_LBL (PORTAL_USER_NO, ULD_SN);

CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_LBL_FRME
    ON LS_PORTAL_ULD_LBL (ULD_FRME_SN);

COMMENT ON TABLE  LS_PORTAL_ULD_LBL             IS '포털 업로드 프레임 위 수동 라벨(BBOX/POLYGON). 프레임 삭제 시 연쇄 삭제.';
COMMENT ON COLUMN LS_PORTAL_ULD_LBL.LBL_TYPE_CD IS '라벨 유형: BBOX | POLYGON.';
COMMENT ON COLUMN LS_PORTAL_ULD_LBL.POINT_CN    IS '좌표 JSON 내용(BBOX=[x,y,w,h] / POLYGON=[[x,y],...]).';

-- ============================================================
-- LS_SYSTEM_CONFIG 시드 : 포털 업로드 영상 프레임 추출 간격(초)
--   - STNG_TYPE_CD = NUMBER (정수) → SystemConfigService.getInt 로 조회
--   - 범위 1~600 (ConfigKeys.NUMBER_RANGE), 기본 5
--   - 컬럼명은 V61 glossary rename 반영: STNG_KEY / STNG_VALUE / STNG_TYPE_CD
--   - 멱등: ON CONFLICT DO NOTHING (이미 존재하면 NOOP)
-- ============================================================
INSERT INTO LS_SYSTEM_CONFIG (STNG_KEY, STNG_VALUE, STNG_TYPE_CD, EXPLN, MDFR_ID) VALUES
    ('portal.upload.frame-interval-sec', '5', 'NUMBER',
     '포털 업로드 영상 프레임 추출 간격(초, 1~600)', 'SYSTEM')
ON CONFLICT (STNG_KEY) DO NOTHING;
