-- V117: 물리 컬럼/제약 표준단어 정합 rename (타입/사이즈/데이터 불변).
-- 'RES' 는 사업표준단어가 아니다(false-friend) — 해상도=RESL, 응답=RESP 로 통일한다.
-- 기존 컬럼은 V55(LS_RESOLUTION_EXPORT)/V12(LS_BATCH_PROC_LOG)/V80(GOAL_RES_CD)에서 생성됐고,
-- historical 마이그레이션은 편집하지 않고 여기서 RENAME 으로 데이터 보존 정합한다.
-- Java 필드명/getter/API JSON 키는 불변 — 엔티티 @Column(name) 만 새 물리명으로 매핑한다.
-- PostgreSQL 표준 문법. RENAME COLUMN 시 PK/UK/인덱스가 컬럼 참조를 자동 follow 한다.

-- LS_RESOLUTION_EXPORT: 해상도(RESL) 정합
ALTER TABLE LS_RESOLUTION_EXPORT RENAME COLUMN RES_EXPORT_SN TO RESL_EXPORT_SN;
ALTER TABLE LS_RESOLUTION_EXPORT RENAME COLUMN GOAL_RES_CD   TO GOAL_RESL_CD;
-- V55 에서 CONSTRAINT ... UNIQUE 로 명명된 제약 → RENAME CONSTRAINT
ALTER TABLE LS_RESOLUTION_EXPORT RENAME CONSTRAINT UK_LS_RES_EXPORT_RAW_RES TO UK_LS_RESL_EXPORT_RAW_RESL;

-- LS_BATCH_PROC_LOG: 응답(RESP) 정합
ALTER TABLE LS_BATCH_PROC_LOG RENAME COLUMN RES_PAYLOAD_CN TO RESP_PAYLOAD_CN;
