-- =============================================================================
-- V140: 증강 외부 위탁 작업 LS_DATA_AUG_JOB (Phase 7-A1 — 생성형 AI 요청 경로 실배선)
--
-- 목적: 「생성형 AI API 연동명세서 v1.1」 정합으로 외부 위탁을 실제 HTTP 로 보내면서,
--       요청 1건(LS_DATA_AUG 1행)이 input_files 상한(100장) 때문에 여러 job 으로
--       분할 위탁되는 것을 추적한다. LS_DATA_AUG 1행 : LS_DATA_AUG_JOB N행.
--
-- 왜 필요한가:
--   1) job_id 발급 주체 반전 — 이제 외부가 202 응답으로 job_id 를 준다. 우리는 request_id
--      (=Idempotency-Key)만 발급하므로 "우리 키 ↔ 외부 job_id" 매핑을 어딘가 남겨야 한다.
--   2) 분할 위탁 — 프레임 250장이면 100/100/50 세 job 이다. LS_DATA_AUG 의 단일
--      OTSD_JOB_ID 컬럼(UNIQUE)으로는 표현할 수 없다.
--   3) 실패 가시화 — 기존 AugmentRequestBridge 는 외부 호출 예외를 WARN 으로 삼켜
--      요청이 조용히 유실됐다. 실패를 사유(ERR_CD/ERR_MSG_CN)와 함께 행으로 남긴다.
--
-- 표준용어 준거(정본: docs/표준용어 — 사업표준단어·사업표준도메인·사업표준용어, 공공 공통표준단어):
--   단어) 증강=AUG(사업), 작업=JOB(사업), 순서=SEQ(사업), 건수=NOCS(사업), 외부=OTSD(공공 6차),
--         상태=STTS(사업), 코드=CD(사업), 오류=ERR(사업), 메시지=MSG(사업), 내용=CN(사업),
--         일련번호=SN(사업).
--   용어) 등록된 복합용어를 그대로 채택한다(단어 재조합보다 우선):
--         - 총건수 = TOT_NOCS  (사업표준용어 등록명. '총=TOTAL' 단어 조합 대신 등록 용어 사용)
--         - 멱등키 = IDMP_KEY, V128  (사업표준용어 등록 — 선존 LS_DATA_AUG/LS_WEBHOOK_IDEMPOTENCY 동일)
--         - 외부작업아이디 = OTSD_JOB_ID, 명V200 (사업표준용어 등록 — 선존 두 테이블과 동일)
--         - 오류코드 = ERR_CD, V50 (사업표준용어 등록). 코드V20 이 아니라 등록 크기 50 을 쓴다 —
--           외부 계약 오류코드가 'REQUIRED_FIELD_MISSING'(22자)·'MODEL_EXECUTION_FAILED'(22자)로
--           20 을 넘어 절삭되기 때문이며, 등록 용어와도 일치한다.
--   도메인) 코드V20 = VARCHAR(20) : JOB_STTS_CD
--           수I11   = INTEGER     : JOB_SEQ / TOT_NOCS (순서 전용 도메인 부재 → 수 도메인)
--           내용V1000 = VARCHAR(1000) : ERR_MSG_CN (2000 은 표준도메인 부재 — 선존 V2000 은 미러 안 함)
--           일련번호B20 = BIGINT  : AUG_JOB_SN / DATA_AUG_SN
--   ※ IDMP_KEY 는 128 이지만 외부 계약(request_id ≤ 64)은 애플리케이션에서 강제한다.
--
-- JOB_STTS_CD 값(명세서 §3.2 상태머신 그대로):
--   RECEIVED(위탁 선기록/외부 접수) → RUNNING → SUCCEEDED | FAILED | CANCELED
--   ※ LS_DATA_AUG.AUG_PROC_STTS_CD(PENDING/ACCEPTED/REJECTED = 검수 결과 축)와는
--     서로 다른 코드 공간이다. 섞어 쓰지 않는다.
--
-- 멱등: IDMP_KEY UNIQUE — 같은 request_id 로 두 번 선기록될 수 없다(동시 위탁 race 차단).
--       외부(목/벤더)도 Idempotency-Key 재사용 시 기존 job 을 그대로 돌려준다.
--
-- 우리 소유 LS_* 테이블(관제 MNG_* 아님) — 협의 불요. PostgreSQL 표준 문법.
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_DATA_AUG_JOB (
    AUG_JOB_SN   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    DATA_AUG_SN  BIGINT       NOT NULL,                       -- LS_DATA_AUG FK (증강 결과 1건)
    JOB_SEQ      INT          NOT NULL,                       -- 분할 위탁 순서(1부터)
    IDMP_KEY     VARCHAR(128) NOT NULL,                       -- 우리가 발급한 request_id(=Idempotency-Key)
    OTSD_JOB_ID  VARCHAR(200),                                -- 외부가 202 로 발급한 job_id (접수 전 NULL)
    JOB_STTS_CD  VARCHAR(20)  NOT NULL,                       -- RECEIVED/RUNNING/SUCCEEDED/FAILED/CANCELED
    TOT_NOCS     INT          NOT NULL DEFAULT 0,             -- 이 job 이 담은 input_files 총건수
    ERR_CD       VARCHAR(50),                                 -- 실패 오류 코드(명세서 §3.3 또는 내부 코드)
    ERR_MSG_CN   VARCHAR(1000),                               -- 실패 오류 메시지(내부 경로/시크릿 미포함)
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AUG_JOB_SN),
    CONSTRAINT UK_LDAJ_IDMP_KEY UNIQUE (IDMP_KEY),
    CONSTRAINT FK_LDAJ_DATA_AUG FOREIGN KEY (DATA_AUG_SN)
        REFERENCES LS_DATA_AUG (DATA_AUG_SN) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LDAJ_AUG_SEQ ON LS_DATA_AUG_JOB (DATA_AUG_SN, JOB_SEQ);
CREATE INDEX IF NOT EXISTS IDX_LDAJ_OTSD_JOB_ID ON LS_DATA_AUG_JOB (OTSD_JOB_ID);

COMMENT ON TABLE  LS_DATA_AUG_JOB              IS '증강 외부 위탁 작업 — LS_DATA_AUG 1행이 input_files 100 상한으로 분할 위탁된 job 단위.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.DATA_AUG_SN  IS '증강 결과 식별자(LS_DATA_AUG FK).';
COMMENT ON COLUMN LS_DATA_AUG_JOB.JOB_SEQ      IS '분할 위탁 순서(1부터). 프레임 250장이면 1,2,3.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.IDMP_KEY     IS '저작도구가 발급한 request_id(=Idempotency-Key). 외부 job_id 가 아니다.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.OTSD_JOB_ID  IS '외부 시스템이 202 응답으로 발급한 job_id. 접수 전/실패 시 NULL.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.JOB_STTS_CD  IS '외부 작업 상태(RECEIVED/RUNNING/SUCCEEDED/FAILED/CANCELED). 검수 결과 축과 별개.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.TOT_NOCS     IS '이 job 으로 위탁한 입력 파일 총건수(최대 100).';
COMMENT ON COLUMN LS_DATA_AUG_JOB.ERR_CD       IS '실패 오류 코드. 위탁 실패를 조용히 삼키지 않기 위한 사유 기록.';
COMMENT ON COLUMN LS_DATA_AUG_JOB.ERR_MSG_CN   IS '실패 오류 메시지(요약). 절대경로/시크릿/스택트레이스 미포함.';
