-- =============================================================================
-- V141: 증강 위탁 파일 매핑 LS_DATA_AUG_JOB_FILE (Phase 7-D — 외부 산출 프레임 실반영)
--
-- 목적: 「생성형 AI API 연동명세서 v1.1」의 job 위탁 1건이 실어 보낸 input_files[] 각 항목이
--       <어느 프레임(LS_DATA_SRC)의 비식별 이미지였는지>를 위탁 시점에 못박고, 콜백으로 돌아온
--       results[].output_file_path 를 그 항목에 되붙인다. LS_DATA_AUG_JOB 1행 : N행.
--
-- 왜 필요한가 (이 표가 없으면 데이터 오염):
--   1) 계약상 results[] 항목에는 source_file_id 가 <없다>. 즉 "몇 번째 입력의 결과"라는
--      순서 정보만으로 대응시킬 수 있다. 그런데 위탁 시점의 순서↔프레임 대응이 어디에도
--      남아 있지 않으면, 결과 수신 시점에 프레임을 다시 정렬(frameNo asc, srcSn asc)해
--      재계산해야 한다. 위탁~콜백 사이에 프레임이 추가·삭제되면 그 재계산이 <조용히>
--      어긋나 다른 프레임의 증강본이 붙는다(무증상 오염).
--   2) 증강 1건은 100장 상한 때문에 여러 job 으로 쪼개져 <여러 번> 콜백이 온다. 마지막
--      콜백 시점에 앞 job 들의 산출 경로를 알아야 프레임셋을 통째로 채울 수 있으므로,
--      각 job 의 결과 경로를 수신 즉시 여기에 적재해 둔다.
--
-- 표준용어 준거(정본: docs/표준용어 — 사업표준단어/용어/도메인, 공공 공통표준단어):
--   단어) 증강=AUG, 작업=JOB, 파일=FILE, 순서=SEQ, 일련번호=SN,
--         결과=RSLT, 경로=PATH, 명=NM, 등록=REG, 수정=MDFCN, 일시=DT.
--   용어) 등록된 복합용어 우선 채택(단어 재조합보다 우선):
--         - 결과파일경로 = RSLT_FILE_PATH (사업표준용어 등록 — "증강 결과 파일 경로").
--           경로<명> 컬럼 관례(RAW_FILE_PATH_NM/SRC_FILE_PATH_NM, 명V500)에 맞춰
--           RSLT_FILE_PATH_NM 으로 쓴다.
--         - 원천일련번호 = SRC_SN (사업표준용어 등록, ERD-010 "프레임 단위 FK→LS_DATA_SRC.SRC_SN").
--           ※ 단어 '원천'의 약어는 ORGN 이지만 여기서는 <등록된 복합용어> SRC_SN 을 그대로 쓴다
--             (선존 LS_DATA_AUG.SRC_SN·LS_DATA_SRC.SRC_SN 과 동일 — 재조합 금지 원칙).
--   도메인) 일련번호B20 = BIGINT  : AUG_JOB_FILE_SN / AUG_JOB_SN / SRC_SN
--           수I11      = INTEGER : FILE_SEQ (순서 전용 도메인 부재 → V140 JOB_SEQ 선례와 동일)
--           명V500     = VARCHAR(500) : RSLT_FILE_PATH_NM
--                        (외부 계약 output_file_path 상한 500 과 일치)
--
-- 적재 시점:
--   FILE_SEQ / SRC_SN  — 위탁 <전> RECEIVED 선기록과 같은 트랜잭션(멱등키 확보와 동시).
--   RSLT_FILE_PATH_NM  — SUCCEEDED 콜백 수신 시. 수신 건수가 위탁 건수와 다르면 적재하지
--                        않고 job 을 FAILED(RESULT_COUNT_MISMATCH)로 종결한다(fail-closed).
--
-- 우리 소유 LS_* 테이블(관제 MNG_* 아님) — 협의 불요. PostgreSQL 표준 문법.
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_DATA_AUG_JOB_FILE (
    AUG_JOB_FILE_SN   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    AUG_JOB_SN        BIGINT       NOT NULL,   -- LS_DATA_AUG_JOB FK (위탁 job 1건)
    FILE_SEQ          INT          NOT NULL,   -- input_files[].sequence (증강 1건 전체에서 1부터)
    SRC_SN            BIGINT       NOT NULL,   -- 위탁한 비식별 프레임(LS_DATA_SRC)
    RSLT_FILE_PATH_NM VARCHAR(500),            -- 외부 산출 파일 경로(results[].output_file_path). 수신 전 NULL
    REG_DT            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AUG_JOB_FILE_SN),
    CONSTRAINT UK_LDAJF_JOB_FILE_SEQ UNIQUE (AUG_JOB_SN, FILE_SEQ),
    CONSTRAINT FK_LDAJF_AUG_JOB FOREIGN KEY (AUG_JOB_SN)
        REFERENCES LS_DATA_AUG_JOB (AUG_JOB_SN) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LDAJF_SRC_SN ON LS_DATA_AUG_JOB_FILE (SRC_SN);

COMMENT ON TABLE  LS_DATA_AUG_JOB_FILE                   IS '증강 위탁 파일 매핑 — 위탁 순서↔프레임(SRC_SN) 대응과 외부 산출 경로.';
COMMENT ON COLUMN LS_DATA_AUG_JOB_FILE.AUG_JOB_SN        IS '위탁 작업 식별자(LS_DATA_AUG_JOB FK).';
COMMENT ON COLUMN LS_DATA_AUG_JOB_FILE.FILE_SEQ          IS '위탁 입력 순서(input_files[].sequence). 증강 1건 전체에서 1부터 증가.';
COMMENT ON COLUMN LS_DATA_AUG_JOB_FILE.SRC_SN            IS '위탁한 비식별 프레임(LS_DATA_SRC) 식별자. 결과를 되붙일 대상.';
COMMENT ON COLUMN LS_DATA_AUG_JOB_FILE.RSLT_FILE_PATH_NM IS '외부가 반환한 증강 산출 이미지 경로. 수신 전 NULL, 건수 불일치 시 미적재.';
