-- ============================================================
-- V34 — PJT_ID 컬럼 전면 제거 (프로젝트 개념 자체 제거)
--
-- 본 마이그레이션은 LS_PJT 테이블은 남기고 (V35 에서 DROP),
-- 다른 9개 테이블의 PJT_ID 컬럼 + 관련 PK/UK/INDEX 만 정리한다.
--
-- 인덱스/UK 이름은 V1__phase2_base_schema.sql, V8__add_ls_data_set.sql,
-- V14__create_ls_pjt_task_event_log.sql, V31__create_ls_label.sql 의
-- 실제 정의와 일치하도록 작성됨 (PostgreSQL).
--
-- PostgreSQL 전환:
--   - UNIQUE/PK 는 named CONSTRAINT → ALTER TABLE ... DROP CONSTRAINT.
--   - 인라인 PRIMARY KEY (...) 는 PG 가 <table>_pkey 로 자동 명명.
--   - 일반 INDEX 는 스키마 전역 객체 → DROP INDEX <name> / CREATE INDEX.
-- ============================================================

-- LS_LABEL: UK (PJT_ID, LABEL_NM) → UK (LABEL_NM), 인덱스(PJT_ID,USE_YN,SORT_SEQ) → (USE_YN,SORT_SEQ)
ALTER TABLE LS_LABEL DROP CONSTRAINT UK_LS_LABEL_NAME;
DROP INDEX IF EXISTS IDX_LS_LABEL_PJT_USE;
ALTER TABLE LS_LABEL ADD CONSTRAINT UK_LS_LABEL_NAME UNIQUE (LABEL_NM);
CREATE INDEX IDX_LS_LABEL_USE ON LS_LABEL (USE_YN, SORT_SEQ);
ALTER TABLE LS_LABEL DROP COLUMN PJT_ID;

-- LS_PJT_DATA_MPNG: PK (PJT_ID, RAW_DATA_ID) → PK (RAW_DATA_ID)
ALTER TABLE LS_PJT_DATA_MPNG DROP CONSTRAINT LS_PJT_DATA_MPNG_PKEY;
ALTER TABLE LS_PJT_DATA_MPNG ADD PRIMARY KEY (RAW_DATA_ID);
ALTER TABLE LS_PJT_DATA_MPNG DROP COLUMN PJT_ID;

-- LS_PJT_DATA_STTS: PK (PJT_ID, RAW_DATA_ID) → PK (RAW_DATA_ID)
ALTER TABLE LS_PJT_DATA_STTS DROP CONSTRAINT LS_PJT_DATA_STTS_PKEY;
ALTER TABLE LS_PJT_DATA_STTS ADD PRIMARY KEY (RAW_DATA_ID);
ALTER TABLE LS_PJT_DATA_STTS DROP COLUMN PJT_ID;

-- LS_PJT_USER_AUTHRT: UK (PJT_ID, RAW_DATA_ID, USER_NO, TASK_TYPE_CD) → (RAW_DATA_ID, USER_NO, TASK_TYPE_CD)
ALTER TABLE LS_PJT_USER_AUTHRT DROP CONSTRAINT UK_LS_PJT_USER_AUTHRT;
ALTER TABLE LS_PJT_USER_AUTHRT ADD CONSTRAINT UK_LS_PJT_USER_AUTHRT UNIQUE (RAW_DATA_ID, USER_NO, TASK_TYPE_CD);
ALTER TABLE LS_PJT_USER_AUTHRT DROP COLUMN PJT_ID;

-- LS_PJT_USER_AUTHRT_HSTRY: 카테고리 컬럼 제거 (인덱스 영향 없음)
ALTER TABLE LS_PJT_USER_AUTHRT_HSTRY DROP COLUMN PJT_ID;

-- LS_PJT_META: PK (PJT_ID, META_KEY) → PK (META_KEY)
ALTER TABLE LS_PJT_META DROP CONSTRAINT LS_PJT_META_PKEY;
ALTER TABLE LS_PJT_META ADD PRIMARY KEY (META_KEY);
ALTER TABLE LS_PJT_META DROP COLUMN PJT_ID;

-- LS_PJT_DDLN: PK (PJT_ID, DDLN_SEQ) → PK (DDLN_SEQ)
ALTER TABLE LS_PJT_DDLN DROP CONSTRAINT LS_PJT_DDLN_PKEY;
ALTER TABLE LS_PJT_DDLN ADD PRIMARY KEY (DDLN_SEQ);
ALTER TABLE LS_PJT_DDLN DROP COLUMN PJT_ID;

-- LS_PJT_TASK_EVENT_LOG: 인덱스 (PJT_ID, RAW_DATA_ID, OCCURRED_AT) → (RAW_DATA_ID, OCCURRED_AT)
DROP INDEX IF EXISTS IDX_PJT_TASK_EVENT_VIDEO;
CREATE INDEX IDX_LS_PJT_TASK_EVENT_LOG_RAW ON LS_PJT_TASK_EVENT_LOG (RAW_DATA_ID, OCCURRED_AT);
ALTER TABLE LS_PJT_TASK_EVENT_LOG DROP COLUMN PJT_ID;

-- LS_DATA_SET: 인덱스(PJT_ID, REGISTERED_AT) + 컬럼 제거
DROP INDEX IF EXISTS IDX_LS_DATA_SET_PJT;
ALTER TABLE LS_DATA_SET DROP COLUMN PJT_ID;
