-- V10: BATCH_QUEUED 상태 코드 추가 (마킹 완료 → 배치 큐 적재)
INSERT INTO CM_CODE (GROUP_CODE, CODE, CODE_NM, CODE_DC, USE_YN, SORT_ORDR)
SELECT 'DATA_STTS_CD', 'BATCH_QUEUED', '배치 대기', '마킹 완료 후 배치 큐 적재됨', 'Y', 6
WHERE NOT EXISTS (SELECT 1 FROM CM_CODE WHERE GROUP_CODE = 'DATA_STTS_CD' AND CODE = 'BATCH_QUEUED');
