-- V58: LS_DATA_LBL_HSTRY 생성 — 라벨 삭제 이력 테이블.
--
-- 배경: 커밋 fef2a7d 가 LsDataLblHstry 엔티티 + Repository + 비식별 신고 시 삭제 이력
-- 기록 로직을 추가했으나 CREATE TABLE DDL 마이그레이션을 동반하지 않아
-- POST /v1/labels/{srcSn}/deident-report 호출 시 'relation "ls_data_lbl_hstry" does not
-- exist' 로 500 이 발생했다. (V6 는 no-op 빈 파일이라 테이블 미생성)
--
-- 정합: kr.co.cudo.authoring.version.entity.LsDataLblHstry 와 컬럼명/타입/NULL/PK 1:1.
-- PostgreSQL 표준 문법 (Testcontainers postgres:16 + JPA ddl-auto=validate 대상).
--
-- FK 정책 — 의도적으로 LS_DATA_LBL(LBL_SN) FK 미설정:
--   비식별 신고 시 "이력 기록 직후 라벨 본문 일괄 삭제" 가 같은 트랜잭션에서 일어난다
--   (DeidentReportService.deleteAllVideoLabels). LBL_SN FK 가 있으면 라벨 삭제가
--   이력 row 를 위반(또는 cascade 로 동반 삭제)하여 "삭제된 라벨의 이력 보존" 목적이
--   깨진다. 따라서 LBL_SN 은 FK 없는 식별자 보존 컬럼으로 둔다.
--   SRC_SN(프레임) 은 라벨 삭제 후에도 존속하므로 조회 인덱스만 둔다.
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_DATA_LBL_HSTRY (
    LBL_HSTRY_SN  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,  -- PK (IDENTITY)
    LBL_SN        BIGINT,                                                  -- 삭제된 라벨 LS_DATA_LBL.LBL_SN (FK 미설정 — 위 주석)
    SRC_SN        BIGINT       NOT NULL,                                   -- 라벨이 속한 프레임 LS_DATA_SRC.SRC_SN
    REGISTERED_AT TIMESTAMP    NOT NULL,                                   -- 이력 기록 일시
    PRIMARY KEY (LBL_HSTRY_SN)
);

-- 조회 패턴: findBySrcSnOrderByRegisteredAtDesc — 프레임 단위 이력 최신순.
CREATE INDEX IF NOT EXISTS IDX_LDLH_SRC ON LS_DATA_LBL_HSTRY (SRC_SN, REGISTERED_AT DESC);

-- 라벨 단위 역추적용 (어떤 라벨이 언제 삭제되었는가).
CREATE INDEX IF NOT EXISTS IDX_LDLH_LBL ON LS_DATA_LBL_HSTRY (LBL_SN);
