-- =============================================================================
-- V98: 통합 메타 복제 outbox LS_META_REPL_OUTBOX
--
-- 목적: control DB(SoT)에 동결된 LS_DATASET_VIDEO_META 스냅샷을 포털 DB(물리 분리)로
--       at-least-once 단방향 복제하기 위한 outbox 테이블. APPROVED 트랜잭션에서 스냅샷과
--       함께 커밋되고(원자), 별도 워커(Phase 3)가 PENDING 을 폴링해 포털로 push 한 뒤 DONE 처리한다.
--
-- 멱등키: (RAW_SN, SNPSHT_HASH) — 포털 upsert 시 중복 복제 무해(재시도 안전).
-- 상태: PENDING(대기) / DONE(완료) / DEAD(재시도 초과 dead-letter).
--
-- PostgreSQL 표준 문법.
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_META_REPL_OUTBOX (
    OUTBOX_SN    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RAW_SN       BIGINT       NOT NULL,
    SNPSHT_HASH  VARCHAR(64)  NOT NULL,
    PAYLOAD      TEXT,
    STATUS       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    RETRY_CNT    INT          NOT NULL DEFAULT 0,
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROC_DT      TIMESTAMP,

    PRIMARY KEY (OUTBOX_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_META_REPL_OUTBOX_STATUS
    ON LS_META_REPL_OUTBOX (STATUS, REG_DT);
