package kr.co.cudo.authoring.common.migration;

import kr.co.cudo.authoring.support.PostgresTestContainer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * V5(비표준 컬럼 11종 표준용어 개명) 마이그레이션 자체의 성질 검증 — 멱등 · 데이터 보존 · 폭 축소 fail-closed.
 *
 * <p><b>왜 별도 스키마에서 돌리나</b>: 애플리케이션 컨텍스트가 붙는 {@code klid_at} 은 이미 V5 가 적용된
 * 상태라 <b>개명 전</b> 형상을 관측할 수 없다. 여기서는 전용 스크래치 스키마에 개명 전 형상을 그대로 세우고
 * 실제 V5 스크립트 원문을 그 스키마의 {@code search_path} 에서 실행한다 — V5 가 카탈로그 조회를
 * {@code current_schema()}/{@code to_regclass} 로 스코프하기 때문에 그대로 동작한다.
 *
 * <p>커넥션은 Hikari 풀이 아니라 {@link DriverManager} 로 직접 연다. 풀 커넥션에 {@code search_path} 를
 * 걸면 반납 후 다른 테스트에 그 설정이 새어 나간다.
 *
 * @req R2
 */
class V5StandardColumnRenameGuardIT {

    private static final Path V5_SQL = Paths.get(
            "src/main/resources/db/migration/V5__rename_queue_outbox_columns_to_std.sql");

    /** 테스트마다 다른 스키마를 쓴다 — 같은 컨테이너를 공유하므로 이름이 겹치면 서로를 지운다. */
    private static final AtomicInteger SCHEMA_SEQ = new AtomicInteger();

    private static final String OLD_QUE_DDL = """
            CREATE TABLE ls_clip_schedule_que (
                que_sn        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                raw_sn        bigint NOT NULL,
                job_type      character varying(32) NOT NULL,
                status        character varying(16) DEFAULT 'PENDING' NOT NULL,
                retry_count   integer DEFAULT 0 NOT NULL,
                registered_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                started_at    timestamp without time zone,
                completed_at  timestamp without time zone,
                last_error    character varying(2000)
            )""";

    private static final String OLD_OUTBOX_DDL = """
            CREATE TABLE ls_meta_repl_outbox (
                outbox_sn   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                raw_sn      bigint NOT NULL,
                snpsht_hash character varying(64) NOT NULL,
                payload     text,
                status      character varying(20) DEFAULT 'PENDING' NOT NULL,
                retry_cnt   integer DEFAULT 0 NOT NULL,
                reg_dt      timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                proc_dt     timestamp without time zone
            )""";

    private String schema;
    private Connection conn;

    @BeforeEach
    void setUp() throws SQLException {
        schema = "v5_guard_" + SCHEMA_SEQ.incrementAndGet();
        conn = DriverManager.getConnection(
                PostgresTestContainer.INSTANCE.getJdbcUrl(),
                PostgresTestContainer.INSTANCE.getUsername(),
                PostgresTestContainer.INSTANCE.getPassword());
        exec("CREATE SCHEMA " + schema);
        exec("SET search_path TO " + schema);
        exec(OLD_QUE_DDL);
        exec(OLD_OUTBOX_DDL);
    }

    @AfterEach
    void tearDown() throws SQLException {
        if (conn != null) {
            try (Statement st = conn.createStatement()) {
                st.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            } finally {
                conn.close();
            }
        }
    }

    // ------------------------------------------------------------------ 멱등

    @Test
    @DisplayName("V5를_두_번_적용해도_안전하다")
    void migrationIsIdempotent() throws Exception {
        // given — 개명 전 형상 + 행 1건
        seedOutbox("hash-a", "{\"k\":1}", "PENDING");

        // when — 두 번 적용
        applyV5();
        applyV5();

        // then — 새 이름만 남고 두 번째 적용이 아무것도 깨지 않는다
        assertThat(columnExists("ls_meta_repl_outbox", "stts_cd")).isTrue();
        assertThat(columnExists("ls_meta_repl_outbox", "status")).isFalse();
        assertThat(columnExists("ls_clip_schedule_que", "job_type_cd")).isTrue();
        assertThat(columnExists("ls_clip_schedule_que", "job_type")).isFalse();
        assertThat(scalarLong("SELECT count(*) FROM ls_meta_repl_outbox")).isEqualTo(1L);
    }

    // ------------------------------------------------------------------ 데이터 보존

    @Test
    @DisplayName("기존_아웃박스_행의_페이로드와_상태가_개명_후에도_보존된다")
    void existingOutboxRowsSurviveRename() throws Exception {
        // given — RENAME 이 아니라 재생성이면 사라질 행들
        String payload = "{\"rawSn\":42,\"meta\":\"보존되어야 한다\"}";
        seedOutbox("hash-keep-1", payload, "PENDING");
        seedOutbox("hash-keep-2", null, "DONE");

        // when
        applyV5();

        // then — 행수·값이 그대로다
        assertThat(scalarLong("SELECT count(*) FROM ls_meta_repl_outbox")).isEqualTo(2L);
        assertThat(scalarString(
                "SELECT payload_cn FROM ls_meta_repl_outbox WHERE snpsht_hash = 'hash-keep-1'"))
                .isEqualTo(payload);
        assertThat(scalarString(
                "SELECT stts_cd FROM ls_meta_repl_outbox WHERE snpsht_hash = 'hash-keep-1'"))
                .isEqualTo("PENDING");
        assertThat(scalarString(
                "SELECT stts_cd FROM ls_meta_repl_outbox WHERE snpsht_hash = 'hash-keep-2'"))
                .isEqualTo("DONE");
        assertThat(scalarString(
                "SELECT payload_cn FROM ls_meta_repl_outbox WHERE snpsht_hash = 'hash-keep-2'"))
                .isNull();
    }

    // ------------------------------------------------------------------ 폭 축소 fail-closed

    @Test
    @DisplayName("작업유형이_목표_폭을_넘으면_마이그레이션이_중단된다")
    void abortsWhenJobTypeExceedsTargetWidth() throws Exception {
        // given — 목표 폭 20 을 넘는 값 2건(21자·25자). 조용히 자르면 큐 작업 유형이 훼손된다.
        //   건수·최장 길이를 구분해 세는지 보려고 길이를 다르게 둔다.
        String longest = "B".repeat(25);
        exec("INSERT INTO ls_clip_schedule_que (raw_sn, job_type) VALUES (1, '" + "A".repeat(21) + "')");
        exec("INSERT INTO ls_clip_schedule_que (raw_sn, job_type) VALUES (2, '" + longest + "')");

        // when / then — 중단되고, DO 블록은 원자적이라 개명도 남지 않는다
        assertThatThrownBy(this::applyV5)
                .isInstanceOf(SQLException.class)
                .satisfies(e -> assertGuardMessage(e, "ls_clip_schedule_que.job_type_cd", 20, 2, 25, longest));
        assertThat(columnExists("ls_clip_schedule_que", "job_type")).isTrue();
        assertThat(columnExists("ls_clip_schedule_que", "job_type_cd")).isFalse();
        assertThat(columnExists("ls_meta_repl_outbox", "status")).isTrue();
    }

    @Test
    @DisplayName("상태값이_목표_폭을_넘으면_마이그레이션이_중단된다")
    void abortsWhenOutboxStatusExceedsTargetWidth() throws Exception {
        // given — 17자(목표 폭 16 초과)
        String tooLong = "S".repeat(17);
        exec("INSERT INTO ls_meta_repl_outbox (raw_sn, snpsht_hash, status) VALUES (1, 'h', '"
                + tooLong + "')");

        // when / then
        assertThatThrownBy(this::applyV5)
                .isInstanceOf(SQLException.class)
                .satisfies(e -> assertGuardMessage(e, "ls_meta_repl_outbox.stts_cd", 16, 1, 17, tooLong));
        assertThat(columnExists("ls_meta_repl_outbox", "status")).isTrue();
        assertThat(columnExists("ls_meta_repl_outbox", "stts_cd")).isFalse();
    }

    /**
     * 중단 사유가 <b>이 가드가 만든 것</b>인지 확인한다 — 아무 SQLException 이나 통과하면 가드의 존재
     * 이유가 사라진다. 헤더가 이 가드의 근거로 든 것이 정확히 "PG 원문 오류만으로는 무엇이 몇 건
     * 걸렸는지 알 수 없다" 이므로, 그 유일한 산출물(대상·목표 폭·초과 건수·최장 길이)을 단언한다.
     *
     * <p>PG 가 스스로 내는 {@code value too long for type character varying(N)} 로는 통과하지 못한다.
     *
     * <p>동시에 <b>실제 데이터 값이 새지 않는지</b>도 단언한다(CWE-209) — 헤더가 "건수와 최장 길이만
     * 싣는다"를 설계 의도로 명시했고, 그 의도를 지키는지는 여기서만 확인된다.
     */
    private void assertGuardMessage(Throwable e, String qualifiedColumn, int targetLen,
                                    long overCount, int maxLen, String secretValue) {
        String msg = String.valueOf(e.getMessage());
        assertThat(msg)
                .as("가드가 만든 중단 사유여야 한다 — PG 원문 오류(value too long)로는 통과하지 못한다")
                .contains(qualifiedColumn)
                .contains(targetLen + "자")
                .contains("초과 행 " + overCount + "건")
                .contains("최장 " + maxLen + "자");
        assertThat(msg)
                .as("초과한 값 자체를 메시지에 실으면 로그로 새어 나간다 (CWE-209)")
                .doesNotContain(secretValue);
    }

    @Test
    @DisplayName("목표_폭_이하_값은_그대로_통과한다")
    void acceptsValuesWithinTargetWidth() throws Exception {
        // given — 경계값(20자 / 16자)
        exec("INSERT INTO ls_clip_schedule_que (raw_sn, job_type) VALUES (1, '" + "A".repeat(20) + "')");
        exec("INSERT INTO ls_meta_repl_outbox (raw_sn, snpsht_hash, status) VALUES (1, 'h', '"
                + "S".repeat(16) + "')");

        // when
        applyV5();

        // then
        assertThat(charMaxLength("ls_clip_schedule_que", "job_type_cd")).isEqualTo(20);
        assertThat(charMaxLength("ls_meta_repl_outbox", "stts_cd")).isEqualTo(16);
    }

    // ------------------------------------------------------------------ 내부

    private void applyV5() throws IOException, SQLException {
        assertThat(Files.exists(V5_SQL)).as("V5 마이그레이션 파일이 존재해야 한다 (%s)", V5_SQL).isTrue();
        exec(Files.readString(V5_SQL));
    }

    private void seedOutbox(String hash, String payload, String status) throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.executeUpdate("INSERT INTO ls_meta_repl_outbox (raw_sn, snpsht_hash, payload, status) VALUES "
                    + "(1, '" + hash + "', "
                    + (payload == null ? "NULL" : "'" + payload.replace("'", "''") + "'")
                    + ", '" + status + "')");
        }
    }

    private void exec(String sql) throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute(sql);
        }
    }

    private boolean columnExists(String table, String column) throws SQLException {
        return scalarLong("SELECT count(*) FROM information_schema.columns"
                + " WHERE table_schema = current_schema()"
                + " AND table_name = '" + table + "' AND column_name = '" + column + "'") > 0;
    }

    private int charMaxLength(String table, String column) throws SQLException {
        return (int) scalarLong("SELECT character_maximum_length FROM information_schema.columns"
                + " WHERE table_schema = current_schema()"
                + " AND table_name = '" + table + "' AND column_name = '" + column + "'");
    }

    private long scalarLong(String sql) throws SQLException {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getLong(1) : 0L;
        }
    }

    private String scalarString(String sql) throws SQLException {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }
}
