-- =============================================================================
-- V107: 포털 전용 업로드(이미지/영상) + 수동 라벨링 데이터 기반
--
-- 목적: 포털 사용자가 자기 자산(이미지/영상)을 직접 업로드하고 수동 라벨링하는 기능의
--       데이터 골격. 저작도구 본 파이프라인(관제 학습용 적재)과 분리된 포털 전용 경로다.
--       본 Phase 는 스키마 + 엔티티/리포지토리 골격만 생성(Controller/Service 는 후속 Phase).
--
-- 표준 물리명(glossary 확정): 업로드=ULD, 프레임=FRME, 크기=SZ, 사유=RSN, 라벨=LBL,
--       포털=PORTAL(기존 관례), 원본=ORGNL. (구 드리프트 FRM_NO 등 답습 금지 → FRME_NO 사용.)
--
-- 소유권/격리:
--   - 3 테이블 모두 PORTAL_USER_NO 소유자 스코프. 리포지토리는 소유자 스코프 파생 쿼리만 노출.
--   - 프레임/라벨은 업로드(ULD) 삭제 시 ON DELETE CASCADE 로 연쇄 정리.
--
-- 표준 정합:
--   - 감사 시각 REG_DT / MDFCN_DT 는 TIMESTAMP DEFAULT CURRENT_TIMESTAMP (기존 LS_* 관례).
--   - IDENTITY 는 GENERATED BY DEFAULT AS IDENTITY (V97 등과 동일).
--
-- PostgreSQL 표준 문법 (MariaDB 고유 문법 미사용).
-- =============================================================================

-- ============================================================
-- LS_PORTAL_ULD : 포털 업로드 마스터 (이미지 1건 또는 영상 1건)
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD (
    ULD_SN         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PORTAL_USER_NO VARCHAR(100) NOT NULL,
    ULD_TYPE_CD    VARCHAR(16)  NOT NULL,        -- IMAGE | VIDEO
    ORGNL_FILE_NM  VARCHAR(255),                 -- 사용자 업로드 원본 파일명
    FILE_PATH_NM   VARCHAR(500),                 -- 저장 경로
    FILE_SZ        BIGINT,                        -- 파일 크기(byte)
    MIME_TYPE_NM   VARCHAR(100),
    ULD_STTS_CD    VARCHAR(16)  NOT NULL,        -- UPLOADED | PROCESSING | READY | FAILED
    VDO_LEN_SEC    DOUBLE PRECISION,             -- 영상만: 길이(초)
    FPS            DOUBLE PRECISION,             -- 영상만: 프레임레이트
    FRME_CNT       INT,                          -- 영상만: 추출 프레임 수
    FAIL_RSN_CN    TEXT,                          -- 실패 사유(FAILED 시)
    REG_DT         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_USER_REG
    ON LS_PORTAL_ULD (PORTAL_USER_NO, REG_DT);

-- 고착 자산 스캔(findStuck: ULD_STTS_CD IN (...) AND MDFCN_DT < cutoff) 풀스캔 방지.
CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_STTS_MDFCN
    ON LS_PORTAL_ULD (ULD_STTS_CD, MDFCN_DT);

-- ============================================================
-- LS_PORTAL_ULD_FRME : 업로드 파생 프레임 (이미지=1행, 영상=추출 N행)
--   - PK 는 SEQUENCE 채번(Hibernate pooled, allocationSize=50) — 영상당 최대 2000행
--     일괄 INSERT 시 JDBC batching 활성화(IDENTITY 는 batching 무효화되므로 미사용).
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS LS_PORTAL_ULD_FRME_SEQ INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD_FRME (
    ULD_FRME_SN  BIGINT       NOT NULL,
    ULD_SN       BIGINT       NOT NULL,
    FRME_NO      INT          NOT NULL,          -- 업로드 내 프레임 순번(0-base)
    FILE_PATH_NM VARCHAR(500) NOT NULL,
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_FRME_SN),
    CONSTRAINT FK_LS_PORTAL_ULD_FRME_ULD
        FOREIGN KEY (ULD_SN) REFERENCES LS_PORTAL_ULD (ULD_SN) ON DELETE CASCADE,
    CONSTRAINT UK_LS_PORTAL_ULD_FRME UNIQUE (ULD_SN, FRME_NO)
);

-- ============================================================
-- LS_PORTAL_ULD_LBL : 프레임별 수동 라벨 (BBOX | POLYGON)
-- ============================================================
CREATE TABLE IF NOT EXISTS LS_PORTAL_ULD_LBL (
    ULD_LBL_SN     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PORTAL_USER_NO VARCHAR(100) NOT NULL,
    ULD_SN         BIGINT       NOT NULL,
    ULD_FRME_SN    BIGINT       NOT NULL,
    LBL_TYPE_CD    VARCHAR(16)  NOT NULL,        -- BBOX | POLYGON
    LBL_NM         VARCHAR(80),
    POINT_CN       TEXT,                          -- 좌표(JSON 문자열)
    REG_DT         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ULD_LBL_SN),
    CONSTRAINT FK_LS_PORTAL_ULD_LBL_FRME
        FOREIGN KEY (ULD_FRME_SN) REFERENCES LS_PORTAL_ULD_FRME (ULD_FRME_SN) ON DELETE CASCADE,
    -- 반정규화 컬럼 ULD_SN 정합성을 DB 로 보장 + 업로드 삭제 시 연쇄 정리
    CONSTRAINT FK_LS_PORTAL_ULD_LBL_ULD
        FOREIGN KEY (ULD_SN) REFERENCES LS_PORTAL_ULD (ULD_SN) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_LBL_USER_ULD
    ON LS_PORTAL_ULD_LBL (PORTAL_USER_NO, ULD_SN);

-- replace-all 삭제/조회(deleteAllByUldFrmeSnAndPortalUserNo)를 커버하는 복합 인덱스
CREATE INDEX IF NOT EXISTS IDX_LS_PORTAL_ULD_LBL_FRME
    ON LS_PORTAL_ULD_LBL (ULD_FRME_SN, PORTAL_USER_NO);

-- ============================================================
-- 시스템 설정 시드: 포털 업로드 영상 프레임 추출 간격(초)
--   - 화이트리스트(ConfigKeys.ALLOWED) 등록 키. NUMBER, 기본 5초, 범위 1~600.
--   - 컬럼명은 V61 표준화 후 STNG_KEY / STNG_VALUE / STNG_TYPE_CD 를 사용한다.
--   - 이미 존재하면 NOOP (ON CONFLICT DO NOTHING) — 재실행 안전.
-- ============================================================
INSERT INTO LS_SYSTEM_CONFIG (STNG_KEY, STNG_VALUE, STNG_TYPE_CD, EXPLN, MDFR_ID) VALUES
    ('portal.upload.frame-interval-sec', '5', 'NUMBER', '포털 업로드 영상 프레임 추출 간격(초, 1~600)', 'SYSTEM')
ON CONFLICT (STNG_KEY) DO NOTHING;
