-- =============================================================================
-- V112: 배치 재시도 대기 LS_BAT_RTY_WTNG (B2)
--
-- 목적: 배치 파이프라인 실패 영상의 재시도 항목을 DB 로 영속화한다. 기존 in-memory
--       ConcurrentHashMap 큐는 실패 등록 노드 ≠ 재시도 발화 노드일 때(2노드 Active-Active)
--       재시도가 조용히 유실되던 결함이 있었다(CLAUDE.md 배포 토폴로지 정합).
--
-- 표준용어 준거(사업 program 사전 = 진실원): 배치=BAT, 재시도=RTY, 횟수=NMTM, 최대=MAX,
--       오류=ERR, 대기=WTNG, 예정=PRNMNT. "다음(NEXT)" 표준 부재 → 재시도 예정 일시(RTY_PRNMNT_DT)
--       로 대체, "큐(QUEUE)" 표준 부재 → 대기(WTNG)로 대체. gov 사전의 BTCH/RTRY 는 미채택.
--       (선존 테이블 LS_CONTROL_NOTIFY_FALLBACK 의 RTRY_* 는 드리프트라 미러하지 않는다.)
--
-- 상태(STTS_CD): PENDING(재시도 대기) / RETRYING(폴링 노드가 클레임한 처리중) /
--       EXHAUSTED(최대 재시도 초과 — 삭제 대신 이력 보존).
--
-- 2노드 동시 폴링 안전: 폴링 노드는 STTS_CD='PENDING' 행을 조건부 원자 UPDATE
--       (PENDING→RETRYING)로 클레임하므로 DB 가 동시 UPDATE 를 직렬화해 1건만 성공한다.
--
-- 멱등: RAW_SN UNIQUE — 영상 1건당 재시도 항목 1행. 성공(clear) 시 행 삭제.
--
-- PK 네이밍: 기존 LS_* 관례(엔티티 의미 명사 + _SN — DEIDENT_REPORT_SN/LABEL_VERSION_SN/
--       WORK_LOCK_SN)를 따라 상태 한정어(WTNG)를 제외한 BAT_RTY_SN 을 사용한다.
--
-- PostgreSQL 표준 문법.
-- =============================================================================

CREATE TABLE LS_BAT_RTY_WTNG (
    BAT_RTY_SN      BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RAW_SN          BIGINT        NOT NULL,                          -- 영상 단위 식별자
    RTY_NMTM        INT           NOT NULL DEFAULT 0,                -- 재시도 횟수
    MAX_RTY_NMTM    INT           NOT NULL DEFAULT 3,                -- 최대 재시도 횟수
    STTS_CD         VARCHAR(16)   NOT NULL DEFAULT 'PENDING',        -- 상태 코드
    RTY_PRNMNT_DT   TIMESTAMP,                                       -- 재시도 예정 일시
    LAST_ERR_MSG_CN VARCHAR(2000),                                   -- 마지막 오류(ERR) 메시지
    REG_DT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BAT_RTY_SN),
    CONSTRAINT UK_LBRW_RAW_SN UNIQUE (RAW_SN)
);

CREATE INDEX IDX_LBRW_STATUS ON LS_BAT_RTY_WTNG (STTS_CD, RTY_PRNMNT_DT);
