-- V116: 해상도 파생영상 라벨 매핑 테이블 + LS_RESOLUTION_EXPORT 파생 RAW 참조 컬럼 — Phase 2 (RQ-SFR-06-03 파생영상).
-- (V115 는 선행 restructure_lbl_hstry 가 점유 — origin/main 0a6f07b 충돌 해소 반영해 V116 로 재넘버링.)
--
-- Phase 2 는 원본(APPROVED·비식별) 영상에서 목표 해상도의 새 파생영상(RAW_SN)을 만들고
-- 원본 라벨 좌표를 scaleX/scaleY 로 리스케일해 복사한다. 좌표 재계산(COORD_RECALC_YN='Y')과
-- 배율을 추적하기 위한 전용 매핑 테이블을 둔다. LS_DATA_AUG_LBL_MAP 은 DATA_AUG_SN NOT NULL 이라
-- 재사용하지 않는다(증강 이력/통계 오염 방지).
--
-- PostgreSQL 표준 문법 + 멱등(IF NOT EXISTS). LS_* 전용 테이블만 신설한다.

CREATE TABLE IF NOT EXISTS LS_RESOLUTION_LBL_MAP (
    RES_LBL_MAP_SN    BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RES_EXPORT_SN     BIGINT        NOT NULL,               -- LS_RESOLUTION_EXPORT.RES_EXPORT_SN (파생 산출 추적 FK)
    ORGNL_DATA_LBL_SN BIGINT        NULL,                   -- 원본 라벨 LS_DATA_LBL.LBL_SN
    DATA_LBL_SN       BIGINT        NOT NULL,               -- 파생 라벨 LS_DATA_LBL.LBL_SN (좌표 스케일 복사본)
    COORD_RECALC_YN   VARCHAR(1)    NOT NULL DEFAULT 'Y',   -- 좌표 재계산 여부 (해상도 변경이므로 항상 'Y')
    SCALE_X           DECIMAL(10,6) NULL,                   -- x축 배율 (=목표W/원본W)
    SCALE_Y           DECIMAL(10,6) NULL,                   -- y축 배율 (=목표H/원본H)
    REG_ID            VARCHAR(30)   NULL,                   -- 등록자(REVIEWER) 식별자
    REG_DT            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RES_LBL_MAP_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_RES_LBL_MAP_EXPORT ON LS_RESOLUTION_LBL_MAP (RES_EXPORT_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_RES_LBL_MAP_LBL    ON LS_RESOLUTION_LBL_MAP (DATA_LBL_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_RES_LBL_MAP_ORGNL  ON LS_RESOLUTION_LBL_MAP (ORGNL_DATA_LBL_SN);

-- 파생영상(RAW_SN) 역참조 컬럼 — Phase 1 은 EXPORT 1행만 기록했으나 Phase 2 는 새 RAW 를 만든다.
ALTER TABLE LS_RESOLUTION_EXPORT ADD COLUMN IF NOT EXISTS NEW_RAW_SN BIGINT;
CREATE INDEX IF NOT EXISTS IDX_LRE_NEW_RAW ON LS_RESOLUTION_EXPORT (NEW_RAW_SN);
