-- =============================================================================
-- V127: 이벤트 어노테이션(event_annotation, VLM VQA/CoT) 저장 테이블
--
-- 목적: 외부 VLM 이 생성한 event_annotation(질의응답 + Chain-of-Thought + evidence)
--       payload 를 영상(RAW_SN) 단위로 저장하고, 검토(REVIEWER) 상태를 관리한다.
--       LS_DATA_META(값 K/V) 와 별개로, 구조화된 event_annotation JSON 본문을
--       jsonb 컬럼(ANNO_CN)에 원문 그대로 보존한다.
--
-- 표준용어/표준도메인 정합(Critical):
--   - 테이블: LS_EVNT_ANNO(이벤트 EVNT + 어노테이션 ANNO), LS_EVNT_ANNO_REVIEW.
--     (구 ANOT 는 비표준 — 사용하지 않음)
--   - ANNO_CN(어노테이션 ANNO + 내용 CN): payload 본문, 타입 jsonb
--     (KLID-PT ANNO_SMRY 선례 준용, 길이 제한 없음).
--   - RVW_STTS_CD / META_TYPE_CD: 코드값 표준 도메인 VARCHAR(20) (32 드리프트 금지).
--   - 감사 ID(REG_ID/MDFCN_ID/RVW_ID): 식별자 표준 도메인 VARCHAR(30) (V108 정합).
--   - RJCT_RSN: VARCHAR(4000).
--   - VER(버전, 낙관적 잠금): BIGINT NOT NULL DEFAULT 0 — LS_RAW_DATA_STATUS.VER(V61) /
--     LS_PORTAL_TUS_ULD.VER(V111) 선례와 동일. 동시 승인/반려 상태전이 Race Condition 방어(CWE-362).
--
-- PostgreSQL 표준 문법.
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_EVNT_ANNO (
    EVNT_ANNO_SN BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RAW_SN       BIGINT       NOT NULL,
    ANNO_CN      JSONB        NOT NULL,
    REG_ID       VARCHAR(30)  NULL,
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID     VARCHAR(30)  NULL,
    MDFCN_DT     TIMESTAMP    NULL,
    PRIMARY KEY (EVNT_ANNO_SN),
    CONSTRAINT FK_LS_EVNT_ANNO_RAW FOREIGN KEY (RAW_SN) REFERENCES LS_DATA_RAW (RAW_SN),
    -- 영상당 event_annotation 1건 전제(UC). 다건 필요 시 EVNT_SEQ 추가 후 UK 재편.
    CONSTRAINT UK_LS_EVNT_ANNO_RAW UNIQUE (RAW_SN)
);

CREATE TABLE IF NOT EXISTS LS_EVNT_ANNO_REVIEW (
    RVW_SN       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    EVNT_ANNO_SN BIGINT       NOT NULL,
    RVW_STTS_CD  VARCHAR(20)  NOT NULL,
    META_TYPE_CD VARCHAR(20)  NULL,
    RVW_ID       VARCHAR(30)  NULL,
    RVW_DT       TIMESTAMP    NULL,
    RJCT_RSN     VARCHAR(4000) NULL,
    REG_ID       VARCHAR(30)  NULL,
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID     VARCHAR(30)  NULL,
    MDFCN_DT     TIMESTAMP    NULL,
    VER          BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (RVW_SN),
    CONSTRAINT FK_LS_EVNT_ANNO_REVIEW_ANNO FOREIGN KEY (EVNT_ANNO_SN) REFERENCES LS_EVNT_ANNO (EVNT_ANNO_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_EVNT_ANNO_REVIEW_ANNO ON LS_EVNT_ANNO_REVIEW (EVNT_ANNO_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_EVNT_ANNO_REVIEW_STTS ON LS_EVNT_ANNO_REVIEW (META_TYPE_CD, RVW_STTS_CD);
