-- LS_BATCH_PROC_LOG: finalized authoring-owned batch step log.
CREATE TABLE IF NOT EXISTS LS_BATCH_PROC_LOG (
    BATCH_PROC_LOG_SN BIGINT NOT NULL AUTO_INCREMENT,
    JOB_ID VARCHAR(64) NOT NULL,
    DATA_RAW_SN BIGINT NULL,
    DATA_SRC_SN BIGINT NULL,
    PROC_STEP_CD VARCHAR(30) NOT NULL,
    PROC_STTS_CD VARCHAR(20) NOT NULL,
    START_DT TIMESTAMP NULL,
    END_DT TIMESTAMP NULL,
    RTRY_CNT INT NOT NULL DEFAULT 0,
    ERROR_CD VARCHAR(50) NULL,
    ERROR_MSG VARCHAR(1000) NULL,
    REQ_PAYLOAD LONGTEXT NULL,
    RES_PAYLOAD LONGTEXT NULL,
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID VARCHAR(30) NULL,
    MDFCN_DT TIMESTAMP NULL,
    PRIMARY KEY (BATCH_PROC_LOG_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_BATCH_PROC_LOG_JOB ON LS_BATCH_PROC_LOG (JOB_ID);
CREATE INDEX IF NOT EXISTS IDX_LS_BATCH_PROC_LOG_RAW ON LS_BATCH_PROC_LOG (DATA_RAW_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_BATCH_PROC_LOG_SRC ON LS_BATCH_PROC_LOG (DATA_SRC_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_BATCH_PROC_LOG_STEP_STTS ON LS_BATCH_PROC_LOG (PROC_STEP_CD, PROC_STTS_CD);
