-- 라벨 프리셋 (Phase: SCR-LBL-PRESET-001)
CREATE TABLE LS_LABEL_PRESET (
  PRESET_ID    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '프리셋 PK',
  NAME         VARCHAR(64)  NOT NULL COMMENT '프리셋 이름',
  DESCRIPTION  VARCHAR(500) NULL     COMMENT '설명 (선택)',
  CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  UPDATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
  PRIMARY KEY (PRESET_ID),
  UNIQUE KEY UK_LS_LABEL_PRESET_NAME (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='라벨링 프리셋';

CREATE TABLE LS_LABEL_PRESET_CODE (
  CODE_SN      BIGINT       NOT NULL AUTO_INCREMENT COMMENT '코드 PK',
  PRESET_ID    BIGINT       NOT NULL COMMENT 'FK→LS_LABEL_PRESET',
  CODE         VARCHAR(32)  NOT NULL COMMENT '라벨 코드 (PERSON, VEHICLE 등)',
  SORT_ORDER   INT          NOT NULL DEFAULT 0 COMMENT '입력 순서 보존',
  PRIMARY KEY (CODE_SN),
  UNIQUE KEY UK_LS_LABEL_PRESET_CODE (PRESET_ID, CODE),
  KEY IDX_LS_LABEL_PRESET_CODE_PRESET (PRESET_ID),
  CONSTRAINT FK_LS_LABEL_PRESET_CODE_PRESET FOREIGN KEY (PRESET_ID) REFERENCES LS_LABEL_PRESET(PRESET_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='프리셋 라벨 코드 (1:N)';
