-- =============================================================================
-- V143: 관제 수정 통지 디바운스 누적 LS_MON_NOTI_ACML (Phase 9-C — 크로스노드 디바운스)
--
-- 목적: ControlNotifyDebouncer 의 디바운스 윈도우를 JVM 로컬 ConcurrentHashMap 에서
--       DB 로 옮긴다. 배포 토폴로지는 2노드 Active-Active 인데 윈도우가 인메모리라
--         1) 같은 영상의 수정이 양 노드에 나뉘어 축적되면 export 재생성·관제 통지가 2회 나가고
--            (관제가 같은 영상을 두 버전으로 픽업),
--         2) 노드가 flush 전에 죽으면 축적분이 통째로 유실됐다(재생성·통지 무음 소실).
--       윈도우를 영속화하고 flush 를 조건부 UPDATE 로 클레임해 <한 노드만 1회> flush 하게 한다.
--
-- 모델: 영상(RAW_SN) 1건 = 열린 윈도우 1행(STTS_CD='PENDING'). 축적은 그 행의 CHG_DTL_CN(JSON)에
--       머지한다. flush 클레임은 PENDING→FLUSHING 조건부 UPDATE(1행을 받은 노드만 승리).
--       발송 완료 시 행 삭제. 클레임 후 죽으면 FLUSHING 이 남고 임차(lease) 만료 후 재클레임된다.
--       ※ 부분 유니크(아래)가 "열린 윈도우는 영상당 최대 1개"를 DB 레벨에서 보장하고,
--         FLUSHING 으로 넘어간 행은 제약에서 빠지므로 새 수정이 즉시 새 윈도우를 연다.
--
-- 표준용어 준거(정본: docs/표준용어 — 사업표준단어·공공 공통표준단어/도메인, 사업표준용어):
--   단어) 관제=MON(사업, Monitoring), 알림=NOTI(공공 8차, Notification), 누적=ACML(공공 6차),
--         상태=STTS, 코드=CD, 변경=CHG, 상세=DTL, 내용=CN, 여부=YN, 재처리=RPRCS(공공 6차),
--         일련번호=SN. (선존 LS_CONTROL_NOTIFY_FALLBACK 의 CONTROL/NOTIFY 드리프트는 미러하지 않는다 —
--         LS_BAT_RTY_WTNG(B2) 와 동일 방침.)
--   용어) 등록된 복합용어를 단어 재조합보다 우선 채택:
--         - 변경상세내용 = CHG_DTL_CN (선존 LS_DATA_LBL_HSTRY 와 동일, diff JSON)
--   도메인) 코드V20 = VARCHAR(20) : STTS_CD
--           여부C1  = CHAR(1)     : EXPORT_RPRCS_YN ('Y'/'N' — V85 여부 도메인 통일)
--           일련번호B20 = BIGINT   : NOTI_ACML_SN / RAW_SN
--           ※ CHG_DTL_CN 은 등록 복합용어 "변경상세내용"의 정본 도메인이 내용V4000(VARCHAR(4000))이나,
--             이 컬럼은 프레임 다건 변경을 머지 누적하는 JSON 이라 디바운스 윈도우가 길어지면 4000자를
--             초과할 수 있어 TEXT(내용LT)를 채택한다. 선존 LS_DATA_LBL_HSTRY.CHG_DTL_CN(V115)도
--             동일하게 TEXT 라 이번이 신규 드리프트가 아니라 기존 답습이다(잘림으로 인한 통지 누락이
--             VARCHAR(4000) 절약보다 리스크가 크다는 판단).
--   ※ EXPORT_* 접두는 선존 LS_DATASET_EXPORT(EXPORT_PATH_NM/EXPORT_STTS_CD/EXPORT_VER_NO)와 동일한
--     기존 물리명 축을 따른다.
--
-- STTS_CD 값: PENDING(축적 중 = 열린 윈도우) | FLUSHING(한 노드가 클레임해 발송 중)
--   ※ 발송이 끝나면 행을 삭제하므로 종결 상태는 없다(큐가 아니라 윈도우다).
--
-- 시각 컬럼 의미(둘의 역할이 다르다):
--   REG_DT   = 윈도우 열린 시각. 디바운스 만료 판정(now - debounce-window-sec) 기준.
--   MDFCN_DT = 마지막 갱신 시각. FLUSHING 행에서는 <클레임 임차 시작>이라, 임차 만료 시
--              (크래시 잔재) 다른 노드가 재클레임하는 기준이 된다. 축적분 유실 방지의 핵심.
--
-- RAW_SN 에 FK 를 걸지 않는다 — 통지 축적은 영상 행 수명과 독립이며(영상 정리 시 통지가 막히면
-- 안 된다), 선존 LS_CONTROL_NOTIFY_FALLBACK 도 동일하다.
--
-- 우리 소유 LS_* 테이블(관제 MNG_* 아님) — 협의 불요. PostgreSQL 표준 문법. 멱등(IF NOT EXISTS).
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_MON_NOTI_ACML (
    NOTI_ACML_SN    BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RAW_SN          BIGINT      NOT NULL,                    -- 영상 단위 작업 식별자(LS_DATA_RAW.RAW_SN)
    STTS_CD         VARCHAR(20) NOT NULL DEFAULT 'PENDING',  -- PENDING(축적 중) | FLUSHING(발송 클레임됨)
    EXPORT_RPRCS_YN CHAR(1)     NOT NULL DEFAULT 'N',        -- 이 윈도우가 export 폴더 전량 재생성을 동반하는가
    CHG_DTL_CN      TEXT        NOT NULL DEFAULT '{}',       -- 누적 변경 상세(JSON): 프레임↔변경종류 + 영상단위 변경종류
    REG_DT          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NOTI_ACML_SN)
);

-- 영상당 <열린> 윈도우는 최대 1개 — 두 노드가 동시에 첫 수정을 축적해도 한 행만 생긴다
-- (INSERT ... ON CONFLICT (RAW_SN) WHERE STTS_CD='PENDING' DO NOTHING 의 추론 대상).
-- FLUSHING 행은 제약에서 빠져, 발송 중에 들어온 새 수정이 곧바로 다음 윈도우를 연다.
CREATE UNIQUE INDEX IF NOT EXISTS UK_LMNA_RAW_PENDING
    ON LS_MON_NOTI_ACML (RAW_SN) WHERE STTS_CD = 'PENDING';

-- flush 후보 스캔: (PENDING & REG_DT<=만료컷) OR (FLUSHING & MDFCN_DT<=임차컷)
CREATE INDEX IF NOT EXISTS IDX_LMNA_STTS_REG   ON LS_MON_NOTI_ACML (STTS_CD, REG_DT);
CREATE INDEX IF NOT EXISTS IDX_LMNA_STTS_MDFCN ON LS_MON_NOTI_ACML (STTS_CD, MDFCN_DT);

COMMENT ON TABLE  LS_MON_NOTI_ACML                 IS '관제 수정 통지 디바운스 누적 — 영상 1건의 변경을 윈도우로 모아 1회만 flush(2노드 정합).';
COMMENT ON COLUMN LS_MON_NOTI_ACML.RAW_SN          IS '영상 단위 작업 식별자. 통지 단위가 영상 1건이므로 윈도우 키다.';
COMMENT ON COLUMN LS_MON_NOTI_ACML.STTS_CD         IS 'PENDING(축적 중) / FLUSHING(한 노드가 클레임해 발송 중). 발송 완료 시 행 삭제.';
COMMENT ON COLUMN LS_MON_NOTI_ACML.EXPORT_RPRCS_YN IS 'export 폴더 전량 재생성 동반 여부(OR 누적). Y 면 재생성 후 통지, N 이면 즉시 통지.';
COMMENT ON COLUMN LS_MON_NOTI_ACML.CHG_DTL_CN      IS '누적 변경 상세 JSON {"frames":{srcSn:[변경종류..]},"video":[변경종류..]}. 라벨/메타 본문·PII 미포함.';
COMMENT ON COLUMN LS_MON_NOTI_ACML.REG_DT          IS '윈도우 열린 시각. 디바운스 만료 판정 기준.';
COMMENT ON COLUMN LS_MON_NOTI_ACML.MDFCN_DT        IS '마지막 갱신 시각. FLUSHING 행에서는 클레임 임차 시작 시각(임차 만료 시 재클레임 기준).';
