-- =============================================================================
-- V156: LS_DATA_AUG_DSCD 신설 — 증강 파생영상 <b>폐기 원장</b>(소프트 삭제 표식 → 유예 → 실삭제).
--
-- 배경: REVIEWER 가 증강 결과를 반려하면 파생 영상은 등재 게이트
--   (DerivativeWorkEligibility, RVW_STTS_CD='ACCEPTED' 축)에 의해 즉시 작업 대상에서 빠진다.
--   그러나 <b>행과 파일은 그대로 남는다</b> — 잘못 눌러도 되돌릴 수 있어야 하고(유예), 유예가 지나면
--   실제로 지워져야 한다(저장소 회수). 이 테이블은 그 <b>유예 추적 · 실삭제 집행 · 복구</b> 3가지의
--   단일 원장이다.
--
-- ★ 왜 LS_DATA_AUG 의 컬럼이 아니라 별도 테이블인가 (되돌리지 말 것)
--   실삭제는 LS_DATA_AUG 행 <b>자체를 지운다</b>(파생 요청 이력까지 파생과 함께 정리). 표식을 그
--   테이블의 컬럼으로 두면 삭제와 동시에 <b>무엇을 언제 왜 지웠는지가 함께 사라진다</b> — 감사 추적이
--   끊기고, 커밋 이후 파일 삭제가 실패했을 때 재시도할 <b>경로 단서</b>도 사라진다(파생 RAW 행이 없어
--   경로를 재구성할 방법이 없다). 이 원장은 삭제 이후에도 <b>비석(tombstone)</b> 으로 남는다.
--
-- ★ FK 를 걸지 않는다 (V155 · V146 의 판정 기준을 그대로 따른 결과)
--   · DATA_AUG_SN → LS_DATA_AUG : CASCADE 면 실삭제가 <b>비석 자신</b>을 지워 감사 추적이 사라지고,
--     RESTRICT 면 실삭제 자체가 FK 위반으로 깨진다. 어느 쪽도 성립하지 않는다.
--   · NEW_RAW_SN  → LS_DATA_RAW : 위와 동일(파생 RAW 삭제가 비석을 지운다). NEW_RAW_SN 은 V155 가
--     이미 "계보 링크라 FK 대상 아님" 으로 판정한 컬럼이다.
--   FK 부재로 남는 것은 "이미 삭제된 대상을 가리키는 식별자" 뿐인데, 그것이 바로 비석의 용도다.
--
-- ★ 표준용어·표준도메인 (물리명 + 타입 + 크기)
--   단어를 조합하기 전에 복합용어 등록 여부를 먼저 확인했고, 등록돼 있으면 <b>등록값을 그대로</b> 채택했다.
--   [등록된 복합용어 채택]
--     · 폐기일시   DSCD_DT       (공통표준용어, 연월일시분초D)           → TIMESTAMP
--     · 폐기사유   DSCD_RSN      (공통표준용어, 내용V4000)               → VARCHAR(4000)
--     · 복구일시   RSTR_DT       (공통표준용어, 연월일시분초D)           → TIMESTAMP
--     · 삭제일시   DEL_DT        (공통표준용어 + 사업표준용어, 연월일시분초D) → TIMESTAMP
--     · 영상파일경로 VDO_FILE_PATH(사업표준용어, V1000)                  → VARCHAR(1000)
--     · 신규원시일련번호 NEW_RAW_SN(사업표준용어, N19)                   → BIGINT   (V155 채택값 동일)
--     · 원본원시일련번호 ORGNL_RAW_SN(LS_DATA_RAW 기존 물리명, N19)      → BIGINT
--     · 데이터증강일련번호 DATA_AUG_SN(LS_DATA_AUG 기존 물리명, N19)     → BIGINT
--     · 삭제처리일시 DEL_PRCS_DT(공통표준용어 8차(2025-11), 연월일시분초D) → TIMESTAMP
--       ※ 초판 주석은 이 컬럼을 "미등록 → 표준단어 조합" 으로 분류했으나 <b>오기</b>였다(값·타입은
--         결과적으로 등록값과 동일). 등록된 복합용어를 그대로 채택한 것으로 정정한다(V157 DEV_FIX).
--   [등록 복합용어가 없어 표준단어로 조합 — 각 단어 모두 표준 등재]
--     · DATA_AUG_DSCD_SN : 데이터(DATA) + 증강(AUG) + 폐기(DSCD, 공통표준단어) + 일련번호(SN) → BIGINT
--     · FILE_DEL_DT      : 파일(FILE) + 삭제(DEL) + 일시(DT)                      → TIMESTAMP
--     · RSTR_RSN         : 복구(RSTR) + 사유(RSN, 사업표준단어/도메인 '내용')      → VARCHAR(4000)
--   감사 컬럼(REG_ID/REG_DT/MDFCN_ID/MDFCN_DT)은 리포 전역 관행(VARCHAR(30)/TIMESTAMP)과 동일.
--
-- 우리 소유 LS_* 테이블 — 관제 협의 불요. 데이터마트 뷰(V_COMPLETED_*) 변경 없음.
-- =============================================================================

CREATE TABLE IF NOT EXISTS LS_DATA_AUG_DSCD (
    DATA_AUG_DSCD_SN BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    DATA_AUG_SN      BIGINT        NOT NULL,
    NEW_RAW_SN       BIGINT        NOT NULL,
    ORGNL_RAW_SN     BIGINT        NULL,
    DSCD_DT          TIMESTAMP     NOT NULL,
    DSCD_RSN         VARCHAR(4000) NULL,
    RSTR_DT          TIMESTAMP     NULL,
    RSTR_RSN         VARCHAR(4000) NULL,
    DEL_PRCS_DT      TIMESTAMP     NULL,
    DEL_DT           TIMESTAMP     NULL,
    FILE_DEL_DT      TIMESTAMP     NULL,
    VDO_FILE_PATH    VARCHAR(1000) NULL,
    REG_ID           VARCHAR(30)   NULL,
    REG_DT           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID         VARCHAR(30)   NULL,
    MDFCN_DT         TIMESTAMP     NULL,
    PRIMARY KEY (DATA_AUG_DSCD_SN)
);

COMMENT ON TABLE  LS_DATA_AUG_DSCD                  IS '증강 파생영상 폐기 원장 - 반려 시 표식, 유예 경과 후 실삭제, 유예 내 복구. 실삭제 후에도 비석으로 존속(감사 추적 + 파일 삭제 재시도 단서)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DATA_AUG_DSCD_SN IS '데이터증강폐기일련번호 - PK';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DATA_AUG_SN      IS '데이터증강일련번호 - 폐기 대상 증강 요청(LS_DATA_AUG). FK 미설정(실삭제가 비석을 지우지 않게)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.NEW_RAW_SN       IS '신규원시일련번호 - 폐기 대상 파생 영상(LS_DATA_RAW). NOT NULL - 매핑 없는 그랜드퍼더링 증강은 실삭제 대상이 아니라 애초에 행을 만들지 않는다';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.ORGNL_RAW_SN     IS '원본원시일련번호 - 파생의 부모 영상. 감사(원본 오삭제 사후 검출) + 파생 비디오 경로 재구성 단서';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DSCD_DT          IS '폐기일시 - 소프트 삭제 표식 시각(= 유예 기산점)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DSCD_RSN         IS '폐기사유 - 검수 반려 사유 스냅샷(복구 시 검수행에서 지워지므로 여기 보존)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.RSTR_DT          IS '복구일시 - 값이 있으면 폐기 취소됨(실삭제 대상 아님)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.RSTR_RSN         IS '복구사유 - 되돌린 이유(누가=MDFCN_ID, 언제=RSTR_DT)';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DEL_PRCS_DT      IS '삭제처리일시 - 실삭제 배치의 원자 클레임 마커(2노드 중복 집행 방지). 오래된 클레임은 재클레임 허용';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.DEL_DT           IS '삭제일시 - DB 행 실삭제 커밋 시각';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.FILE_DEL_DT      IS '파일삭제일시 - 생성 파일까지 정리 완료 시각. DEL_DT 가 있고 이 값이 NULL 이면 파일 삭제 재시도 대상';
COMMENT ON COLUMN LS_DATA_AUG_DSCD.VDO_FILE_PATH    IS '영상파일경로 - 삭제 직전 기록한 파생 비디오 경로(RAW 행이 사라진 뒤 재시도용 단서)';

-- 같은 증강에 열린 폐기 표식은 1건만 — 반려 재시도/동시 요청이 표식을 중복 적재하면 유예·복구가
-- 어느 행을 가리키는지 모호해진다. 복구(RSTR_DT)·실삭제(DEL_DT) 로 닫힌 행은 술어에서 빠지므로
-- "반려 → 복구 → 재반려" 는 정상적으로 새 표식을 만든다.
-- ⚠ 이름이 비슷한 UK_LS_DATA_AUG_ACTVTN(V143 → V153 DROP, "같은 영상×종류 활성 증강 1건")과는
--    <b>무관한 별개 제약</b>이다. 그 정책(중복 증강 요청 서버 차단)은 폐기됐고 되살리지 않는다.
CREATE UNIQUE INDEX IF NOT EXISTS UK_LS_DATA_AUG_DSCD_ACTVTN
    ON LS_DATA_AUG_DSCD (DATA_AUG_SN)
    WHERE RSTR_DT IS NULL AND DEL_DT IS NULL;

-- 실삭제 스윕 후보 조회 — 열린 표식 중 유예 경과분을 오래된 순으로 훑는다.
CREATE INDEX IF NOT EXISTS IX_LS_DATA_AUG_DSCD_SWEEP
    ON LS_DATA_AUG_DSCD (DSCD_DT)
    WHERE RSTR_DT IS NULL AND DEL_DT IS NULL;

-- 파일 삭제 재시도 축 — DB 는 지웠는데 파일 정리가 남은 비석.
CREATE INDEX IF NOT EXISTS IX_LS_DATA_AUG_DSCD_FILE_RTY
    ON LS_DATA_AUG_DSCD (DEL_DT)
    WHERE DEL_DT IS NOT NULL AND FILE_DEL_DT IS NULL;

-- 파생 영상 역추적(비석 조회).
CREATE INDEX IF NOT EXISTS IX_LS_DATA_AUG_DSCD_NEW_RAW
    ON LS_DATA_AUG_DSCD (NEW_RAW_SN);
