-- =============================================================================
-- V166: LS_DATA_INGEST 수신 컬럼 신설 (관제 데이터 참조 제거 — 대체 경로 구축)
--
-- ★ 이 마이그레이션은 아무것도 삭제하지 않는다. MNG_* 테이블 제거는 다음 단계다.
-- ★ 변경 대상은 LS_DATA_INGEST 하나뿐이다. LS_DATA_RAW 는 건드리지 않는다(아래 §복사 안 함).
--
-- 배경 — 왜 "삭제 전에" 이 파일이 먼저인가
--   저작도구는 관제 공유 테이블(MNG_*) 참조를 전면 제거하는 중이며, 영상 관련 정보는
--   관제가 직접 INSERT 하는 LS_DATA_INGEST(V147) 로 <평면 수신>한다. 그런데 바로 직전
--   커밋(2026-08-04 "관제 인입 영상 자동마킹 400 해소")이 MNG_CLIP_EVNT_LST 조인으로
--   EVNT_TYPE_CD 를 해석하는 로직을 <주 적재 경로에 방금 넣었다>. 대체 경로 없이 그
--   테이블을 지우면 어제 고친 자동마킹이 즉시 회귀한다(신규 영상 전량 마킹 400).
--   따라서 이 단계에서 대체 경로(인입이 유형코드를 직접 싣는 통로)를 먼저 깔고,
--   MNG_* 제거는 그 다음 단계에서 수행한다.
--
-- 신설 컬럼 (4) — 전부 nullable, 전부 LS_DATA_INGEST
--   EVNT_TYPE_CD   VARCHAR(20)
--   ANONY_INCL_YN · PSDO_INCL_YN · PRVC_INCL_YN   CHAR(1)   (원천 영상 = 비식별 처리 <전> 영상)
--
--   ※ WGS84_LAT / WGS84_LOT 는 <이미 V147 에 존재한다>(DECIMAL(10,7)). 지시서상 "인입 신설"로
--     열거됐으나 V147 DDL 원문 실측 결과 선존이므로 여기서 다시 ADD 하지 않는다. 있는 컬럼을
--     또 만들면 no-op 이거나(IF NOT EXISTS 없이는) 실패이며, 어느 쪽이든 "여기서 만들어졌다"는
--     오독을 남긴다. CCTV_NM · EVNT_NM · RGN_NM · FILE_FMT 도 같은 이유로 선존(V147)이다.
--     즉 관제는 이 6개를 이미 보내고 있고, 저작도구가 그 값을 안 쓰고 마스터를 조인하던 것이 결함이다.
--
-- ★★ LS_DATA_RAW 에는 아무 컬럼도 만들지 않는다 — 값을 복사하지 않는다 (설계 확정)
--   CCTV명·이벤트명·지역명·파일형식·좌표·개인정보 3필드는 <LS_DATA_INGEST 가 단일 진실원>이며
--   조회 시 조인으로 읽는다. 관제가 준 <읽기 전용 사실>을 작업 대상 마스터(LS_DATA_RAW —
--   상태 전이·라벨링·검수가 붙는 가변 테이블)에 복사하면 같은 값이 두 곳에 생기고, 수정될 일이
--   없는 값에 대해 이중 저장소를 유지하게 된다.
--
--   [조인이 성립하는 근거 — 실측]
--     · 원본 영상은 <항상> 인입 행을 보유한다. dev 내부 업로드도 InternalUploadIngestWriter 가
--       LS_DATA_INGEST 에 INSERT 한다(저작도구가 유일하게 정당한 origin 인 예외 흐름).
--     · 인입 행을 삭제하는 코드가 없다 — 감사 추적을 위해 영구 보존한다.
--     · 파생영상(증강·해상도)만 자기 인입 행이 없는데, <파생 깊이가 1 로 고정>돼 있어
--       (확정 정책 "파생본에서는 어떤 파생도 만들지 않는다") 부모는 항상 원본이다.
--       따라서 ORGNL_RAW_SN 1단계 폴백이면 충분하고 재귀 순회가 필요 없다.
--
--   [Phase 3 에서 쓸 조회 패턴]
--     LEFT JOIN LS_DATA_INGEST i ON i.RAW_SN = COALESCE(r.ORGNL_RAW_SN, r.RAW_SN)
--     → 파생이면 부모의 인입 행, 원본이면 자기 인입 행을 본다.
--
--   ⚠ 단 <개인정보 3필드는 파생에서 반드시 null> 이어야 한다. 확정 정책상 <파생영상에는
--     원본영상이 없다 — 비식별 영상만 있다>. 파생의 비디오는 부모의 비식별본 복사본이라
--     "비식별 처리 전 원천"이라는 대상 자체가 존재하지 않는다. 위 폴백 조인을 그대로 쓰면
--     파생이 부모의 원천 판정을 물려받아 <사실이 아닌 값>이 되므로 이 3필드만 파생을 제외한다:
--       CASE WHEN r.ORGNL_RAW_SN IS NULL THEN i.ANONY_INCL_YN ELSE NULL END
--     이름·포맷·좌표는 촬영 주체·장소·이벤트라 파생본에도 그대로 성립하므로 폴백을 타도 된다
--     (파생은 부모의 VMS_CCTV_ID 를 복사받으므로 부모 인입 값이 그대로 유효하다).
--     ★ 이 "파생 제외" 규칙은 <한 곳에만> 구현한다 — 판정을 복제하면 한쪽만 갱신돼 어긋난다
--       (이 저장소의 반복 결함 패턴).
--
--   ★★ 파생의 원천 축이 비는 것은 <결손이 아니라 정상>이다 — 축이 이렇게 닫힌다
--     파생은 부모의 <비식별 영상>으로 만들어진 것이라 파생의 개인정보 판정은 <비식별 축>에서
--     오며, 그 값은 <이미 자기 LS_DATA_RAW 행에 있다>.
--
--       영상   | 원천 축 (LS_DATA_INGEST 조인)          | 비식별 축 (자기 LS_DATA_RAW 행)
--       -------|----------------------------------------|--------------------------------
--       원본   | 인입 조인으로 획득                      | 사람이 화면에서 수동 입력
--       파생   | 없음 (원천 영상 자체가 존재하지 않음)    | 부모에서 계승 (copyPrivacyMetaFrom)
--
--     LsDataRaw.createFromAugment / createFromResolution 이 copyPrivacyMetaFrom(parent) 로 부모의
--     비식별 축 3필드를 <생성 시점 1회 계승>한다(기존 구현, 이 마이그레이션이 건드리지 않는다).
--     CLAUDE.md 구속 정책: "파생영상은 부모의 영상 축 판정을 생성 시점 1회 계승한다 … 계승하지
--     않으면 image=Y / video=N 으로 갈려 개인정보가 과소 신고된다".
--
--     ⚠ 따라서 파생에 원천 축 값을 채우려 하지 말 것(부모 인입 조인 등). 부모의 <원천> 판정은
--       부모의 비식별 <전> 영상에 대한 것이라, 비식별본으로 만들어진 파생에는 해당하지 않는다.
--
--   [예외 — EVNT_TYPE_CD 만 LS_DATA_RAW 로 복사한다]
--     마킹 프리컨디션(MarkingGuards)이 LS_DATA_RAW.EVNT_TYPE_CD 를 <직접> 읽으므로 조인으로
--     대체할 수 없다. 그 컬럼은 <이미 존재>하므로(V2) 이 마이그레이션의 신설 대상이 아니다.
--
-- 관제 송신 요청 항목 (이 컬럼들은 관제가 채워야 값이 생긴다)
--   · EVNT_TYPE_CD — 관제가 채우기 전까지 null 이다. 그동안은 적재 경로가 기존
--     EVNT_ID → MNG_CLIP_EVNT_LST 해석으로 폴백하므로 <현행 동작이 유지>된다(과도기 폴백이며
--     MNG_* 제거 단계에서 함께 걷어낸다).
--   · ANONY_INCL_YN / PSDO_INCL_YN / PRVC_INCL_YN — 관제가 안 보내면 null 이다.
--
-- ★ 인입 값에 서버 보정(fail-closed 기본값)을 하지 않는다
--   LS_DATA_INGEST 는 <관제가 보낸 것을 있는 그대로 보관하는 수신 원장>이다. 적재 시점에
--   기본값으로 채우면 "관제가 안 보냈다"와 "관제가 N 을 보냈다"를 영영 구분할 수 없다.
--   fail-closed 기본값(익명 N / 가명 N / 개인정보 Y)은 <값을 소비하는 시점>(export 판정)에서
--   적용한다 — 이번 단계 범위가 아니다.
--   같은 이유로 DB DEFAULT 도 두지 않는다(DEFAULT 를 두면 관제가 보낸 적 없는 기존 행까지
--   소급해 "판정이 있다"고 주장하게 된다).
--
-- ★ 개인정보 3필드는 LS_DATA_RAW 의 동명 컬럼(V163)과 <다른 축>이다 — 절대 섞지 말 것
--
--     축              | 대상                        | 값의 출처
--     ----------------|-----------------------------|--------------------------------------
--     원천(ORIGINAL)  | 비식별 처리 <전> 원천 영상   | 관제 인입 (이번 신설 — LS_DATA_INGEST)
--     비식별(DEIDENT) | 비식별 처리된 영상          | 사람이 화면에서 수동 입력
--                     |                             | (LS_DATA_RAW.*_INCL_YN, V163)
--
--   선존 LS_DATA_RAW.ANONY_INCL_YN / PSDO_INCL_YN / PRVC_INCL_YN(V163)은 <비식별 영상에 대한
--   사람의 수동 판정> 전용이며 그 null 은 "사람이 아직 입력하지 않았다"를 뜻한다
--   (ExportPrivacyPolicy 가 그 null 을 보고 기본상수 프리필 여부를 가른다).
--   적재가 그 컬럼에 관제 수신값을 쓰면 <null=미입력 시맨틱이 붕괴>해, export 가 "관제 기본값"을
--   "사람의 판정"으로 둔갑시켜 내보낸다. 이번 적재 경로는 그 3컬럼을 <건드리지 않으며>,
--   회귀 가드가 이 불변식을 고정한다(TrainingVideoIngestTxTest · IngestFlatMetaMigrationIT).
--
--   ※ 이번 단계는 <컬럼 신설>까지다. ExportPrivacyPolicy 의 판정 로직(ORIGINAL 산출물에서
--     3필드를 null 로 두는 현행 구속 정책)은 <건드리지 않는다> — 그 변경은 CLAUDE.md·
--     테스트케이스 갱신이 따르는 별도 작업이다.
--
-- 표준용어·표준도메인 근거 (신규 판정 대상 없음 — 전부 기존 등록분 재사용)
--   [검증 실시 2026-08-04 — docs/표준용어 CSV 정본 4종 직접 대조]
--     · 이벤트유형코드 EVNT_TYPE_CD — 사업표준용어 등록 · 사업도메인 코드V20 → VARCHAR(20) 일치.
--         선존 LS_DATA_RAW.EVNT_TYPE_CD(V107 에서 코드V20 으로 정렬)·MNG_CLIP_EVNT_LST 의
--         동명 컬럼과도 같은 길이라 어느 경로로 채워지든 절단이 없다.
--     · 익명여부포함 ANONY_INCL_YN / 가명여부포함 PSDO_INCL_YN / 개인정보포함여부 PRVC_INCL_YN
--         셋 다 사업표준용어 <등록 물리명 그대로>이며 선존 LS_DATA_RAW(V163)와 동일하다.
--         ★ 타입은 CHAR(1) 을 채택한다 — 등록 도메인이 두 갈래이기 때문이다:
--             사업표준도메인 여부V1 = VARCHAR(1)   /   공통표준도메인 여부C1 = CHAR(1)
--           이 프로젝트는 V85(align_yn_columns_char1)에서 여부 컬럼을 <공공 여부C1 = CHAR(1)>로
--           일괄 정렬했고 선존 V163 3필드도 CHAR(1) + @JdbcTypeCode(CHAR) 로 매핑돼 있다.
--           같은 의미의 짝 컬럼을 VARCHAR(1) 로 만들면 <같은 테이블 안에서 타입이 갈리는> 더 큰
--           드리프트가 되고 엔티티 매핑도 어긋나므로 사내 선례(V85/V163)를 따른다.
--     · 접두 없음 — LS_DATA_INGEST 에는 비식별 축이 아예 없어 혼동 여지가 없고, 관제가 보내는
--       필드명과 1:1 대응하는 편이 연동 계약 문서화에 유리하다.
--
-- 잠금 영향 (2노드 Active-Active 무중단 배포)
--   PostgreSQL 11+ 부터 <DEFAULT 없는 nullable 컬럼 추가>는 테이블을 재작성하지 않고 카탈로그
--   메타데이터만 갱신한다. ACCESS EXCLUSIVE 락을 잡지만 구간이 상수 시간이라 순간이다.
--   여기서는 DEFAULT 를 아예 두지 않아 기존 행은 전부 NULL 로 남고 rewrite 도 없다.
--
-- 데이터 영향
--   기존 행 0건 변경. 신설 컬럼은 전부 NULL 로 시작하고 값은 <이후 관제 송신분부터> 채워진다.
--   기존 행 백필은 이 파일의 범위가 아니다(필요해지면 V164 형태의 별도 1회성 마이그레이션).
--
-- ★ 롤백 절차
--   컬럼 <추가>이고 전부 nullable 이라 구버전 jar 는 이 컬럼들을 단순히 무시한다
--   (ddl-auto=validate 는 "엔티티에 없는 DB 컬럼"을 문제 삼지 않는다). 따라서 스키마를 되돌리지
--   않고 구버전으로 롤백해도 <기동 실패가 없다> — V165(DROP) 와 달리 선행 조치가 필요 없다.
--   스키마까지 되돌려야 한다면 DBA 가 아래를 수동 적용한다.
--
--     ALTER TABLE LS_DATA_INGEST DROP COLUMN IF EXISTS EVNT_TYPE_CD;
--     ALTER TABLE LS_DATA_INGEST DROP COLUMN IF EXISTS ANONY_INCL_YN;
--     ALTER TABLE LS_DATA_INGEST DROP COLUMN IF EXISTS PSDO_INCL_YN;
--     ALTER TABLE LS_DATA_INGEST DROP COLUMN IF EXISTS PRVC_INCL_YN;
--     DELETE FROM flyway_schema_history WHERE version = '166';
--
--   ★ 롤백 시 <LS_DATA_RAW 의 동명 3컬럼(V163)을 절대 지우지 말 것> — 이름이 같지만 그 3개는
--     <비식별 축 수동 판정>이며 이 마이그레이션이 만든 것이 아니다. 지우면 사람이 입력한
--     판정이 전부 소실된다(비가역). 이 파일은 LS_DATA_RAW 를 한 줄도 건드리지 않는다.
--
-- 문법: PostgreSQL 표준 (MariaDB 고유 문법 미사용). IF NOT EXISTS 로 재실행 안전(멱등).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) 이벤트유형코드 직접 수신 통로 — 관제 공유 테이블(MNG_CLIP_EVNT_LST) 조인 해석의 대체 경로.
--    관제가 이 값을 채우면 적재 경로가 마스터 조회 없이 그대로 사용한다
--    (TrainingVideoIngestTx#resolveEvntTypeCd — 인입값 우선, 미수신 시 기존 해석 폴백).
-- -----------------------------------------------------------------------------
ALTER TABLE LS_DATA_INGEST ADD COLUMN IF NOT EXISTS EVNT_TYPE_CD VARCHAR(20);

COMMENT ON COLUMN LS_DATA_INGEST.EVNT_TYPE_CD IS
    '이벤트유형코드(관제 수신). LS_DATA_RAW.EVNT_TYPE_CD 의 원천이며 마킹 진입 프리컨디션 값이다. EVNT_ID(식별자, 예 ABA_0001)와 서로 다른 값이다 — 대체·통합하지 않는다. 관제 미채움 시 null 이며 적재 경로가 EVNT_ID → MNG_CLIP_EVNT_LST 해석으로 폴백한다(과도기).';

-- -----------------------------------------------------------------------------
-- 2) 원천 영상(비식별 처리 전)의 개인정보 3필드 수신 통로.
--    ★ LS_DATA_RAW 의 동명 컬럼(V163)은 <비식별 영상에 대한 사람의 수동 판정>이라 다른 축이다.
--      적재는 그 3컬럼을 건드리지 않는다(위 §축이 두 개 참조).
--    ★ 서버 보정 없음 — 관제가 안 보내면 null 로 둔다. fail-closed 기본값은 소비 시점에서 적용한다.
-- -----------------------------------------------------------------------------
ALTER TABLE LS_DATA_INGEST ADD COLUMN IF NOT EXISTS ANONY_INCL_YN CHAR(1);  -- 익명정보 포함여부(원천)
ALTER TABLE LS_DATA_INGEST ADD COLUMN IF NOT EXISTS PSDO_INCL_YN  CHAR(1);  -- 가명정보 포함여부(원천)
ALTER TABLE LS_DATA_INGEST ADD COLUMN IF NOT EXISTS PRVC_INCL_YN  CHAR(1);  -- 개인정보 포함여부(원천)

COMMENT ON COLUMN LS_DATA_INGEST.ANONY_INCL_YN IS
    '원천 영상(비식별 처리 전)의 익명정보 포함여부(관제 수신, Y/N). 저작도구가 사람 입력으로 관리하는 비식별 축(LS_DATA_RAW.ANONY_INCL_YN, V163)과 대상이 다른 별개 축이다 — 적재는 그 컬럼을 채우지 않는다. 관제 미수신 시 null 이며 서버가 보정하지 않는다(수신 원장). 조회 시 파생영상은 원천 영상이 없으므로 이 값을 물려받지 않는다.';
COMMENT ON COLUMN LS_DATA_INGEST.PSDO_INCL_YN IS
    '원천 영상의 가명정보 포함여부(관제 수신, Y/N). 비식별 축(LS_DATA_RAW.PSDO_INCL_YN, V163)과 별개. 미수신 시 null(서버 보정 없음).';
COMMENT ON COLUMN LS_DATA_INGEST.PRVC_INCL_YN IS
    '원천 영상의 개인정보 포함여부(관제 수신, Y/N). 비식별 축(LS_DATA_RAW.PRVC_INCL_YN, V163)과 별개. 미수신 시 null(서버 보정 없음 — fail-closed 기본값 Y 는 소비 시점에서 적용).';
