-- LS_AUTH_WORK_LOCK: 저작도구 작업 잠금.
-- 기준: docs/requirements/final-clean/관제서버_DB_신규테이블_DDL.md §3
-- 작업 잠금은 LS_DATA_RAW 의 고유 속성이 아니므로 별도 테이블로 분리한다.
CREATE TABLE IF NOT EXISTS LS_AUTH_WORK_LOCK (
    WORK_LOCK_SN BIGINT NOT NULL AUTO_INCREMENT,
    LOCK_TARGET_CD VARCHAR(20) NOT NULL,
    PJT_SN BIGINT NULL,
    DATA_RAW_SN BIGINT NULL,
    DATA_SRC_SN BIGINT NULL,
    LOCK_STTS_CD VARCHAR(20) NOT NULL,
    LOCK_ID VARCHAR(64) NOT NULL,
    LOCK_OWNER_ID VARCHAR(30) NULL,
    LOCK_DT TIMESTAMP NOT NULL,
    EXPIRE_DT TIMESTAMP NULL,
    RELEASE_DT TIMESTAMP NULL,
    RELEASE_REASON VARCHAR(500) NULL,
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID VARCHAR(30) NULL,
    MDFCN_DT TIMESTAMP NULL,
    PRIMARY KEY (WORK_LOCK_SN),
    CONSTRAINT UK_LS_AUTH_WORK_LOCK_ID UNIQUE (LOCK_ID)
);

CREATE INDEX IF NOT EXISTS IDX_LS_AUTH_WORK_LOCK_TARGET ON LS_AUTH_WORK_LOCK (LOCK_TARGET_CD, PJT_SN, DATA_RAW_SN, DATA_SRC_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_AUTH_WORK_LOCK_STTS ON LS_AUTH_WORK_LOCK (LOCK_STTS_CD, EXPIRE_DT);
