-- LS_DATA_LBL_AI_INFO: AI 라벨 출처/신뢰도 정보.
-- 기준: docs/requirements/final-clean/관제서버_DB_신규테이블_DDL.md §6
-- LS_DATA_LBL 은 현재 라벨 좌표만 보관하고 AI 추론 출처는 본 테이블로 분리한다.
CREATE TABLE IF NOT EXISTS LS_DATA_LBL_AI_INFO (
    DATA_LBL_AI_INFO_SN BIGINT NOT NULL AUTO_INCREMENT,
    DATA_LBL_SN BIGINT NOT NULL,
    DATA_RAW_SN BIGINT NOT NULL,
    DATA_SRC_SN BIGINT NOT NULL,
    LBL_SRC_CD VARCHAR(20) NOT NULL,
    MODEL_NM VARCHAR(100) NULL,
    MODEL_VER VARCHAR(50) NULL,
    CONF_SCORE DECIMAL(6,5) NULL,
    AUTO_LBL_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID VARCHAR(30) NULL,
    MDFCN_DT TIMESTAMP NULL,
    PRIMARY KEY (DATA_LBL_AI_INFO_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_DATA_LBL_AI_INFO_LBL ON LS_DATA_LBL_AI_INFO (DATA_LBL_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_DATA_LBL_AI_INFO_SRC ON LS_DATA_LBL_AI_INFO (DATA_RAW_SN, DATA_SRC_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_DATA_LBL_AI_INFO_SRC_CD ON LS_DATA_LBL_AI_INFO (LBL_SRC_CD);
