-- LS_LABEL_VERSION: 라벨 Gitea 커밋 버전.
-- 기준: docs/requirements/final-clean/관제서버_DB_신규테이블_DDL.md §7
-- 변경 히스토리/롤백은 Gitea 가 담당하고 DB 는 현재 라벨이 어떤 커밋 기준인지만 추적한다.
CREATE TABLE IF NOT EXISTS LS_LABEL_VERSION (
    LABEL_VERSION_SN BIGINT NOT NULL AUTO_INCREMENT,
    PJT_SN BIGINT NOT NULL,
    DATA_RAW_SN BIGINT NOT NULL,
    DATA_SRC_SN BIGINT NULL,
    GITEA_CMT_HASH VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SAVE_REASON_CD VARCHAR(20) NULL,
    ACTIVE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LABEL_VERSION_SN),
    CONSTRAINT UK_LS_LABEL_VERSION_HASH UNIQUE (GITEA_CMT_HASH)
);

CREATE INDEX IF NOT EXISTS IDX_LS_LABEL_VERSION_TARGET ON LS_LABEL_VERSION (PJT_SN, DATA_RAW_SN, DATA_SRC_SN, ACTIVE_YN);
