-- LS_DATA_META_REVIEW: 외부 메타데이터 검토 상태.
-- 기준: docs/requirements/final-clean/관제서버_DB_신규테이블_DDL.md §10
-- LS_DATA_META 는 값을 저장하고 외부 생성 여부/검토 상태는 본 테이블에서 관리한다.
CREATE TABLE IF NOT EXISTS LS_DATA_META_REVIEW (
    DATA_META_REVIEW_SN BIGINT NOT NULL AUTO_INCREMENT,
    DATA_META_SN BIGINT NOT NULL,
    PJT_SN BIGINT NOT NULL,
    DATA_RAW_SN BIGINT NOT NULL,
    DATA_SRC_SN BIGINT NULL,
    META_TYPE_CD VARCHAR(20) NOT NULL,
    SRC_SYS_CD VARCHAR(20) NULL,
    RVW_STTS_CD VARCHAR(20) NOT NULL,
    RVW_ID VARCHAR(30) NULL,
    RVW_DT TIMESTAMP NULL,
    REJECT_REASON VARCHAR(1000) NULL,
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID VARCHAR(30) NULL,
    MDFCN_DT TIMESTAMP NULL,
    PRIMARY KEY (DATA_META_REVIEW_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LS_DATA_META_REVIEW_META ON LS_DATA_META_REVIEW (DATA_META_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_DATA_META_REVIEW_TARGET ON LS_DATA_META_REVIEW (PJT_SN, DATA_RAW_SN, DATA_SRC_SN);
CREATE INDEX IF NOT EXISTS IDX_LS_DATA_META_REVIEW_STTS ON LS_DATA_META_REVIEW (META_TYPE_CD, RVW_STTS_CD);
