-- LS_DEIDENT_PROC_LOG: DeidentifyStep 이 기록하는 영상 단위 비식별 API 호출 이력.
CREATE TABLE IF NOT EXISTS LS_DEIDENT_PROC_LOG (
    PROC_LOG_SN BIGINT NOT NULL AUTO_INCREMENT,
    DATA_RAW_SN BIGINT NOT NULL,
    REQ_ID VARCHAR(64) NULL,
    ORGN_FILE_PATH VARCHAR(1000) NOT NULL,
    DE_IDNTF_FILE_PATH VARCHAR(1000) NULL,
    PROC_STTS_CD VARCHAR(20) NOT NULL,
    REQ_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RES_DT TIMESTAMP NULL,
    ERROR_CD VARCHAR(50) NULL,
    ERROR_MSG VARCHAR(1000) NULL,
    REG_ID VARCHAR(30) NULL,
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_ID VARCHAR(30) NULL,
    MDFCN_DT TIMESTAMP NULL,
    PRIMARY KEY (PROC_LOG_SN)
);
CREATE INDEX IDX_LS_DEIDENT_PROC_LOG_RAW ON LS_DEIDENT_PROC_LOG (DATA_RAW_SN);
CREATE INDEX IDX_LS_DEIDENT_PROC_LOG_STTS ON LS_DEIDENT_PROC_LOG (PROC_STTS_CD);
