-- H2 전용 Quartz 스키마 (운영 MariaDB는 기존 QRTZ_* 테이블 공유)
-- Phase 3: 영상 수신 + 큐 + Quartz 부트스트랩.
-- 운영 klid_system 에는 본 테이블이 이미 존재하므로 IF NOT EXISTS 로 충돌 방지.
-- 컬럼 정의는 저작도구_DB설계서_FINAL.md §3.3 / §3.9 / §3.10 + plan Phase 3 기준.

-- ============================================================
-- §3.3 원시 영상 (LS_DATA_RAW)
--  - VMS_CLIP_ID UK 로 관제서버로부터의 중복 송신 방지(upsert 기반)
--  - 본 테이블은 H2/MariaDB 양쪽 호환을 우선해 NOT NULL/디폴트만 지정.
-- ============================================================

CREATE TABLE IF NOT EXISTS LS_DATA_RAW (
    RAW_SN          BIGINT          NOT NULL AUTO_INCREMENT,
    VMS_CLIP_ID     VARCHAR(128)    NOT NULL,
    VMS_CCTV_ID     VARCHAR(64)     NOT NULL,
    EVNT_TYPE_CD    VARCHAR(32),
    LCLGV_CD        VARCHAR(32),
    PRVC_TYPE_CD    VARCHAR(16)     NOT NULL,
    PRVC_YN         VARCHAR(1)      NOT NULL DEFAULT 'N',
    DE_IDNTF_YN     VARCHAR(1)      NOT NULL DEFAULT 'N',
    FILE_PATH       VARCHAR(500)    NOT NULL,
    CAPTURED_AT     TIMESTAMP,
    DURATION_SEC    INT,
    DATA_STTS_CD    VARCHAR(32)     NOT NULL DEFAULT 'PENDING',
    REG_DT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT          TIMESTAMP,
    PRIMARY KEY (RAW_SN),
    CONSTRAINT UK_LS_DATA_RAW_VMS_CLIP UNIQUE (VMS_CLIP_ID)
);

CREATE INDEX IF NOT EXISTS IX_LS_DATA_RAW_CCTV ON LS_DATA_RAW (VMS_CCTV_ID);
CREATE INDEX IF NOT EXISTS IX_LS_DATA_RAW_STTS ON LS_DATA_RAW (DATA_STTS_CD);

CREATE TABLE IF NOT EXISTS LS_DATA_RAW_HSTRY (
    HSTRY_SEQ       BIGINT          NOT NULL AUTO_INCREMENT,
    RAW_SN          BIGINT          NOT NULL,
    CHG_TYPE        VARCHAR(16)     NOT NULL,
    PREV_STTS_CD    VARCHAR(32),
    NEW_STTS_CD     VARCHAR(32),
    CHG_USER_NO     BIGINT,
    CHG_DT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (HSTRY_SEQ)
);

CREATE INDEX IF NOT EXISTS IX_LS_DATA_RAW_HSTRY_RAW ON LS_DATA_RAW_HSTRY (RAW_SN);

-- ============================================================
-- §3.10 관제 마스터 (저작도구는 읽기 전용)
-- ============================================================

CREATE TABLE IF NOT EXISTS MNG_CLIP_MASTER (
    CLIP_SN         BIGINT          NOT NULL,
    VMS_CLIP_ID     VARCHAR(128)    NOT NULL,
    VMS_CCTV_ID     VARCHAR(64)     NOT NULL,
    JOB_DMND_YN     VARCHAR(1)      NOT NULL DEFAULT 'N',
    REG_DT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CLIP_SN)
);

CREATE TABLE IF NOT EXISTS MNG_RESOURCE_CCTV (
    VMS_CCTV_ID     VARCHAR(64)     NOT NULL,
    CCTV_NM         VARCHAR(255),
    SHT_ADDR        VARCHAR(500),
    OG_NM           VARCHAR(255),
    WGS84_LAT       DECIMAL(10,7),
    WGS84_LOT       DECIMAL(10,7),
    RESOLUTION      VARCHAR(32),
    USE_YN          VARCHAR(1)      NOT NULL DEFAULT 'Y',
    PRIMARY KEY (VMS_CCTV_ID)
);

CREATE TABLE IF NOT EXISTS MNG_EX_EVNT_TYPE (
    EVNT_TYPE_CD    VARCHAR(32)     NOT NULL,
    CLCT_EVNT_NM    VARCHAR(255)    NOT NULL,
    USE_YN          VARCHAR(1)      NOT NULL DEFAULT 'Y',
    PRIMARY KEY (EVNT_TYPE_CD)
);

CREATE TABLE IF NOT EXISTS MNG_EX_EVNT_TYPE_MAP (
    EVNT_TYPE_CD    VARCHAR(32)     NOT NULL,
    EVNT_NM         VARCHAR(255)    NOT NULL,
    UP_EVNT_TYPE_CD VARCHAR(32),
    EVNT_LVL        INT             NOT NULL DEFAULT 1,
    PRIMARY KEY (EVNT_TYPE_CD)
);

CREATE TABLE IF NOT EXISTS MNG_EX_LOCAL_GOV (
    LCLGV_CD        VARCHAR(32)     NOT NULL,
    SIDO_NM         VARCHAR(64),
    SGG_NM          VARCHAR(64),
    USE_YN          VARCHAR(1)      NOT NULL DEFAULT 'Y',
    PRIMARY KEY (LCLGV_CD)
);

-- ============================================================
-- §3.9 배치 작업 큐 (MNG_CLIP_SCHEDULE_QUE)
--  - JOB_TYPE = 'LABELING_BATCH' 값으로 라벨링 배치 파이프라인 적재.
--  - STATUS: PENDING / IN_PROGRESS / DONE / FAILED.
-- ============================================================

CREATE TABLE IF NOT EXISTS MNG_CLIP_SCHEDULE_QUE (
    QUE_SN          BIGINT          NOT NULL AUTO_INCREMENT,
    RAW_SN          BIGINT          NOT NULL,
    JOB_TYPE        VARCHAR(32)     NOT NULL,
    STATUS          VARCHAR(16)     NOT NULL DEFAULT 'PENDING',
    RETRY_COUNT     INT             NOT NULL DEFAULT 0,
    REGISTERED_AT   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STARTED_AT      TIMESTAMP,
    COMPLETED_AT    TIMESTAMP,
    LAST_ERROR      VARCHAR(2000),
    PRIMARY KEY (QUE_SN)
);

CREATE INDEX IF NOT EXISTS IX_MNG_CLIP_SCHEDULE_QUE_STATUS ON MNG_CLIP_SCHEDULE_QUE (STATUS, JOB_TYPE);
CREATE INDEX IF NOT EXISTS IX_MNG_CLIP_SCHEDULE_QUE_RAW ON MNG_CLIP_SCHEDULE_QUE (RAW_SN);

-- ============================================================
-- Quartz 11개 테이블 (H2 전용 — 운영은 기존 QRTZ_* 사용)
--  Quartz 공식 quartz_h2.sql 참고. IF NOT EXISTS 로 운영 충돌 방지.
--  isClustered = false (단일 인스턴스). 운영은 application-prd.yml 에서 isClustered=true 설정.
-- ============================================================

CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS (
    SCHED_NAME        VARCHAR(120) NOT NULL,
    JOB_NAME          VARCHAR(200) NOT NULL,
    JOB_GROUP         VARCHAR(200) NOT NULL,
    DESCRIPTION       VARCHAR(250),
    JOB_CLASS_NAME    VARCHAR(250) NOT NULL,
    -- BOOL 로 통일 (H2 MODE=MySQL 호환). 운영 MariaDB 의 VARCHAR(1) 와 JDBC 레벨에서 호환됨.
    IS_DURABLE        BOOL         NOT NULL,
    IS_NONCONCURRENT  BOOL         NOT NULL,
    IS_UPDATE_DATA    BOOL         NOT NULL,
    REQUESTS_RECOVERY BOOL         NOT NULL,
    JOB_DATA          BLOB,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS (
    SCHED_NAME     VARCHAR(120) NOT NULL,
    TRIGGER_NAME   VARCHAR(200) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL,
    JOB_NAME       VARCHAR(200) NOT NULL,
    JOB_GROUP      VARCHAR(200) NOT NULL,
    DESCRIPTION    VARCHAR(250),
    NEXT_FIRE_TIME BIGINT,
    PREV_FIRE_TIME BIGINT,
    PRIORITY       INTEGER,
    TRIGGER_STATE  VARCHAR(16)  NOT NULL,
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL,
    START_TIME     BIGINT       NOT NULL,
    END_TIME       BIGINT,
    CALENDAR_NAME  VARCHAR(200),
    MISFIRE_INSTR  SMALLINT,
    JOB_DATA       BLOB,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME      VARCHAR(120) NOT NULL,
    TRIGGER_NAME    VARCHAR(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR(200) NOT NULL,
    REPEAT_COUNT    BIGINT       NOT NULL,
    REPEAT_INTERVAL BIGINT       NOT NULL,
    TIMES_TRIGGERED BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS (
    SCHED_NAME      VARCHAR(120) NOT NULL,
    TRIGGER_NAME    VARCHAR(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID    VARCHAR(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_NAME  VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1    VARCHAR(512),
    STR_PROP_2    VARCHAR(512),
    STR_PROP_3    VARCHAR(512),
    INT_PROP_1    INT,
    INT_PROP_2    INT,
    LONG_PROP_1   BIGINT,
    LONG_PROP_2   BIGINT,
    DEC_PROP_1    DECIMAL(13,4),
    DEC_PROP_2    DECIMAL(13,4),
    BOOL_PROP_1   VARCHAR(1),
    BOOL_PROP_2   VARCHAR(1),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS (
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_NAME  VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA     BLOB,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS (
    SCHED_NAME    VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR      BLOB         NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS (
    SCHED_NAME        VARCHAR(120) NOT NULL,
    ENTRY_ID          VARCHAR(140) NOT NULL,
    TRIGGER_NAME      VARCHAR(200) NOT NULL,
    TRIGGER_GROUP     VARCHAR(200) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    FIRED_TIME        BIGINT       NOT NULL,
    SCHED_TIME        BIGINT       NOT NULL,
    PRIORITY          INTEGER      NOT NULL,
    STATE             VARCHAR(16)  NOT NULL,
    JOB_NAME          VARCHAR(200),
    JOB_GROUP         VARCHAR(200),
    IS_NONCONCURRENT  BOOL,
    REQUESTS_RECOVERY BOOL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE (
    SCHED_NAME        VARCHAR(120) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT       NOT NULL,
    CHECKIN_INTERVAL  BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE IF NOT EXISTS QRTZ_LOCKS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR(40)  NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
