-- LS_DEIDENT_REPORT 슬림화: 시스템 처리 이력 컬럼을 LS_DEIDENT_PROC_LOG 로 이전.
-- 인덱스 IDX_LS_DEIDENT_REPORT_PROC / IDX_LS_DEIDENT_REPORT_REQ 는 단일 컬럼 인덱스이므로
-- 해당 컬럼 DROP 시 H2/MariaDB 모두 자동 제거된다.
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS REQ_ID;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS ORGN_FILE_PATH_NM;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS DE_IDNTF_FILE_PATH_NM;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS PROC_STTS_CD;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS REQ_DT;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS RES_DT;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS ERROR_CD;
ALTER TABLE LS_DEIDENT_REPORT DROP COLUMN IF EXISTS ERROR_MSG;
