-- ============================================================
-- V34 — PJT_ID 컬럼 전면 제거 (프로젝트 개념 자체 제거)
--
-- 본 마이그레이션은 LS_PJT 테이블은 남기고 (V35 에서 DROP),
-- 다른 9개 테이블의 PJT_ID 컬럼 + 관련 PK/UK/INDEX 만 정리한다.
--
-- 인덱스/UK 이름은 V1__phase2_base_schema.sql, V8__add_ls_data_set.sql,
-- V14__create_ls_pjt_task_event_log.sql, V31__create_ls_label.sql 의
-- 실제 정의와 일치하도록 작성됨.
-- ============================================================

-- LS_LABEL: UK (PJT_ID, NAME) → UK (NAME), 인덱스(PJT_ID,USE_YN,SORT_NO) → (USE_YN,SORT_NO)
ALTER TABLE LS_LABEL DROP INDEX UK_LS_LABEL_NAME;
ALTER TABLE LS_LABEL DROP INDEX IDX_LS_LABEL_PJT_USE;
ALTER TABLE LS_LABEL ADD UNIQUE KEY UK_LS_LABEL_NAME (NAME);
ALTER TABLE LS_LABEL ADD KEY IDX_LS_LABEL_USE (USE_YN, SORT_NO);
ALTER TABLE LS_LABEL DROP COLUMN PJT_ID;

-- LS_PJT_DATA_MPNG: PK (PJT_ID, RAW_DATA_ID) → PK (RAW_DATA_ID)
-- 주의: H2 호환을 위해 DROP/ADD PK를 분리하여 두 문장으로 처리한다.
ALTER TABLE LS_PJT_DATA_MPNG DROP PRIMARY KEY;
ALTER TABLE LS_PJT_DATA_MPNG ADD PRIMARY KEY (RAW_DATA_ID);
ALTER TABLE LS_PJT_DATA_MPNG DROP COLUMN PJT_ID;

-- LS_PJT_DATA_STTS: PK (PJT_ID, RAW_DATA_ID) → PK (RAW_DATA_ID)
ALTER TABLE LS_PJT_DATA_STTS DROP PRIMARY KEY;
ALTER TABLE LS_PJT_DATA_STTS ADD PRIMARY KEY (RAW_DATA_ID);
ALTER TABLE LS_PJT_DATA_STTS DROP COLUMN PJT_ID;

-- LS_PJT_USER_AUTHRT: UK (PJT_ID, RAW_DATA_ID, USER_NO, TASK_TYPE_CD) → (RAW_DATA_ID, USER_NO, TASK_TYPE_CD)
ALTER TABLE LS_PJT_USER_AUTHRT DROP INDEX UK_LS_PJT_USER_AUTHRT;
ALTER TABLE LS_PJT_USER_AUTHRT ADD UNIQUE KEY UK_LS_PJT_USER_AUTHRT (RAW_DATA_ID, USER_NO, TASK_TYPE_CD);
ALTER TABLE LS_PJT_USER_AUTHRT DROP COLUMN PJT_ID;

-- LS_PJT_USER_AUTHRT_HSTRY: 카테고리 컬럼 제거 (인덱스 영향 없음)
ALTER TABLE LS_PJT_USER_AUTHRT_HSTRY DROP COLUMN PJT_ID;

-- LS_PJT_META: PK (PJT_ID, META_KEY) → PK (META_KEY)
ALTER TABLE LS_PJT_META DROP PRIMARY KEY;
ALTER TABLE LS_PJT_META ADD PRIMARY KEY (META_KEY);
ALTER TABLE LS_PJT_META DROP COLUMN PJT_ID;

-- LS_PJT_DDLN: PK (PJT_ID, DDLN_SEQ) → PK (DDLN_SEQ)
ALTER TABLE LS_PJT_DDLN DROP PRIMARY KEY;
ALTER TABLE LS_PJT_DDLN ADD PRIMARY KEY (DDLN_SEQ);
ALTER TABLE LS_PJT_DDLN DROP COLUMN PJT_ID;

-- LS_PJT_TASK_EVENT_LOG: 인덱스 (PJT_ID, RAW_DATA_ID, OCCURRED_AT) → (RAW_DATA_ID, OCCURRED_AT)
ALTER TABLE LS_PJT_TASK_EVENT_LOG DROP INDEX IDX_PJT_TASK_EVENT_VIDEO;
ALTER TABLE LS_PJT_TASK_EVENT_LOG ADD KEY IDX_LS_PJT_TASK_EVENT_LOG_RAW (RAW_DATA_ID, OCCURRED_AT);
ALTER TABLE LS_PJT_TASK_EVENT_LOG DROP COLUMN PJT_ID;

-- LS_DATA_SET: 인덱스(PJT_ID, REGISTERED_AT) + 컬럼 제거
ALTER TABLE LS_DATA_SET DROP INDEX IDX_LS_DATA_SET_PJT;
ALTER TABLE LS_DATA_SET DROP COLUMN PJT_ID;
