-- ============================================================
-- V37 — 기존 LS_PJT_* → 신규 LS_* 테이블 데이터 복사 (Phase 10)
--
-- 원칙:
--   - V36 에서 생성된 신규 7개 테이블로 기존 데이터를 1:1 복사
--   - 기존 LS_PJT_* 는 SELECT 만 — ALTER/DROP 금지 (Phase 11/12 단계적 제거)
--   - 빈 DB 환경 (local/CI/Testcontainers) 에서는 SELECT 0 rows → INSERT 0 rows 정상 통과
--   - 컬럼은 명시적으로 나열 (SELECT * 금지, 컬럼 순서 안전성)
--   - LS_TASK_ASSIGNMENT.ASSIGNMENT_ID 는 AUTO_INCREMENT 신규 PK 이므로 INSERT 시 생략 (자동 부여)
--     기존 AUTHRT_SEQ 값과 무관한 새 ID 가 부여되며, 매핑 정합성은 LS_TASK_ASSIGN_HISTORY 에서
--     AUTHRT_SEQ 컬럼명을 그대로 유지하여 보존 (Phase 11 Entity 매핑 시 연결 키 결정)
-- ============================================================

-- 1. LS_PJT_DATA_MPNG → LS_RAW_DATA_ENROLLMENT
INSERT INTO LS_RAW_DATA_ENROLLMENT (RAW_DATA_ID, REG_DT)
SELECT RAW_DATA_ID, REG_DT
FROM LS_PJT_DATA_MPNG;

-- 2. LS_PJT_DATA_STTS → LS_RAW_DATA_STATUS
INSERT INTO LS_RAW_DATA_STATUS (RAW_DATA_ID, DATA_STTS_CD, STP_CYCL, IGI_CYCL, UPD_DT, VERSION)
SELECT RAW_DATA_ID, DATA_STTS_CD, STP_CYCL, IGI_CYCL, UPD_DT, VERSION
FROM LS_PJT_DATA_STTS;

-- 3. LS_PJT_USER_AUTHRT → LS_TASK_ASSIGNMENT
--    ASSIGNMENT_ID 는 AUTO_INCREMENT 로 신규 부여, 기존 AUTHRT_SEQ 값은 폐기
--    (이력 테이블의 AUTHRT_SEQ 연결은 Phase 11 매핑 작업에서 결정)
INSERT INTO LS_TASK_ASSIGNMENT (USER_NO, RAW_DATA_ID, TASK_TYPE_CD, REG_USER_NO, REG_DT)
SELECT USER_NO, RAW_DATA_ID, TASK_TYPE_CD, REG_USER_NO, REG_DT
FROM LS_PJT_USER_AUTHRT;

-- 4. LS_PJT_USER_AUTHRT_HSTRY → LS_TASK_ASSIGN_HISTORY
--    HSTRY_SEQ 는 AUTO_INCREMENT 이지만 기존 PK 값을 보존하기 위해 명시적으로 복사
INSERT INTO LS_TASK_ASSIGN_HISTORY
    (HSTRY_SEQ, AUTHRT_SEQ, RAW_DATA_ID, PREV_USER_NO, NEW_USER_NO, TASK_TYPE_CD, CHG_USER_NO, CHG_DT)
SELECT HSTRY_SEQ, AUTHRT_SEQ, RAW_DATA_ID, PREV_USER_NO, NEW_USER_NO, TASK_TYPE_CD, CHG_USER_NO, CHG_DT
FROM LS_PJT_USER_AUTHRT_HSTRY;

-- 5. LS_PJT_META → LS_META
INSERT INTO LS_META (META_KEY, META_VAL)
SELECT META_KEY, META_VAL
FROM LS_PJT_META;

-- 6. LS_PJT_DDLN → LS_DEADLINE
INSERT INTO LS_DEADLINE
    (DDLN_SEQ, DDLN_DT, ANONY_INCL_YN, PSDO_INCL_YN, PRVC_INCL_YN, REG_DT)
SELECT DDLN_SEQ, DDLN_DT, ANONY_INCL_YN, PSDO_INCL_YN, PRVC_INCL_YN, REG_DT
FROM LS_PJT_DDLN;

-- 7. LS_PJT_TASK_EVENT_LOG → LS_TASK_EVENT_LOG
--    EVENT_SEQ 는 AUTO_INCREMENT 이지만 기존 PK 값을 보존하기 위해 명시적으로 복사
INSERT INTO LS_TASK_EVENT_LOG
    (EVENT_SEQ, RAW_DATA_ID, EVENT_TYPE_CD, ACTOR_USER_NO, SUBJECT_USER_NO, PREV_USER_NO, REASON, OCCURRED_AT)
SELECT EVENT_SEQ, RAW_DATA_ID, EVENT_TYPE_CD, ACTOR_USER_NO, SUBJECT_USER_NO, PREV_USER_NO, REASON, OCCURRED_AT
FROM LS_PJT_TASK_EVENT_LOG;
