-- Phase 2 보강 (DEV_FIX 1차) — Webhook idempotency 영속 원장.
-- 외부 시스템(Deidentify SW / VLM / 증강) 위탁 시 본 도구가 발급한 idempotencyKey 추적용.
-- 인메모리(ConcurrentHashMap) 구현은 재시작/멀티 인스턴스에서 allowlist 손실 위험 → 영속화.
-- Phase 4 에서 도메인 테이블별 컬럼 추가 후 함께 사용 가능.
CREATE TABLE IF NOT EXISTS LS_WEBHOOK_IDEMPOTENCY (
    IDEMPOTENCY_KEY VARCHAR(64) NOT NULL,
    CHANNEL VARCHAR(32) NOT NULL,           -- DEIDENTIFY|VLM|AUGMENT
    STATE VARCHAR(16) NOT NULL,             -- ISSUED|PROCESSED|FAILED
    EXTERNAL_JOB_ID VARCHAR(128) NULL,
    APPLIED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDEMPOTENCY_KEY)
);
CREATE INDEX IDX_LS_WEBHOOK_IDEMPOTENCY_CH_STATE ON LS_WEBHOOK_IDEMPOTENCY (CHANNEL, STATE);
CREATE INDEX IDX_LS_WEBHOOK_IDEMPOTENCY_EXT_JOB ON LS_WEBHOOK_IDEMPOTENCY (EXTERNAL_JOB_ID);
