-- Phase 2: 관제서버 outbound 통지 fallback 큐 (TASK_COMPLETED / TASK_MODIFIED).
-- LS_GITEA_FALLBACK_QUEUE 패턴 동일 — 영속 백킹 스토어 + dead-letter.

CREATE TABLE LS_CONTROL_NOTIFY_FALLBACK (
    QUEUE_SN       BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(64)  NOT NULL,
    EVENT_TYPE     VARCHAR(32)   NOT NULL,
    RAW_SN         BIGINT        NOT NULL,
    PAYLOAD        TEXT          NOT NULL,
    RETRY_COUNT    INT           NOT NULL DEFAULT 0,
    MAX_RETRY      INT           NOT NULL DEFAULT 5,
    STATUS         VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    LAST_ERROR     VARCHAR(2000),
    NEXT_RETRY_AT  DATETIME,
    DEAD_LETTER_AT DATETIME,
    CREATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_LCNF_IDEMPOTENCY (IDEMPOTENCY_KEY),
    INDEX IDX_LCNF_STATUS (STATUS, NEXT_RETRY_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
