-- Phase 2: 관제서버 outbound 통지 fallback 큐 (TASK_COMPLETED / TASK_MODIFIED).
-- LS_GITEA_FALLBACK_QUEUE 패턴 동일 — 영속 백킹 스토어 + dead-letter.

CREATE TABLE LS_CONTROL_NOTIFY_FALLBACK (
    QUEUE_SN       BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IDMP_KEY       VARCHAR(64)   NOT NULL,                          -- 멱등키 (사업표준)
    EVENT_TYPE_CD  VARCHAR(32)   NOT NULL,                          -- 이벤트 타입 코드
    RAW_SN         BIGINT        NOT NULL,
    PAYLOAD_CN     TEXT          NOT NULL,                          -- 페이로드 내용(CN)
    RTRY_CNT       INT           NOT NULL DEFAULT 0,                -- 재시도 횟수
    MAX_RTRY_CNT   INT           NOT NULL DEFAULT 5,                -- 최대 재시도 횟수
    STTS_CD        VARCHAR(16)   NOT NULL DEFAULT 'PENDING',        -- 상태 코드
    LAST_ERR_MSG   VARCHAR(2000),                                  -- 마지막 오류(ERR) 메시지
    NEXT_RTRY_DT   TIMESTAMP,                                      -- 다음 재시도 일시
    DLQ_DT         TIMESTAMP,                                      -- 사장큐(DLQ) 진입 일시
    REG_DT         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDFCN_DT       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (QUEUE_SN),
    CONSTRAINT UK_LCNF_IDEMPOTENCY UNIQUE (IDMP_KEY)
);

CREATE INDEX IDX_LCNF_STATUS ON LS_CONTROL_NOTIFY_FALLBACK (STTS_CD, NEXT_RTRY_DT);
