-- V45: 마킹 테이블 생성 (Phase 2 — 영상 마킹 도메인)
CREATE TABLE IF NOT EXISTS LS_MARKING (
    MARKING_SN BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RAW_SN     BIGINT       NOT NULL,
    EVENT_NAME VARCHAR(100) NOT NULL,
    MARKING_MODE VARCHAR(16) NOT NULL,
    INTERVAL_SEC INT,
    VIDEO_PATH VARCHAR(500) NOT NULL,
    MARKS      TEXT         NOT NULL,
    STATUS     VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    CREATED_BY BIGINT,
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_LM_RAW (RAW_SN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
