-- V45: 마킹 테이블 생성 (Phase 2 — 영상 마킹 도메인)
-- 행안부 공통표준 정합: 비표준 컬럼을 표준 약어로 정의 (신규 미배포 → CREATE TABLE 직접 작성)
CREATE TABLE IF NOT EXISTS LS_MARKING (
    MARKING_SN         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RAW_SN             BIGINT       NOT NULL,
    EVNT_NM            VARCHAR(100) NOT NULL,             -- 이벤트명 (구 EVENT_NAME)
    MARK_MODE_CD       VARCHAR(16)  NOT NULL,             -- 마킹모드 코드 AUTO/MANUAL (구 MARKING_MODE)
    FRME_INTV_NOCS     INT,                               -- 프레임간격수 (구 INTERVAL_FRAMES)
    VIDEO_FILE_PATH_NM VARCHAR(500) NOT NULL,             -- 영상파일경로명 (구 VIDEO_PATH)
    MARK_CN            TEXT         NOT NULL,             -- 마킹내용 JSON (구 MARKS)
    STTS_CD            VARCHAR(16)  NOT NULL DEFAULT 'PENDING', -- 상태코드 (구 STATUS)
    CREATED_BY         BIGINT,
    REG_DT             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 등록일시 (구 CREATED_AT)
    MDFCN_DT           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 수정일시 (구 UPDATED_AT)
    PRIMARY KEY (MARKING_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LM_RAW ON LS_MARKING (RAW_SN);
