-- V2.0: 포털 사용자 작업 데이터 별도 적재. 원본(LS_DATA_LBL) 미수정 정책.
CREATE TABLE IF NOT EXISTS LS_PORTAL_USER_LABEL (
    USER_LBL_SN     BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PORTAL_USER_NO  VARCHAR(100)    NOT NULL,
    SOURCE_RAW_SN   BIGINT          NOT NULL,
    SOURCE_SRC_SN   BIGINT          NOT NULL,
    LBL_TYPE_CD     VARCHAR(16)     NOT NULL,
    LABEL           VARCHAR(255),
    POINTS          TEXT,
    CREATED_AT      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_LPUL_USER (PORTAL_USER_NO, SOURCE_RAW_SN)
);
