-- V55: 해상도 변경(다운스케일) 산출 추적 테이블 — Phase 1 (RQ-SFR-06-03 v1.8/1.10)
-- 검수 완료(APPROVED) 원본 영상의 프레임 이미지셋을 표준 하위 해상도로 다운스케일한 결과 1건당 1행.
-- 영상(비디오)·라벨·메타·신규 LS_DATA_RAW 행을 만들지 않으며, 본 테이블만 기록한다.
CREATE TABLE IF NOT EXISTS LS_RESOLUTION_EXPORT (
    RES_EXPORT_SN   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    DATA_RAW_SN     BIGINT       NOT NULL,               -- 원본 영상 PK (LS_DATA_RAW.RAW_SN)
    TARGET_RES_CD   VARCHAR(16)  NOT NULL,               -- 표준 하위 해상도 코드 (RES_1080P/RES_720P/RES_480P)
    ORGNL_W         INT          NOT NULL,               -- 원본 가로(px)
    ORGNL_H         INT          NOT NULL,               -- 원본 세로(px)
    TARGET_W        INT          NOT NULL,               -- 타겟 가로(px)
    TARGET_H        INT          NOT NULL,               -- 타겟 세로(px)
    FRAME_CNT       INT          NOT NULL,               -- 다운스케일된 프레임 개수
    OUTPUT_DIR_PATH VARCHAR(500) NOT NULL,               -- 산출 디렉토리 경로(내부 추적용, 응답 미노출)
    REG_ID          VARCHAR(64),                         -- 등록자(REVIEWER) 식별자
    REG_DT          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 등록일시
    PRIMARY KEY (RES_EXPORT_SN),
    CONSTRAINT UK_LS_RES_EXPORT_RAW_RES UNIQUE (DATA_RAW_SN, TARGET_RES_CD)
);

CREATE INDEX IF NOT EXISTS IDX_LRE_RAW ON LS_RESOLUTION_EXPORT (DATA_RAW_SN);
