-- V56: 게시판(공지사항) 테이블 생성 (신규 도메인 — 게시판/공지)
-- 행안부 공통표준 정합: 표준 약어 컬럼으로 정의 (신규 미배포 → CREATE TABLE 직접 작성)
CREATE TABLE IF NOT EXISTS LS_NOTICE (
    NOTICE_SN    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    NOTICE_TITLE VARCHAR(200) NOT NULL,                          -- 공지 제목
    NOTICE_CN    TEXT         NOT NULL,                          -- 공지 내용
    PIN_YN       VARCHAR(1)   NOT NULL DEFAULT 'N',              -- 상단고정여부 Y/N
    PUB_STTS_CD  VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',          -- 발행상태코드 DRAFT/PUBLISHED
    PUB_DT       TIMESTAMP,                                      -- 발행일시 (발행 시점)
    REG_ID       VARCHAR(64),                                    -- 등록자 ID
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,-- 등록일시
    MDFR_ID      VARCHAR(64),                                    -- 수정자 ID
    MDFCN_DT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,-- 수정일시
    PRIMARY KEY (NOTICE_SN)
);

CREATE INDEX IF NOT EXISTS IDX_LNT_PUB ON LS_NOTICE (PUB_STTS_CD, PIN_YN, REG_DT DESC);

-- LS_NOTICE_ATTACH: 첨부파일 (Phase 2 에서 사용 — 본 Phase 미구현)
CREATE TABLE IF NOT EXISTS LS_NOTICE_ATTACH (
    ATTACH_SN     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    NOTICE_SN     BIGINT       NOT NULL,
    ORGNL_FILE_NM VARCHAR(255) NOT NULL,                          -- 원본파일명
    STORE_FILE_NM VARCHAR(255) NOT NULL,                          -- 저장파일명
    FILE_PATH     VARCHAR(500) NOT NULL,                          -- 파일경로
    FILE_SIZE     BIGINT       NOT NULL,                          -- 파일크기(byte)
    REG_DT        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ATTACH_SN),
    CONSTRAINT FK_LNTA_NOTICE FOREIGN KEY (NOTICE_SN) REFERENCES LS_NOTICE(NOTICE_SN) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LNTA_NOTICE ON LS_NOTICE_ATTACH (NOTICE_SN);
