-- Phase 1 — 이슈 스레드 도메인 (검수자↔작업자 양방향 소통 채널).
-- 운영 klid_system 적용 시 관제서버팀 사전 협의 필수 (LS_DATA_ISSUE 확장 — 저작도구 전용 테이블).
-- PostgreSQL 표준 문법만 사용 (Testcontainers postgres:16 + ddl-auto=validate 검증).
--
-- 시나리오 #4 방어 — ALTER → backfill → NOT NULL/DEFAULT 3단계로 분리하여
-- 기존 반려 이력 row 가 NOT NULL 위반 없이 안전하게 채워지도록 한다.

-- ============================================================
-- 1) LS_DATA_ISSUE 확장 — 이슈 타입/상태/프레임참조/낙관적잠금 컬럼 (nullable 로 먼저 추가)
-- ============================================================
ALTER TABLE LS_DATA_ISSUE ADD COLUMN ISSUE_TYPE_CD VARCHAR(20);
ALTER TABLE LS_DATA_ISSUE ADD COLUMN ISSUE_STTS_CD VARCHAR(20);
ALTER TABLE LS_DATA_ISSUE ADD COLUMN SRC_SN        BIGINT;
ALTER TABLE LS_DATA_ISSUE ADD COLUMN VERSION       BIGINT;

-- ============================================================
-- 2) backfill — 기존 행은 모두 검수 반려 이력(REJECTION) 이며 상태 전이 비대상(RESOLVED 고정).
--    VERSION 은 0 으로 시작.
-- ============================================================
UPDATE LS_DATA_ISSUE
   SET ISSUE_TYPE_CD = 'REJECTION',
       ISSUE_STTS_CD = 'RESOLVED',
       VERSION       = 0
 WHERE ISSUE_TYPE_CD IS NULL;

-- ============================================================
-- 3) NOT NULL + DEFAULT 적용. SRC_SN 은 프레임 단위 선택 참조라 NULL 유지.
-- ============================================================
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN ISSUE_TYPE_CD SET DEFAULT 'REJECTION';
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN ISSUE_TYPE_CD SET NOT NULL;
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN ISSUE_STTS_CD SET DEFAULT 'OPEN';
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN ISSUE_STTS_CD SET NOT NULL;
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN VERSION       SET DEFAULT 0;
ALTER TABLE LS_DATA_ISSUE ALTER COLUMN VERSION       SET NOT NULL;

-- SRC_SN 부분 인덱스 (프레임 단위 이슈 조회용 — NULL 행 제외)
CREATE INDEX IX_LS_DATA_ISSUE_SRC ON LS_DATA_ISSUE (SRC_SN) WHERE SRC_SN IS NOT NULL;

-- ============================================================
-- 3-1) CHECK 제약 — 코드값 허용 집합 강제 (backfill 완료 후 추가하여 기존 행 위반 없음).
--      애플리케이션 enum/상수와 1:1 정합. 비정상 코드 적재를 DB 최후 방어로 차단.
-- ============================================================
ALTER TABLE LS_DATA_ISSUE
    ADD CONSTRAINT CK_LS_DATA_ISSUE_TYPE
    CHECK (ISSUE_TYPE_CD IN ('REJECTION', 'INQUIRY'));
ALTER TABLE LS_DATA_ISSUE
    ADD CONSTRAINT CK_LS_DATA_ISSUE_STTS
    CHECK (ISSUE_STTS_CD IN ('OPEN', 'ANSWERED', 'RESOLVED'));

-- ============================================================
-- 4) LS_ISSUE_COMMENT : 이슈 스레드 댓글 (검수자↔작업자 양방향 소통)
--    AUTHOR_ROLE_CD 는 토큰 역할에서만 도출 (시나리오 #1 — Mass Assignment 방어).
-- ============================================================
CREATE TABLE LS_ISSUE_COMMENT (
    ISSUE_COMMENT_SN BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    DATA_ISSUE_SN    BIGINT       NOT NULL,
    AUTHOR_NO        VARCHAR(50)  NOT NULL,
    AUTHOR_ROLE_CD   VARCHAR(20)  NOT NULL,
    CMNT_CN          VARCHAR(1000) NOT NULL,
    REG_DT           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ISSUE_COMMENT_SN),
    -- AUTHOR_ROLE_CD 는 토큰 역할에서만 도출 — 허용 집합을 DB 최후 방어로 강제.
    CONSTRAINT CK_LS_ISSUE_COMMENT_ROLE
        CHECK (AUTHOR_ROLE_CD IN ('WORKER', 'REVIEWER'))
);

CREATE INDEX IX_LS_ISSUE_COMMENT_ISSUE  ON LS_ISSUE_COMMENT (DATA_ISSUE_SN);
CREATE INDEX IX_LS_ISSUE_COMMENT_AUTHOR ON LS_ISSUE_COMMENT (AUTHOR_NO);
