-- Phase 2 (UC018) — KPST 폴링 연동: LS_DEIDENT_PROC_LOG 에 KPST 식별자 + 폴링 상태 컬럼 추가.
-- 모두 nullable 이며 기존 행/콜백 경로(DeidentifyResultService)에 무영향(추가만, 기존 컬럼/제약 변경 없음).
ALTER TABLE LS_DEIDENT_PROC_LOG ADD COLUMN KPST_PRJ_ID BIGINT NULL;       -- KPST 프로젝트 ID(영상 1건=프로젝트 1개)
ALTER TABLE LS_DEIDENT_PROC_LOG ADD COLUMN KPST_DATASET_ID BIGINT NULL;   -- KPST 데이터셋 ID(파일 단위)
ALTER TABLE LS_DEIDENT_PROC_LOG ADD COLUMN POLL_STTS_CD VARCHAR(20) NULL; -- WAITING/POLLING/DOWNLOADED, null=콜백 경로
ALTER TABLE LS_DEIDENT_PROC_LOG ADD COLUMN POLL_LAST_DT TIMESTAMP NULL;   -- 마지막 폴링 시각
ALTER TABLE LS_DEIDENT_PROC_LOG ADD COLUMN POLL_ATTEMPT_CNT INTEGER NULL DEFAULT 0; -- 폴링 시도 횟수(타임아웃 판정용)

-- 폴링 잡이 WAITING/POLLING 대상만 조회하므로 부분 효율을 위한 인덱스.
CREATE INDEX IX_LDPL_POLL_STTS ON LS_DEIDENT_PROC_LOG (POLL_STTS_CD);
