-- 용어 표준 약어 정합: 물리 컬럼 rename (타입/사이즈 변경 없음)
-- Java 필드명/API JSON 키/getter 는 불변 — 엔티티 @Column(name) 만 새 물리명으로 매핑.
-- RENAME COLUMN 은 UK/PK/인덱스가 자동 follow 되며 제약 이름은 그대로 둔다.
ALTER TABLE LS_LABEL_PRESET_CODE RENAME COLUMN CODE_SN TO CD_SN;
ALTER TABLE LS_LABEL_PRESET_CODE RENAME COLUMN CODE    TO LBL_CD;
ALTER TABLE LS_RESOLUTION_EXPORT RENAME COLUMN TARGET_RES_CD TO GOAL_RES_CD;
ALTER TABLE LS_NOTICE            RENAME COLUMN PUB_STTS_CD TO PBLCN_STTS_CD;
ALTER TABLE LS_NOTICE            RENAME COLUMN PUB_DT      TO PBLCN_DT;
ALTER TABLE LS_DEIDENT_PROC_LOG  RENAME COLUMN RES_DT      TO RESP_DT;
