-- =============================================================================
-- V94: 감사(audit) ID 컬럼 길이 통일 — 등록자/수정자 ID 를 전 테이블 VARCHAR(64) 로.
--
-- 근거(내부 길이 정합): 동일명 감사컬럼(REG_ID/MDFCN_ID/MDFR_ID) 길이가 30/50/64 로 분열되어
--   있어 최대치(64 — LS_NOTICE·LS_RESOLUTION_EXPORT 기존 REG_ID/MDFR_ID)로 통일한다.
--   전부 확대이므로 데이터 손실 0(무손실 비파괴 확대). 참조 뷰(V_COMPLETED_*) 는 이 컬럼들을
--   SELECT 하지 않아 뷰 재생성 불필요.
-- =============================================================================

-- REG_ID 30 → 64 (11)
ALTER TABLE LS_AUTH_WORK_LOCK   ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_BATCH_PROC_LOG   ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_AUG_LBL_MAP ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_AUG_RVW     ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_LBL_AI_INFO ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_META_REVIEW ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DEIDENT_PROC_LOG ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_DEIDENT_REPORT   ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_LABEL            ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_LABEL_ATTR       ALTER COLUMN REG_ID TYPE VARCHAR(64);
ALTER TABLE LS_LABEL_VERSION    ALTER COLUMN REG_ID TYPE VARCHAR(64);

-- MDFCN_ID 30 → 64 (9)
ALTER TABLE LS_AUTH_WORK_LOCK   ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_BATCH_PROC_LOG   ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_AUG_RVW     ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_LBL_AI_INFO ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_DATA_META_REVIEW ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_DEIDENT_PROC_LOG ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_DEIDENT_REPORT   ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_LABEL            ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);
ALTER TABLE LS_LABEL_ATTR       ALTER COLUMN MDFCN_ID TYPE VARCHAR(64);

-- MDFR_ID 50 → 64 (1)
ALTER TABLE LS_SYSTEM_CONFIG    ALTER COLUMN MDFR_ID TYPE VARCHAR(64);
