-- Phase 11: 포털 채널 — 본인 업로드 영상 메타.
-- DB 설계서 §LS_PORTAL_USER_VIDEO — V1.5 SFR-15 (포털 구축).
--
-- ⚠ 협의 필요 (관제서버팀 / DBA):
--   - 운영 klid_system 의 LS_PORTAL_USER_VIDEO 가 이미 존재하면 본 V9 의 ALTER 만 적용 필요.
--     아래 CREATE TABLE IF NOT EXISTS / ALTER TABLE ... ADD COLUMN IF NOT EXISTS 는
--     양쪽(존재/미존재) 모두에서 안전하게 동작.
--   - DOWNLOAD_DDLN_DT : 저작도구는 컬럼만 보유. 만료 정책/다운로드 UI 는 포털 자체 책임 (V1.5).
--   - PORTAL_USER_NO   : 포털 발급 토큰의 sub 클레임 그대로 저장 (VARCHAR — 외부 ID 형식 미정).
--
-- H2 + MariaDB 호환을 위해 표준 SQL 타입 + IF NOT EXISTS 사용.

-- ============================================================
-- LS_PORTAL_USER_VIDEO : 포털 사용자 업로드 영상
--   - PORTAL_VIDEO_SN   : PK (BIGINT GENERATED BY DEFAULT AS IDENTITY)
--   - PORTAL_USER_NO    : 포털 사용자 식별자 (IDOR 차단 키 — 본인만 조회/라벨링)
--   - FILE_NM           : 원본 파일명 (Upload-Metadata 의 filename)
--   - FILE_PATH_NM      : 디스크 저장 경로 (STORAGE_RAW_PATH/portal/{userId}/{fileId})
--   - FILE_SZ           : 바이트 단위
--   - MIME_TYPE_CD      : video/mp4, video/quicktime, video/x-msvideo
--   - THMB_FILE_PATH_NM : 썸네일 이미지 경로 (FFmpeg 추출 — 본 Phase 에서는 옵션)
--   - DOWNLOAD_DDLN_DT  : 다운로드 만료 시각 (V1.5: 컬럼만, 정책은 포털)
--   - REG_DT            : 업로드 완료 시각
-- ============================================================

CREATE TABLE IF NOT EXISTS LS_PORTAL_USER_VIDEO (
    PORTAL_VIDEO_SN     BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PORTAL_USER_NO      VARCHAR(50)     NOT NULL,
    FILE_NM             VARCHAR(255),
    FILE_PATH_NM        VARCHAR(500),
    FILE_SZ             BIGINT,
    MIME_TYPE_CD        VARCHAR(50),
    THMB_FILE_PATH_NM   VARCHAR(500),
    DOWNLOAD_DDLN_DT    TIMESTAMP       NULL,
    REG_DT              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PORTAL_VIDEO_SN)
);

-- 운영 DB 에 컬럼이 누락된 경우를 위한 ALTER (이미 있으면 NOOP)
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS FILE_NM VARCHAR(255);
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS FILE_PATH_NM VARCHAR(500);
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS FILE_SZ BIGINT;
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS MIME_TYPE_CD VARCHAR(50);
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS THMB_FILE_PATH_NM VARCHAR(500);
ALTER TABLE LS_PORTAL_USER_VIDEO ADD COLUMN IF NOT EXISTS DOWNLOAD_DDLN_DT TIMESTAMP NULL;

-- IDOR 차단용 인덱스 (본인 업로드 목록 조회시 사용)
CREATE INDEX IF NOT EXISTS IDX_PORTAL_USER_NO ON LS_PORTAL_USER_VIDEO (PORTAL_USER_NO, REG_DT);
