-- StatsControllerTest 격리용 클린업 스크립트.
-- 공유 H2(DB_CLOSE_DELAY=-1) 사용으로 다른 @SpringBootTest 가 LS_DATA_RAW 에 남긴
-- EVT_FALL 등 이벤트 데이터가 누적되어 "데이터 없으면 0" 검증이 깨지는 회귀를 차단한다.
--
-- 자식 테이블도 함께 비워 FK 외 logical 참조(RAW_SN/RAW_DATA_ID) 잔재를 제거한다.

DELETE FROM LS_PJT_DATA_STTS;
DELETE FROM LS_PJT_USER_AUTHRT_HSTRY;
DELETE FROM LS_PJT_USER_AUTHRT;
-- LS_DATA_LBL_HSTRY 는 신규 DB 설계 (LS_LABEL_VERSION 으로 분리) 에서 더 이상 생성되지 않음.
DELETE FROM LS_DATA_LBL;
DELETE FROM LS_DATA_META;
DELETE FROM LS_DATA_SRC_HSTRY;
DELETE FROM LS_DATA_SRC;
DELETE FROM LS_DATA_RAW_HSTRY;
DELETE FROM LS_DATA_RAW;
DELETE FROM MNG_CLIP_SCHEDULE_QUE;
