-- Phase 2 테스트용 시드 데이터.
-- @Sql(scripts = "/db/test-data.sql") 로 명시적 적용.
-- 사용자: 1=REVIEWER, 100/101=WORKER, 200=비활성 워커
-- 영상: 1000~1003

DELETE FROM LS_TASK_EVENT_LOG;
DELETE FROM LS_TASK_ASSIGN_HISTORY;
DELETE FROM LS_TASK_ASSIGNMENT;
DELETE FROM LS_RAW_DATA_STATUS;
DELETE FROM LS_RAW_DATA_ENROLLMENT;
DELETE FROM LS_META;
DELETE FROM LS_DEADLINE;
DELETE FROM MNG_ACCT_USER_AUTHRT;
DELETE FROM MNG_ACCT_AUTHRT;
DELETE FROM MNG_ACCT_USER;

INSERT INTO MNG_ACCT_USER (USER_NO, USER_ID, USER_NM, USER_EMAIL, USE_YN, REG_DT) VALUES
  (1,   'reviewer1', '검수자1', 'r1@example.com', 'Y', CURRENT_TIMESTAMP),
  (100, 'worker100', '작업자100', 'w100@example.com', 'Y', CURRENT_TIMESTAMP),
  (101, 'worker101', '작업자101', 'w101@example.com', 'Y', CURRENT_TIMESTAMP),
  (200, 'worker200', '작업자200', 'w200@example.com', 'N', CURRENT_TIMESTAMP);

INSERT INTO MNG_ACCT_AUTHRT (AUTHRT_CD, AUTHRT_NM, USE_YN) VALUES
  ('REVIEWER', '검수자', 'Y'),
  ('WORKER',   '작업자', 'Y');

INSERT INTO MNG_ACCT_USER_AUTHRT (USER_NO, AUTHRT_CD, REG_DT) VALUES
  (1,   'REVIEWER', CURRENT_TIMESTAMP),
  (100, 'WORKER',   CURRENT_TIMESTAMP),
  (101, 'WORKER',   CURRENT_TIMESTAMP),
  (200, 'WORKER',   CURRENT_TIMESTAMP);
