-- Phase 2 테스트용 시드 데이터.
-- @Sql(scripts = "/db/test-data.sql") 로 명시적 적용.
-- 사용자: 1=REVIEWER, 100/101=WORKER, 200=비활성 워커
-- 영상: 1000~1003

DELETE FROM LS_TASK_EVENT_LOG;
DELETE FROM LS_TASK_ASSIGN_HISTORY;
DELETE FROM LS_TASK_ASSIGNMENT;
DELETE FROM LS_RAW_DATA_STATUS;
DELETE FROM LS_RAW_DATA_ENROLLMENT;
DELETE FROM LS_META;
DELETE FROM LS_DEADLINE;
DELETE FROM LS_USER_ROLE;
DELETE FROM MNG_ACCT_USER_AUTHRT;
DELETE FROM MNG_ACCT_AUTHRT;
DELETE FROM MNG_ACCT_USER;

INSERT INTO MNG_ACCT_USER (USER_NO, USER_ID, USER_NM, USER_EMAIL, USE_YN, REG_DT) VALUES
  (1,   'reviewer1', '검수자1', 'r1@example.com', 'Y', CURRENT_TIMESTAMP),
  (100, 'worker100', '작업자100', 'w100@example.com', 'Y', CURRENT_TIMESTAMP),
  (101, 'worker101', '작업자101', 'w101@example.com', 'Y', CURRENT_TIMESTAMP),
  (200, 'worker200', '작업자200', 'w200@example.com', 'N', CURRENT_TIMESTAMP);

INSERT INTO MNG_ACCT_AUTHRT (AUTHRT_CD, AUTHRT_NM, USE_YN) VALUES
  ('REVIEWER', '검수자', 'Y'),
  ('WORKER',   '작업자', 'Y');

INSERT INTO MNG_ACCT_USER_AUTHRT (USER_NO, AUTHRT_CD, REG_DT) VALUES
  (1,   'REVIEWER', CURRENT_TIMESTAMP),
  (100, 'WORKER',   CURRENT_TIMESTAMP),
  (101, 'WORKER',   CURRENT_TIMESTAMP),
  (200, 'WORKER',   CURRENT_TIMESTAMP);

-- 역할 분리 리팩토링 Phase 2/3 — 저작도구 인가 역할은 LS_USER_ROLE 에서 읽는다.
-- 위 MNG_ACCT_USER_AUTHRT 와 동일 USER_NO/역할로 시드 (USER_NO 단일 PK).
-- 200 은 WORKER 역할이지만 USE_YN='N' 이라 작업자 목록에서 제외되어야 한다(useYn 읽기 필터 검증).
-- Phase 3 — 본 DELETE+재삽입이 전체 테스트 공유 컨테이너의 canonical 역할 시드(V9001)를
-- 영구 삭제하지 않도록, @Sql 미적재 sql=0 컨트롤러 테스트가 의존하는 2/1001/2001 역할도 함께
-- 재삽입해 superset 을 항상 유지한다(orphan LS 행 — MNG 사용자 없음 — 은 사용자 목록 쿼리에 비노출).
INSERT INTO LS_USER_ROLE (USER_NO, ROLE_CD, REG_DT) VALUES
  (1,    'REVIEWER', CURRENT_TIMESTAMP),
  (2,    'WORKER',   CURRENT_TIMESTAMP),
  (100,  'WORKER',   CURRENT_TIMESTAMP),
  (101,  'WORKER',   CURRENT_TIMESTAMP),
  (200,  'WORKER',   CURRENT_TIMESTAMP),
  (1001, 'REVIEWER', CURRENT_TIMESTAMP),
  (2001, 'WORKER',   CURRENT_TIMESTAMP);
