-- Phase 2 테스트용 시드 데이터.
-- @Sql(scripts = "/db/test-data.sql") 로 명시적 적용.
-- 사용자: 1=REVIEWER, 100/101=WORKER, 200=비활성 워커
-- 프로젝트: 10=ACTIVE, 11=INACTIVE
-- 영상: 1000~1003

DELETE FROM LS_PJT_TASK_EVENT_LOG;
DELETE FROM LS_PJT_USER_AUTHRT_HSTRY;
DELETE FROM LS_PJT_USER_AUTHRT;
DELETE FROM LS_PJT_DATA_STTS;
DELETE FROM LS_PJT_DATA_MPNG;
DELETE FROM LS_PJT_META;
DELETE FROM LS_PJT_DDLN;
DELETE FROM LS_PJT;
DELETE FROM MNG_ACCT_USER_AUTHRT;
DELETE FROM MNG_ACCT_AUTHRT;
DELETE FROM MNG_ACCT_USER;

INSERT INTO MNG_ACCT_USER (USER_NO, USER_ID, USER_NM, USER_EMAIL, USE_YN, REG_DT) VALUES
  (1,   'reviewer1', '검수자1', 'r1@example.com', 'Y', CURRENT_TIMESTAMP),
  (100, 'worker100', '작업자100', 'w100@example.com', 'Y', CURRENT_TIMESTAMP),
  (101, 'worker101', '작업자101', 'w101@example.com', 'Y', CURRENT_TIMESTAMP),
  (200, 'worker200', '작업자200', 'w200@example.com', 'N', CURRENT_TIMESTAMP);

INSERT INTO MNG_ACCT_AUTHRT (AUTHRT_CD, AUTHRT_NM, USE_YN) VALUES
  ('REVIEWER', '검수자', 'Y'),
  ('WORKER',   '작업자', 'Y');

INSERT INTO MNG_ACCT_USER_AUTHRT (USER_NO, AUTHRT_CD, REG_DT) VALUES
  (1,   'REVIEWER', CURRENT_TIMESTAMP),
  (100, 'WORKER',   CURRENT_TIMESTAMP),
  (101, 'WORKER',   CURRENT_TIMESTAMP),
  (200, 'WORKER',   CURRENT_TIMESTAMP);

INSERT INTO LS_PJT (PJT_ID, PJT_NM, PJT_DESC, PJT_STTS_CD, USE_YN, REG_USER_NO, REG_DT) VALUES
  (10, '테스트프로젝트A', '활성 프로젝트', 'ACTIVE',   'Y', 1, CURRENT_TIMESTAMP),
  (11, '테스트프로젝트B', '비활성',       'INACTIVE', 'N', 1, CURRENT_TIMESTAMP);
