package kr.co.cudo.authoring.controlnotify.migration;

import kr.co.cudo.authoring.support.PostgresTestContainer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * V7({@code LS_MON_NOTI_ACML.STTS_CD} 폭 20 → 16) 마이그레이션 <b>자체</b>의 성질 검증 —
 * 멱등 · 데이터 보존 · fail-closed · 부속 객체(기본값 · NOT NULL · 인덱스 3종) 보존.
 *
 * <p><b>왜 별도 스키마에서 돌리나</b>: 애플리케이션 컨텍스트가 붙는 {@code klid_at} 은 이미 V7 이 적용된
 * 상태라 <b>축소 전</b> 형상을 관측할 수 없다. 여기서는 전용 스크래치 스키마에 축소 전 형상을 그대로
 * 세우고 실제 V7 스크립트 원문을 그 스키마의 {@code search_path} 에서 실행한다 — V7 이 카탈로그 조회를
 * {@code current_schema()}/{@code to_regclass} 로 스코프하기 때문에 그대로 동작한다
 * ({@code V5StandardColumnRenameGuardIT} 와 동일 골격).
 *
 * <p>커넥션은 Hikari 풀이 아니라 {@link DriverManager} 로 직접 연다. 풀 커넥션에 {@code search_path} 를
 * 걸면 반납 후 다른 테스트에 그 설정이 새어 나간다.
 *
 * <p><b>fail-closed 가 이 파일의 핵심이다</b>: dev DB 는 착수 시점에 접근 불가라 초과 행 존재 여부가
 * <b>미확인</b>이었다. 조용히 자르면 상태값이 훼손되어 윈도우가 영영 flush 되지 않으므로, 초과 행이
 * 하나라도 있으면 중단해야 한다.
 *
 * @design ERD-027
 */
class V7MonNotiAcmlSttsWidthGuardIT {

    private static final Path V7_SQL = Paths.get(
            "src/main/resources/db/migration/V7__narrow_mon_noti_acml_stts_cd_to_std_width.sql");

    /** 테스트마다 다른 스키마를 쓴다 — 같은 컨테이너를 공유하므로 이름이 겹치면 서로를 지운다. */
    private static final AtomicInteger SCHEMA_SEQ = new AtomicInteger();

    private static final String TABLE = "ls_mon_noti_acml";

    /** 축소 <b>전</b> 형상 — V1 베이스라인의 정의를 그대로 옮긴 것이다(FK 만 뺀다, 부모 테이블이 없다). */
    private static final String PRE_NARROW_DDL = """
            CREATE TABLE ls_mon_noti_acml (
                noti_acml_sn    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                raw_sn          bigint NOT NULL,
                stts_cd         character varying(20) DEFAULT 'PENDING' NOT NULL,
                export_rprcs_yn character(1) DEFAULT 'N' NOT NULL,
                chg_dtl_cn      text DEFAULT '{}' NOT NULL,
                reg_dt          timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                mdfcn_dt        timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
            )""";

    private String schema;
    private Connection conn;

    @BeforeEach
    void setUp() throws SQLException {
        schema = "v7_guard_" + SCHEMA_SEQ.incrementAndGet();
        conn = DriverManager.getConnection(
                PostgresTestContainer.INSTANCE.getJdbcUrl(),
                PostgresTestContainer.INSTANCE.getUsername(),
                PostgresTestContainer.INSTANCE.getPassword());
        exec("CREATE SCHEMA " + schema);
        exec("SET search_path TO " + schema);
        exec(PRE_NARROW_DDL);
        exec("CREATE INDEX idx_lmna_stts_reg ON ls_mon_noti_acml (stts_cd, reg_dt)");
        exec("CREATE INDEX idx_lmna_stts_mdfcn ON ls_mon_noti_acml (stts_cd, mdfcn_dt)");
        exec("CREATE UNIQUE INDEX uk_lmna_raw_pending ON ls_mon_noti_acml (raw_sn)"
                + " WHERE stts_cd = 'PENDING'");
    }

    @AfterEach
    void tearDown() throws SQLException {
        if (conn != null) {
            try (Statement st = conn.createStatement()) {
                st.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            } finally {
                conn.close();
            }
        }
    }

    // ------------------------------------------------------------------ 멱등

    @Test
    @DisplayName("V7을_두_번_적용해도_안전하다")
    void migrationIsIdempotent() throws Exception {
        // given
        seedWindow(1L, "PENDING");

        // when — 두 번 적용(두 번째는 이미 목표 폭이라 테이블 재작성 자체가 일어나지 않아야 한다)
        applyV7();
        applyV7();

        // then
        assertThat(charMaxLength()).isEqualTo(16);
        assertThat(scalarLong("SELECT count(*) FROM ls_mon_noti_acml")).isEqualTo(1L);
    }

    // ------------------------------------------------------------------ 데이터 보존

    @Test
    @DisplayName("기존_윈도우의_상태값과_누적_변경이_축소_후에도_보존된다")
    void existingRowsSurviveNarrowing() throws Exception {
        // given — 실제로 쓰이는 값 둘. 축소가 재생성이면 사라질 행들이다.
        seedWindow(11L, "PENDING");
        seedWindow(12L, "FLUSHING");

        // when
        applyV7();

        // then — 행수·값이 그대로다(8자 FLUSHING 도 잘리지 않는다)
        assertThat(scalarLong("SELECT count(*) FROM ls_mon_noti_acml")).isEqualTo(2L);
        assertThat(scalarString("SELECT stts_cd FROM ls_mon_noti_acml WHERE raw_sn = 11"))
                .isEqualTo("PENDING");
        assertThat(scalarString("SELECT stts_cd FROM ls_mon_noti_acml WHERE raw_sn = 12"))
                .isEqualTo("FLUSHING");
        assertThat(scalarString("SELECT chg_dtl_cn FROM ls_mon_noti_acml WHERE raw_sn = 11"))
                .isEqualTo("{\"frames\":{\"296\":[\"LABEL_ADDED\"]}}");
    }

    // ------------------------------------------------------------------ fail-closed

    @Test
    @DisplayName("상태값이_목표_폭을_넘으면_마이그레이션이_중단된다")
    void abortsWhenStatusExceedsTargetWidth() throws Exception {
        // given — 목표 폭 16 을 넘는 값 2건(17자·19자). 건수와 최장 길이를 구분해 세는지 보려고
        //   길이를 다르게 둔다. 조용히 자르면 그 윈도우는 어느 상태로도 해석되지 않아 영영 flush 되지 않는다.
        String longest = "B".repeat(19);
        exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd) VALUES (21, '" + "A".repeat(17) + "')");
        exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd) VALUES (22, '" + longest + "')");

        // when / then — 중단되고, DO 블록은 원자적이라 폭도 그대로다
        assertThatThrownBy(this::applyV7)
                .isInstanceOf(SQLException.class)
                .satisfies(e -> assertGuardMessage(e, TABLE + ".stts_cd", 16, 2, 19, longest));
        assertThat(charMaxLength()).isEqualTo(20);
        assertThat(scalarLong("SELECT count(*) FROM ls_mon_noti_acml")).isEqualTo(2L);
    }

    @Test
    @DisplayName("목표_폭_이하_값은_그대로_통과한다")
    void acceptsValuesWithinTargetWidth() throws Exception {
        // given — 경계값 16자
        exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd) VALUES (31, '" + "S".repeat(16) + "')");

        // when
        applyV7();

        // then
        assertThat(charMaxLength()).isEqualTo(16);
        assertThat(scalarString("SELECT stts_cd FROM ls_mon_noti_acml WHERE raw_sn = 31"))
                .isEqualTo("S".repeat(16));
    }

    // ------------------------------------------------------------------ 부속 객체 보존

    @Test
    @DisplayName("기본값과_널제약과_인덱스_3종이_축소_후에도_유지된다")
    void defaultsAndIndexesSurviveNarrowing() throws Exception {
        // when
        applyV7();

        // then — 기본값·NOT NULL
        assertThat(columnDefault()).contains("PENDING");
        assertThat(scalarString("SELECT is_nullable FROM information_schema.columns"
                + " WHERE table_schema = current_schema()"
                + " AND table_name = '" + TABLE + "' AND column_name = 'stts_cd'")).isEqualTo("NO");

        // then — 인덱스 3종(부분 유니크의 술어에 이 컬럼이 있다)
        assertThat(indexDef("idx_lmna_stts_reg")).contains("stts_cd").contains("reg_dt");
        assertThat(indexDef("idx_lmna_stts_mdfcn")).contains("stts_cd").contains("mdfcn_dt");
        assertThat(indexDef("uk_lmna_raw_pending"))
                .contains("UNIQUE").contains("raw_sn").contains("PENDING");

        // then — 부분 유니크가 실제로 강제되는지(정의 문자열만 보면 무력화를 놓친다)
        exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd) VALUES (41, 'PENDING')");
        assertThatThrownBy(() ->
                exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd) VALUES (41, 'PENDING')"))
                .isInstanceOf(SQLException.class);
    }

    /**
     * 중단 사유가 <b>이 가드가 만든 것</b>인지 확인한다 — 아무 SQLException 이나 통과하면 가드의 존재
     * 이유가 사라진다. PG 가 스스로 내는 {@code value too long for type character varying(N)} 로는
     * 통과하지 못한다.
     *
     * <p>동시에 <b>실제 데이터 값이 새지 않는지</b>도 단언한다(CWE-209) — 사람이 조치할 수 있게
     * 건수와 최장 길이만 싣는 것이 설계 의도다.
     */
    private void assertGuardMessage(Throwable e, String qualifiedColumn, int targetLen,
                                    long overCount, int maxLen, String secretValue) {
        String msg = String.valueOf(e.getMessage());
        assertThat(msg)
                .as("가드가 만든 중단 사유여야 한다 — PG 원문 오류(value too long)로는 통과하지 못한다")
                .contains(qualifiedColumn)
                .contains(targetLen + "자")
                .contains("초과 행 " + overCount + "건")
                .contains("최장 " + maxLen + "자");
        assertThat(msg)
                .as("초과한 값 자체를 메시지에 실으면 로그로 새어 나간다 (CWE-209)")
                .doesNotContain(secretValue);
    }

    // ------------------------------------------------------------------ 내부

    private void applyV7() throws IOException, SQLException {
        assertThat(Files.exists(V7_SQL)).as("V7 마이그레이션 파일이 존재해야 한다 (%s)", V7_SQL).isTrue();
        exec(Files.readString(V7_SQL));
    }

    private void seedWindow(long rawSn, String status) throws SQLException {
        exec("INSERT INTO ls_mon_noti_acml (raw_sn, stts_cd, chg_dtl_cn) VALUES ("
                + rawSn + ", '" + status + "', '{\"frames\":{\"296\":[\"LABEL_ADDED\"]}}')");
    }

    private void exec(String sql) throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute(sql);
        }
    }

    private int charMaxLength() throws SQLException {
        return (int) scalarLong("SELECT character_maximum_length FROM information_schema.columns"
                + " WHERE table_schema = current_schema()"
                + " AND table_name = '" + TABLE + "' AND column_name = 'stts_cd'");
    }

    private String columnDefault() throws SQLException {
        return scalarString("SELECT column_default FROM information_schema.columns"
                + " WHERE table_schema = current_schema()"
                + " AND table_name = '" + TABLE + "' AND column_name = 'stts_cd'");
    }

    private String indexDef(String indexName) throws SQLException {
        String def = scalarString("SELECT indexdef FROM pg_indexes"
                + " WHERE schemaname = current_schema()"
                + " AND tablename = '" + TABLE + "' AND indexname = '" + indexName + "'");
        assertThat(def).as("인덱스 %s 가 존재해야 한다", indexName).isNotNull();
        return def;
    }

    private long scalarLong(String sql) throws SQLException {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getLong(1) : 0L;
        }
    }

    private String scalarString(String sql) throws SQLException {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        }
    }
}
