package kr.co.cudo.authoring.meta;

import kr.co.cudo.authoring.assignment.service.ReviewApprovalGate;
import kr.co.cudo.authoring.assignment.repository.LsTaskAssignmentRepository;
import kr.co.cudo.authoring.batch.repository.LsDataMetaRepository;
import kr.co.cudo.authoring.batch.repository.LsDataSrcRepository;
import kr.co.cudo.authoring.common.security.Channel;
import kr.co.cudo.authoring.common.security.Role;
import kr.co.cudo.authoring.common.security.TokenClaims;
import kr.co.cudo.authoring.meta.entity.LsDataMetaReview;
import kr.co.cudo.authoring.meta.repository.LsDataMetaReviewRepository;
import kr.co.cudo.authoring.meta.service.MetaService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEventPublisher;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Phase 7 (버그 F 완성) — {@link MetaService#autoApproveOnVideoApproval} 단위 테스트(Mockito).
 *
 * <p>영상 검수 승인 시 해당 rawSn 의 시계열 메타 검토행(LS_DATA_META_REVIEW)을 같은 승인 트랜잭션에서
 * 자동 확정(APPROVED)해, export/데이터마트 뷰 {@code V_COMPLETED_META}(RVW_STTS_CD='APPROVED'만 노출)에
 * 시계열 메타가 누락되지 않도록 한다. event_annotation 자동 확정 로직을 그대로 미러링한다:
 * <ul>
 *   <li>{@code AUTO_GENERATED}/{@code PENDING} → {@code APPROVED} (자동 확정, 전이 후 flush).</li>
 *   <li>{@code REJECTED}: 명시 반려 존중 — 자동 승인 제외.</li>
 *   <li>{@code APPROVED}: 이미 승인 — 멱등 skip.</li>
 *   <li>검토행 없는 영상: no-op.</li>
 * </ul>
 */
class MetaServiceAutoApproveTest {

    private static final Long RAW_SN = 8100L;
    private static final String ACTOR_SUB = "2001";

    private LsDataMetaRepository metaRepository;
    private LsDataSrcRepository srcRepository;
    private LsTaskAssignmentRepository authrtRepository;
    private LsDataMetaReviewRepository metaReviewRepository;
    private ApplicationEventPublisher eventPublisher;
    private ReviewApprovalGate approvalGate;
    private MetaService service;

    @BeforeEach
    void setUp() {
        metaRepository = mock(LsDataMetaRepository.class);
        srcRepository = mock(LsDataSrcRepository.class);
        authrtRepository = mock(LsTaskAssignmentRepository.class);
        metaReviewRepository = mock(LsDataMetaReviewRepository.class);
        eventPublisher = mock(ApplicationEventPublisher.class);
        approvalGate = mock(ReviewApprovalGate.class);

        service = new MetaService(metaRepository, srcRepository, authrtRepository,
                metaReviewRepository, eventPublisher, approvalGate);
    }

    private TokenClaims reviewer() {
        return new TokenClaims(ACTOR_SUB, Role.REVIEWER, Channel.INTERNAL, Instant.now().plusSeconds(600));
    }

    private LsDataMetaReview reviewWith(String status) {
        // 실제 엔티티로 상태 전이(APPROVED)를 실검증 — createAuto → 필요 시 approve/reject 로 목표 상태 구성.
        LsDataMetaReview review = LsDataMetaReview.createAuto(
                1L, RAW_SN, null, LsDataMetaReview.META_TYPE_EXTERNAL, null, LsDataMetaReview.STTS_PENDING);
        if (LsDataMetaReview.STTS_APPROVED.equals(status)) {
            review.approve("prev-reviewer", LocalDateTime.now());
        } else if (LsDataMetaReview.STTS_REJECTED.equals(status)) {
            review.reject("반려 사유", "prev-reviewer", LocalDateTime.now());
        } else if (LsDataMetaReview.STTS_AUTO_GENERATED.equals(status)) {
            // createAuto 는 PENDING 으로 만들었으므로 AUTO_GENERATED 로 재구성
            review = LsDataMetaReview.createAuto(
                    1L, RAW_SN, null, LsDataMetaReview.META_TYPE_VLM, null, LsDataMetaReview.STTS_AUTO_GENERATED);
        }
        return review;
    }

    @Test
    @DisplayName("영상승인시_AUTO_GENERATED_시계열메타검토_자동APPROVED")
    void autoApprove_whenAutoGenerated_transitionsToApprovedAndFlushes() {
        LsDataMetaReview review = reviewWith(LsDataMetaReview.STTS_AUTO_GENERATED);
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN)).thenReturn(List.of(review));

        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        assertThat(review.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        assertThat(review.getRvwId()).isEqualTo(ACTOR_SUB);
        verify(metaReviewRepository).flush();
    }

    @Test
    @DisplayName("영상승인시_PENDING_시계열메타검토_자동APPROVED")
    void autoApprove_whenPending_transitionsToApproved() {
        LsDataMetaReview review = reviewWith(LsDataMetaReview.STTS_PENDING);
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN)).thenReturn(List.of(review));

        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        assertThat(review.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        assertThat(review.getRvwId()).isEqualTo(ACTOR_SUB);
        verify(metaReviewRepository).flush();
    }

    @Test
    @DisplayName("영상승인시_REJECTED_시계열메타검토는_자동승인_제외")
    void autoApprove_whenRejected_isSkipped() {
        LsDataMetaReview review = reviewWith(LsDataMetaReview.STTS_REJECTED);
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN)).thenReturn(List.of(review));

        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        // 명시 반려 존중 — 상태 불변, 전이 0건이므로 flush 미호출.
        assertThat(review.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_REJECTED);
        verify(metaReviewRepository, never()).flush();
    }

    @Test
    @DisplayName("이미_APPROVED_시계열메타검토는_멱등_skip")
    void autoApprove_whenAlreadyApproved_isIdempotentNoOp() {
        LsDataMetaReview review = reviewWith(LsDataMetaReview.STTS_APPROVED);
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN)).thenReturn(List.of(review));

        // 재전이 시도 시 ensureReviewable() 이 CONFLICT 를 던지면 안 됨 — 필터링으로 approve 미호출.
        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        assertThat(review.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        // 상태 필터 후 승인 대상이 없으므로 rvwId 는 이전 값 유지(멱등).
        assertThat(review.getRvwId()).isEqualTo("prev-reviewer");
        verify(metaReviewRepository, never()).flush();
    }

    @Test
    @DisplayName("시계열메타검토_없는영상_승인은_no-op")
    void autoApprove_whenNoReviewRows_isNoOp() {
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN)).thenReturn(List.of());

        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        verify(metaReviewRepository, never()).flush();
    }

    @Test
    @DisplayName("혼합상태_검토행들_중_PENDING_AUTO_GENERATED만_승인되고_flush는_1회")
    void autoApprove_mixedStatuses_onlyApprovablesTransition() {
        LsDataMetaReview pending = reviewWith(LsDataMetaReview.STTS_PENDING);
        LsDataMetaReview auto = reviewWith(LsDataMetaReview.STTS_AUTO_GENERATED);
        LsDataMetaReview rejected = reviewWith(LsDataMetaReview.STTS_REJECTED);
        LsDataMetaReview approved = reviewWith(LsDataMetaReview.STTS_APPROVED);
        when(metaReviewRepository.findAllByDataRawSn(RAW_SN))
                .thenReturn(List.of(pending, auto, rejected, approved));

        service.autoApproveOnVideoApproval(RAW_SN, reviewer());

        assertThat(pending.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        assertThat(auto.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        assertThat(rejected.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_REJECTED);
        assertThat(approved.getRvwSttsCd()).isEqualTo(LsDataMetaReview.STTS_APPROVED);
        // 전이 1건 이상 → flush 정확히 1회.
        verify(metaReviewRepository).flush();
    }
}
