#!/usr/bin/env bash
set -euo pipefail
# ============================================================================
# apply-migrations.sh — [대상 서버] db/incremental 의 증분 SQL 을 순서대로 1회씩 적용
#
#   ★ 왜 이 스크립트가 생겼나 (2026-09-06)
#     온프렘은 Flyway 를 끈다(확정). 그래서 테이블을 만드는 경로는 설치의 schema.sql 로드
#     하나뿐이고, 그 뒤에 추가된 마이그레이션(V32~)은 <아무도 적용하지 않았다>. 설치 스크립트
#     전체에 'incremental' 참조가 0건이었다.
#     그 결과가 위험한 이유는 <조용하기> 때문이다:
#       · 새 WAR 만 올라가고 DB 는 옛 형상 그대로 남는다
#       · ddl-auto=validate 는 이 앱에서 Hibernate 에 도달하지 않아 <기동이 성공한다>
#       · 화면·배치가 그 테이블을 처음 건드릴 때 비로소 터진다
#     ⇒ "기동됐으니 스키마가 맞다"는 판단이 성립하지 않는 구조라, 적용을 사람 손에 맡기면
#       빠뜨렸는지조차 알 수 없다. 이 스크립트가 그 자리를 없앤다.
#
#   ★ 적용 이력을 DB 에 남긴다 (2026-09-06 사용자 확정)
#     db/incremental/README.md 가 "무엇이 적용됐는지 남기는 자리가 아직 없다"를 미확정으로
#     남겨 뒀고, 선택지 셋 중 <① 적용 이력 표 + 스크립트가 기록>이 채택됐다.
#     ⚠ Flyway 를 켜는 안(②)은 채택되지 않았다 — 여러 노드가 함께 뜨는 형상에서 기동 시
#       advisory lock 경합을 피하려고 끈 것이므로 그 판단을 뒤집지 않는다.
#     ⇒ 이력 표는 <이 스크립트가 소유>하며 앱은 읽지 않는다. flyway_schema_history 와 무관하다.
#
#   ★ search_path 를 반드시 건다 — 이것이 이 스크립트의 존재 이유 절반이다.
#     V1 만 스키마를 한정하고 V2 이후는 전부 비한정 식별자다. search_path 가 klid_at 이 아니면
#       · ALTER/DROP 은 없는 표를 찾다 <실패>하고 (시끄러워서 오히려 안전)
#       · CREATE TABLE IF NOT EXISTS 는 <public 에 빈 표를 새로 만든다> — 오류가 나지 않는다.
#     앱은 klid_at 을 보므로 그 표는 영원히 비어 있고 아무도 모른다. 적용 후 그 오생성을 검사한다.
#
#   ★ 한 파일 = 한 트랜잭션 = 한 세션
#     같은 트랜잭션 안에서 ① 자문 잠금 ② 중복 적용 재확인 ③ 파일 실행 ④ 이력 기록을 한다.
#     여러 노드·여러 사람이 동시에 돌려도 한 번만 적용된다(PostgreSQL 은 DDL 도 트랜잭션이다).
#     ⚠ 그래서 CREATE INDEX CONCURRENTLY 처럼 <트랜잭션 안에서 못 도는> 문장이 든 파일은
#       받지 않고 멈춘다 — 조용히 절반만 적용되는 것보다 낫다.
#
#   사용법
#     ./scripts/apply-migrations.sh --status      현황만 본다 (아무것도 바꾸지 않음)
#     ./scripts/apply-migrations.sh --dry-run     적용할 파일만 보여준다
#     ./scripts/apply-migrations.sh               미적용분을 번호순으로 적용
#     ./scripts/apply-migrations.sh --mark-only   ★ 실행하지 않고 <적용된 것으로 기록>만 한다
#
#     ⚠⚠ --mark-only 는 <신규 설치 직후>에만 쓴다.
#       설치가 로드한 schema.sql 은 그 시점의 증분을 이미 <포함>한 통합본이라, 그 위에 같은
#       증분을 다시 실행하면 멱등하지 않은 문장(ALTER ADD COLUMN 등)에서 실패한다.
#       그렇다고 기록을 안 남기면 다음 회차에 그 증분이 미적용으로 보여 다시 실행된다.
#       ⇒ 신규 설치 흐름은 "schema.sql 로드 → --mark-only" 다.
#       기존 운영 DB 에 쓰면 <적용하지 않은 것을 적용했다고 기록>하므로 절대 쓰지 말 것.
#
#   접속 정보는 16-load-schema.sh 와 <같은 환경변수 축>을 읽는다(두 번째 진실원 금지).
#     CONTROL_DB_HOST/PORT/NAME/USERNAME/PASSWORD · DB_APP_USER · DB_APP_PASSWORD · DB_SCHEMA
# ============================================================================

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SELF_DIR}/lib/common.sh"

ONPREM="$(onprem_root)"
INC_DIR="${ONPREM}/db/incremental"

MODE="apply"       # apply | status | dry-run | mark-only
for arg in "$@"; do
  case "${arg}" in
    --status)    MODE="status" ;;
    --dry-run)   MODE="dry-run" ;;
    --mark-only) MODE="mark-only" ;;
    --help|-h)   sed -n '3,60p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "알 수 없는 옵션: ${arg} (--help 로 사용법)" ;;
  esac
done

require_cmd psql

# ---- 접속 축 (16-load-schema.sh 와 동일) ----
# ★ 설정 파일이 있으면 거기서 읽는다 — 환경변수가 이긴다(2026-09-07 신설).
klid_load_db_props
CONTROL_DB_NAME="${CONTROL_DB_NAME:-klid_system}"
DB_APP_USER="${DB_APP_USER:-${CONTROL_DB_USERNAME:-klid_user}}"
DB_SCHEMA="${DB_SCHEMA:-klid_at}"
# SQL 리터럴로 보간되므로 allowlist 로 먼저 검증한다(인젝션 차단).
[[ "${DB_SCHEMA}" =~ ^[a-z][a-z0-9_]{0,62}$ ]] \
  || die "[mig] 부적합한 DB_SCHEMA='${DB_SCHEMA}' — 소문자 시작 + [a-z0-9_], 최대 63자만 허용합니다."

DB_APP_PASSWORD="${DB_APP_PASSWORD:-${CONTROL_DB_PASSWORD:-}}"
: "${DB_APP_PASSWORD:?DB_APP_PASSWORD 또는 CONTROL_DB_PASSWORD 가 필요합니다(앱 유저 비밀번호)}"
# ★ CONTROL_DB_HOST 는 "host:port,host" 형태일 수 있다 — 그대로 넘기면 접속이 실패한다.
PGHOST_OVERRIDE="${PGHOST:-}" PGPORT_OVERRIDE="${PGPORT:-}" klid_pg_env
export PGPASSWORD="${DB_APP_PASSWORD}"
# ★ 전 세션 공통 — 비한정 식별자가 klid_at 에 떨어지게 한다(위 헤더의 조용한 오생성 방어).
export PGOPTIONS="-c search_path=${DB_SCHEMA}"

HIST_TBL="ls_schm_aplcn_hstry"     # 스키마적용이력 (SCHM 스키마 · APLCN 적용 · HSTRY 이력)
LOCK_KEY="815301"                  # 이 스크립트 전용 자문 잠금 키(임의 상수, 충돌만 피하면 된다)

psql_q() { psql -tAX -v ON_ERROR_STOP=1 -U "${DB_APP_USER}" -d "${CONTROL_DB_NAME}" "$@"; }

# ---- 0) 접속 확인 (죽은 접속으로 아래 판정을 하지 않는다) ----
psql_q -c "SELECT 1" >/dev/null 2>&1 \
  || die "[mig] DB 접속 실패 — host=${PGHOST}:${PGPORT} user=${DB_APP_USER} db=${CONTROL_DB_NAME}"

# ---- 1) 이력 표 보장 (멱등) ----
#   물리명·자료형은 행안부 공통표준용어/표준도메인을 따른다:
#     스키마 SCHM · 적용 APLCN · 이력 HSTRY · 일련번호 SN · 파일 FILE · 명 NM
#     버전 VER · 해시 HASH · 값 VL · 상태 STTS · 코드 CD · 등록자 RGTR · 일시 DT
psql -v ON_ERROR_STOP=1 -U "${DB_APP_USER}" -d "${CONTROL_DB_NAME}" -q <<SQL
CREATE TABLE IF NOT EXISTS ${HIST_TBL} (
    schm_aplcn_hstry_sn bigint GENERATED BY DEFAULT AS IDENTITY,
    aplcn_file_nm       varchar(200) NOT NULL,
    ver_nm              varchar(20)  NOT NULL,
    file_hash_vl        varchar(64)  NOT NULL,
    aplcn_stts_cd       varchar(20)  NOT NULL,
    rgtr_id             varchar(100),
    reg_dt              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ${HIST_TBL}_pkey PRIMARY KEY (schm_aplcn_hstry_sn)
);
-- 성공은 버전당 1회뿐. 실패 기록은 여러 번 남을 수 있어야 재시도가 가능하다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_${HIST_TBL}_ver
    ON ${HIST_TBL} (ver_nm) WHERE aplcn_stts_cd = 'SUCCESS';
COMMENT ON TABLE ${HIST_TBL} IS '스키마적용이력 — 온프렘 증분 SQL 적용 기록(설치 도구 소유, 앱 미사용)';
SQL

# ---- 2) 증분 파일 목록 (번호 오름차순 — 사전순이 아니다) ----
[[ -d "${INC_DIR}" ]] || die "[mig] 증분 디렉터리가 없습니다: ${INC_DIR}"
mapfile -t FILES < <(
  find "${INC_DIR}" -maxdepth 1 -type f -name 'V*.sql' -print \
    | while read -r f; do
        b="$(basename "${f}")"
        n="${b#V}"; n="${n%%__*}"
        [[ "${n}" =~ ^[0-9]+$ ]] || continue
        printf '%s\t%s\n' "${n}" "${f}"
      done | sort -n -k1,1 | cut -f2-
)
[[ "${#FILES[@]}" -gt 0 ]] && ok "[mig] 증분 파일 ${#FILES[@]}개 발견: ${INC_DIR}" \
                           || { ok "[mig] 적용할 증분 파일이 없습니다: ${INC_DIR}"; exit 0; }

applied_hash_of() {   # <ver> → 성공 기록의 해시(없으면 빈 문자열)
  psql_q -c "SELECT file_hash_vl FROM ${HIST_TBL} WHERE ver_nm='$1' AND aplcn_stts_cd='SUCCESS' LIMIT 1;"
}

# ---- 3) 현황 판정 ----
PENDING=(); APPLIED=0
for f in "${FILES[@]}"; do
  b="$(basename "${f}")"; ver="V${b#V}"; ver="${ver%%__*}"
  h="$(_hash_file sha256 "${f}")"
  prev="$(applied_hash_of "${ver}")"
  if [[ -n "${prev}" ]]; then
    if [[ "${prev}" != "${h}" ]]; then
      # ★ 조용히 재적용하지 않는다 — 적용된 것과 매체의 파일이 <다른 내용>이다.
      die "[mig] ${ver} 는 이미 적용됐는데 파일 내용이 다릅니다.
     적용 당시 해시: ${prev}
     지금 매체 해시: ${h}
     증분 파일은 한 번 나가면 고치지 않는 것이 규칙입니다(README: 파일명까지 그대로 복사).
     내용을 바꿔야 하면 새 번호로 파일을 추가하세요. 여기서 임의로 다시 적용하지 않습니다."
    fi
    APPLIED=$((APPLIED+1))
    [[ "${MODE}" == "status" ]] && info "[mig]   적용됨  ${b}"
  else
    PENDING+=("${f}")
    [[ "${MODE}" == "status" ]] && warn "[mig]   미적용  ${b}"
  fi
done

info "[mig] 적용됨 ${APPLIED}건 · 미적용 ${#PENDING[@]}건  (스키마=${DB_SCHEMA}, DB=${CONTROL_DB_NAME})"
[[ "${MODE}" == "status" ]] && exit 0
if [[ "${#PENDING[@]}" -eq 0 ]]; then ok "[mig] 적용할 것이 없습니다 — 최신입니다."; exit 0; fi

if [[ "${MODE}" == "dry-run" ]]; then
  for f in "${PENDING[@]}"; do info "[mig] (dry-run) 적용 예정: $(basename "${f}")"; done
  info "— dry-run, DB 미변경 —"; exit 0
fi

ACTOR="${SUDO_USER:-${USER:-unknown}}@$(hostname -s 2>/dev/null || echo unknown)"

# ---- 4) mark-only — 실행하지 않고 기록만 ----
if [[ "${MODE}" == "mark-only" ]]; then
  warn "[mig] ★ --mark-only — SQL 을 실행하지 않고 <적용된 것으로 기록>만 합니다."
  warn "[mig]   신규 설치 직후(schema.sql 이 이미 이 증분을 포함)에만 올바릅니다."
  warn "[mig]   기존 운영 DB 라면 지금 중단하세요 — 적용하지 않은 것을 적용했다고 남깁니다."
  confirm "정말 기록만 남길까요?" || die "[mig] 사용자가 중단했습니다."
  for f in "${PENDING[@]}"; do
    b="$(basename "${f}")"; ver="V${b#V}"; ver="${ver%%__*}"; h="$(_hash_file sha256 "${f}")"
    psql -v ON_ERROR_STOP=1 -U "${DB_APP_USER}" -d "${CONTROL_DB_NAME}" -q -c \
      "INSERT INTO ${HIST_TBL}(aplcn_file_nm, ver_nm, file_hash_vl, aplcn_stts_cd, rgtr_id)
       VALUES ('${b}', '${ver}', '${h}', 'SUCCESS', '${ACTOR} (mark-only)');"
    ok "[mig] 기록만: ${b}"
  done
  exit 0
fi

# ---- 5) 실제 적용 ----
for f in "${PENDING[@]}"; do
  b="$(basename "${f}")"; ver="V${b#V}"; ver="${ver%%__*}"; h="$(_hash_file sha256 "${f}")"

  # ★ 트랜잭션 밖에서만 도는 문장은 받지 않는다 — 이 스크립트의 원자성 전제가 깨진다.
  if grep -qiE 'CONCURRENTLY|VACUUM|CREATE +DATABASE|CREATE +TABLESPACE' "${f}"; then
    die "[mig] ${b} 에 트랜잭션 안에서 실행할 수 없는 문장이 있습니다(CONCURRENTLY/VACUUM 등).
     이 스크립트는 한 파일을 한 트랜잭션으로 적용해 부분 적용을 막습니다.
     해당 파일은 절차를 따로 정해 사람이 적용하고, 적용 후 --mark-only 없이 이력에 직접 남기세요."
  fi

  info "[mig] 적용: ${b}"
  wrapper="$(mktemp)"; trap 'rm -f "${wrapper}"' EXIT
  {
    # 같은 트랜잭션 안에서 잠금 → 중복 재확인 → 파일 실행 → 이력 기록.
    echo "SELECT pg_advisory_xact_lock(${LOCK_KEY});"
    echo "DO \$klid\$ BEGIN"
    echo "  IF EXISTS (SELECT 1 FROM ${HIST_TBL} WHERE ver_nm='${ver}' AND aplcn_stts_cd='SUCCESS') THEN"
    echo "    RAISE EXCEPTION '이미 적용됨(${ver}) — 다른 노드가 방금 적용했습니다.';"
    echo "  END IF;"
    echo "END \$klid\$;"
    echo "\\i ${f}"
    echo "INSERT INTO ${HIST_TBL}(aplcn_file_nm, ver_nm, file_hash_vl, aplcn_stts_cd, rgtr_id)"
    echo "VALUES ('${b}', '${ver}', '${h}', 'SUCCESS', '${ACTOR}');"
  } > "${wrapper}"

  if psql -1 -v ON_ERROR_STOP=1 -U "${DB_APP_USER}" -d "${CONTROL_DB_NAME}" -q -f "${wrapper}"; then
    ok "[mig] 적용 완료: ${b}"
  else
    # 트랜잭션이 통째로 롤백됐으므로 SUCCESS 도 남지 않는다. 실패 사실만 별도로 남긴다.
    psql -v ON_ERROR_STOP=1 -U "${DB_APP_USER}" -d "${CONTROL_DB_NAME}" -q -c \
      "INSERT INTO ${HIST_TBL}(aplcn_file_nm, ver_nm, file_hash_vl, aplcn_stts_cd, rgtr_id)
       VALUES ('${b}', '${ver}', '${h}', 'FAILED', '${ACTOR}');" || true
    die "[mig] ★ 적용 실패: ${b} — 이 파일의 변경은 <전부 롤백>됐습니다(부분 적용 없음).
     뒤 번호 파일은 실행하지 않았습니다. 원인을 해소한 뒤 이 스크립트를 다시 실행하세요."
  fi
  rm -f "${wrapper}"; trap - EXIT
done

# ---- 6) 적용 후 검증 — public 에 오생성되지 않았는지 (README 의 조용한 실패) ----
if [[ "${DB_SCHEMA}" != "public" ]]; then
  stray="$(psql_q -c "SELECT count(*) FROM information_schema.tables
                       WHERE table_schema='public' AND table_type='BASE TABLE'
                         AND (table_name LIKE 'ls\\_%' OR table_name LIKE 'qrtz\\_%');")"
  if [[ "${stray}" != "0" ]]; then
    warn "[mig] ★ public 에 저작도구 표 ${stray}개가 보입니다 — search_path 가 어긋난 채 적용됐을 수 있습니다."
    warn "[mig]   앱은 ${DB_SCHEMA} 를 보므로 그 표는 영원히 비어 있습니다. 즉시 확인하세요:"
    warn "[mig]   psql -c \"SELECT table_schema, table_name FROM information_schema.tables WHERE table_name LIKE 'ls\\_%';\""
  else
    ok "[mig] public 오생성 없음 — 전부 ${DB_SCHEMA} 에 적용됐습니다."
  fi
fi

tbl="$(psql_q -c "SELECT count(*) FROM information_schema.tables WHERE table_schema='${DB_SCHEMA}' AND table_type='BASE TABLE';")"
ok "[mig] 완료 — ${DB_SCHEMA} 테이블 ${tbl}개 · 이번에 적용 ${#PENDING[@]}건"
info "[mig] 현황 재확인:  ./scripts/apply-migrations.sh --status"
