-- =============================================================================
-- 포털 DB 복제본 정합 — LS_DATASET_VIDEO_META 식별자 컬럼 → VARCHAR(30)
--
-- ⚠ 이 스크립트는 애플리케이션 Flyway 가 자동 실행하지 않는다(db/portal/ 는 migration 경로 밖).
--    control 원본(db/migration/V108)과 스키마를 동형으로 유지하기 위한 복제본 정합 DDL 이며,
--    인프라/운영이 포털 DB(PORTAL_DB_*)에 1회 수동 적용한다(V1 프로비저닝 스크립트와 동일 취급).
--
-- 근거: docs/표준용어/산업용어/사업표준용어.csv 도메인 "식별자V30"(VARCHAR 30) 정합.
--       control 원본 V108 과 동일하게 감사 식별자 컬럼을 VARCHAR(30) 으로 통일한다.
--
-- 값 안전성(값 ≤30 확인): REG_ID 는 짧은 식별자(USER_NO/'SYSTEM' 등, 실측 ≤4)라 64→30 축소는
--   truncation 없음.
--
-- 포털 복제본에는 데이터마트 View 가 없어 View 선삭제/재생성 불필요.
-- PostgreSQL 표준 문법.
-- =============================================================================
ALTER TABLE LS_DATASET_VIDEO_META ALTER COLUMN REG_ID TYPE VARCHAR(30);
